# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require_relative 'AddressValidationServiceDefinitions.rb'
require_relative 'AddressValidationServiceDefinitionsMappingRegistry.rb'
require 'soap/rpc/driver'

module FedexWebServices::Soap::AddressValidation

class AddressValidationPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://wsbeta.fedex.com:443/web-services/addressvalidation"

  Methods = [
    [ "http://fedex.com/ws/addressvalidation/v4/addressValidation",
      "addressValidation",
      [ [:in, "AddressValidationRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/addressvalidation/v4", "AddressValidationRequest"]],
        [:out, "AddressValidationReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/addressvalidation/v4", "AddressValidationReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = AddressValidationServiceDefinitionsMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = AddressValidationServiceDefinitionsMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
