# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require 'xsd/qname'

module FedexWebServices; module Soap; module ASYNC


# {http://fedex.com/ws/async/v4}ArtifactPart
#   sequenceNumber - SOAP::SOAPPositiveInteger
#   contents - SOAP::SOAPBase64
class ArtifactPart
  attr_accessor :sequenceNumber
  attr_accessor :contents

  def initialize(sequenceNumber = nil, contents = nil)
    @sequenceNumber = sequenceNumber
    @contents = contents
  end
end

# {http://fedex.com/ws/async/v4}ArtifactRetrievalFilter
#   accessReference - SOAP::SOAPString
#   type - FedexWebServices::Soap::ASYNC::ArtifactType
#   referenceId - SOAP::SOAPString
class ArtifactRetrievalFilter
  attr_accessor :accessReference
  attr_accessor :type
  attr_accessor :referenceId

  def initialize(accessReference = nil, type = nil, referenceId = nil)
    @accessReference = accessReference
    @type = type
    @referenceId = referenceId
  end
end

# {http://fedex.com/ws/async/v4}ClientDetail
#   accountNumber - SOAP::SOAPString
#   meterNumber - SOAP::SOAPString
#   meterInstance - SOAP::SOAPString
#   integratorId - SOAP::SOAPString
#   region - FedexWebServices::Soap::ASYNC::ExpressRegionCode
#   localization - FedexWebServices::Soap::ASYNC::Localization
class ClientDetail
  attr_accessor :accountNumber
  attr_accessor :meterNumber
  attr_accessor :meterInstance
  attr_accessor :integratorId
  attr_accessor :region
  attr_accessor :localization

  def initialize(accountNumber = nil, meterNumber = nil, meterInstance = nil, integratorId = nil, region = nil, localization = nil)
    @accountNumber = accountNumber
    @meterNumber = meterNumber
    @meterInstance = meterInstance
    @integratorId = integratorId
    @region = region
    @localization = localization
  end
end

# {http://fedex.com/ws/async/v4}Localization
#   languageCode - SOAP::SOAPString
#   localeCode - SOAP::SOAPString
class Localization
  attr_accessor :languageCode
  attr_accessor :localeCode

  def initialize(languageCode = nil, localeCode = nil)
    @languageCode = languageCode
    @localeCode = localeCode
  end
end

# {http://fedex.com/ws/async/v4}Notification
#   severity - FedexWebServices::Soap::ASYNC::NotificationSeverityType
#   source - SOAP::SOAPString
#   code - SOAP::SOAPString
#   message - SOAP::SOAPString
#   localizedMessage - SOAP::SOAPString
#   messageParameters - FedexWebServices::Soap::ASYNC::NotificationParameter
class Notification
  attr_accessor :severity
  attr_accessor :source
  attr_accessor :code
  attr_accessor :message
  attr_accessor :localizedMessage
  attr_accessor :messageParameters

  def initialize(severity = nil, source = nil, code = nil, message = nil, localizedMessage = nil, messageParameters = [])
    @severity = severity
    @source = source
    @code = code
    @message = message
    @localizedMessage = localizedMessage
    @messageParameters = messageParameters
  end
end

# {http://fedex.com/ws/async/v4}NotificationParameter
#   id - SOAP::SOAPString
#   value - SOAP::SOAPString
class NotificationParameter
  attr_accessor :id
  attr_accessor :value

  def initialize(id = nil, value = nil)
    @id = id
    @value = value
  end
end

# {http://fedex.com/ws/async/v4}RetrieveJobResultsReply
#   highestSeverity - FedexWebServices::Soap::ASYNC::NotificationSeverityType
#   notifications - FedexWebServices::Soap::ASYNC::Notification
#   transactionDetail - FedexWebServices::Soap::ASYNC::TransactionDetail
#   version - FedexWebServices::Soap::ASYNC::VersionId
#   artifacts - FedexWebServices::Soap::ASYNC::RetrievedArtifact
class RetrieveJobResultsReply
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :artifacts

  def initialize(highestSeverity = nil, notifications = [], transactionDetail = nil, version = nil, artifacts = [])
    @highestSeverity = highestSeverity
    @notifications = notifications
    @transactionDetail = transactionDetail
    @version = version
    @artifacts = artifacts
  end
end

# {http://fedex.com/ws/async/v4}RetrieveJobResultsRequest
#   webAuthenticationDetail - FedexWebServices::Soap::ASYNC::WebAuthenticationDetail
#   clientDetail - FedexWebServices::Soap::ASYNC::ClientDetail
#   transactionDetail - FedexWebServices::Soap::ASYNC::TransactionDetail
#   version - FedexWebServices::Soap::ASYNC::VersionId
#   jobId - SOAP::SOAPString
#   filters - FedexWebServices::Soap::ASYNC::ArtifactRetrievalFilter
class RetrieveJobResultsRequest
  attr_accessor :webAuthenticationDetail
  attr_accessor :clientDetail
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :jobId
  attr_accessor :filters

  def initialize(webAuthenticationDetail = nil, clientDetail = nil, transactionDetail = nil, version = nil, jobId = nil, filters = [])
    @webAuthenticationDetail = webAuthenticationDetail
    @clientDetail = clientDetail
    @transactionDetail = transactionDetail
    @version = version
    @jobId = jobId
    @filters = filters
  end
end

# {http://fedex.com/ws/async/v4}RetrievedArtifact
#   accessReference - SOAP::SOAPString
#   highestSeverity - FedexWebServices::Soap::ASYNC::NotificationSeverityType
#   notifications - FedexWebServices::Soap::ASYNC::Notification
#   type - FedexWebServices::Soap::ASYNC::ArtifactType
#   format - FedexWebServices::Soap::ASYNC::ArtifactFormatType
#   formatSpecification - SOAP::SOAPString
#   referenceId - SOAP::SOAPString
#   parts - FedexWebServices::Soap::ASYNC::ArtifactPart
class RetrievedArtifact
  attr_accessor :accessReference
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :type
  attr_accessor :format
  attr_accessor :formatSpecification
  attr_accessor :referenceId
  attr_accessor :parts

  def initialize(accessReference = nil, highestSeverity = nil, notifications = [], type = nil, format = nil, formatSpecification = nil, referenceId = nil, parts = [])
    @accessReference = accessReference
    @highestSeverity = highestSeverity
    @notifications = notifications
    @type = type
    @format = format
    @formatSpecification = formatSpecification
    @referenceId = referenceId
    @parts = parts
  end
end

# {http://fedex.com/ws/async/v4}TransactionDetail
#   customerTransactionId - SOAP::SOAPString
#   localization - FedexWebServices::Soap::ASYNC::Localization
class TransactionDetail
  attr_accessor :customerTransactionId
  attr_accessor :localization

  def initialize(customerTransactionId = nil, localization = nil)
    @customerTransactionId = customerTransactionId
    @localization = localization
  end
end

# {http://fedex.com/ws/async/v4}WebAuthenticationDetail
#   parentCredential - FedexWebServices::Soap::ASYNC::WebAuthenticationCredential
#   userCredential - FedexWebServices::Soap::ASYNC::WebAuthenticationCredential
class WebAuthenticationDetail
  attr_accessor :parentCredential
  attr_accessor :userCredential

  def initialize(parentCredential = nil, userCredential = nil)
    @parentCredential = parentCredential
    @userCredential = userCredential
  end
end

# {http://fedex.com/ws/async/v4}WebAuthenticationCredential
#   key - SOAP::SOAPString
#   password - SOAP::SOAPString
class WebAuthenticationCredential
  attr_accessor :key
  attr_accessor :password

  def initialize(key = nil, password = nil)
    @key = key
    @password = password
  end
end

# {http://fedex.com/ws/async/v4}VersionId
#   serviceId - SOAP::SOAPString
#   major - SOAP::SOAPInt
#   intermediate - SOAP::SOAPInt
#   minor - SOAP::SOAPInt
class VersionId
  attr_accessor :serviceId
  attr_accessor :major
  attr_accessor :intermediate
  attr_accessor :minor

  def initialize(serviceId = nil, major = nil, intermediate = nil, minor = nil)
    @serviceId = serviceId
    @major = major
    @intermediate = intermediate
    @minor = minor
  end
end

# {http://fedex.com/ws/async/v4}ArtifactFormatType
class ArtifactFormatType < ::String
  BINARY = new("BINARY")
  DOC = new("DOC")
  EPL2 = new("EPL2")
  PDF = new("PDF")
  PNG = new("PNG")
  RTF = new("RTF")
  TEXT = new("TEXT")
  XML = new("XML")
  ZPLII = new("ZPLII")
end

# {http://fedex.com/ws/async/v4}ArtifactType
class ArtifactType < ::String
  AUXILIARY_LABEL = new("AUXILIARY_LABEL")
  CERTIFICATE_OF_ORIGIN = new("CERTIFICATE_OF_ORIGIN")
  COD_RETURN_LABEL = new("COD_RETURN_LABEL")
  COMMERCIAL_INVOICE = new("COMMERCIAL_INVOICE")
  COMMODITIES_BY_TRACKING_NUMBER_REPORT = new("COMMODITIES_BY_TRACKING_NUMBER_REPORT")
  CONDENSED_CRN_REPORT = new("CONDENSED_CRN_REPORT")
  CONSOLIDATED_COMMERCIAL_INVOICE = new("CONSOLIDATED_COMMERCIAL_INVOICE")
  CONSOLIDATED_CUSTOMS_LINEHAUL_REPORT = new("CONSOLIDATED_CUSTOMS_LINEHAUL_REPORT")
  CONSOLIDATED_SOLD_TO_SUMMARY_REPORT = new("CONSOLIDATED_SOLD_TO_SUMMARY_REPORT")
  CRN_REPORT = new("CRN_REPORT")
  CUSTOMS_PACKING_LIST = new("CUSTOMS_PACKING_LIST")
  CUSTOM_CONSOLIDATION_DOCUMENT = new("CUSTOM_CONSOLIDATION_DOCUMENT")
  CUSTOM_PACKAGE_DOCUMENT = new("CUSTOM_PACKAGE_DOCUMENT")
  CUSTOM_SHIPMENT_DOCUMENT = new("CUSTOM_SHIPMENT_DOCUMENT")
  DANGEROUS_GOODS_SHIPPERS_DECLARATION = new("DANGEROUS_GOODS_SHIPPERS_DECLARATION")
  DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_LABEL = new("DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_LABEL")
  FREIGHT_ADDRESS_LABEL = new("FREIGHT_ADDRESS_LABEL")
  GENERAL_AGENCY_AGREEMENT = new("GENERAL_AGENCY_AGREEMENT")
  LOW_CUSTOMS_VALUE_EXCEPTION_PARTY_REPORT = new("LOW_CUSTOMS_VALUE_EXCEPTION_PARTY_REPORT")
  NAFTA_CERTIFICATE_OF_ORIGIN = new("NAFTA_CERTIFICATE_OF_ORIGIN")
  OP_900 = new("OP_900")
  OUTBOUND_LABEL = new("OUTBOUND_LABEL")
  PRO_FORMA_INVOICE = new("PRO_FORMA_INVOICE")
  RETURN_INSTRUCTIONS = new("RETURN_INSTRUCTIONS")
  SERVICE_REPLY = new("SERVICE_REPLY")
  SERVICE_REQUEST = new("SERVICE_REQUEST")
  STANDARD_BROKER_CLEARANCE_PARTY_REPORT = new("STANDARD_BROKER_CLEARANCE_PARTY_REPORT")
  TERMS_AND_CONDITIONS = new("TERMS_AND_CONDITIONS")
end

# {http://fedex.com/ws/async/v4}ExpressRegionCode
class ExpressRegionCode < ::String
  APAC = new("APAC")
  CA = new("CA")
  EMEA = new("EMEA")
  LAC = new("LAC")
  US = new("US")
end

# {http://fedex.com/ws/async/v4}NotificationSeverityType
class NotificationSeverityType < ::String
  ERROR = new("ERROR")
  FAILURE = new("FAILURE")
  NOTE = new("NOTE")
  SUCCESS = new("SUCCESS")
  WARNING = new("WARNING")
end


end; end; end
