# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require_relative 'CloseServiceDefinitions.rb'
require 'soap/mapping'

module FedexWebServices; module Soap; module Close

module CloseServiceDefinitionsMappingRegistry
  EncodedRegistry = ::SOAP::Mapping::EncodedRegistry.new
  LiteralRegistry = ::SOAP::Mapping::LiteralRegistry.new
  NsV5 = "http://fedex.com/ws/close/v5"

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ClientDetail,
    :schema_type => XSD::QName.new(NsV5, "ClientDetail"),
    :schema_element => [
      ["accountNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "AccountNumber")]],
      ["meterNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "MeterNumber")]],
      ["integratorId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "IntegratorId")], [0, 1]],
      ["localization", ["FedexWebServices::Soap::Close::Localization", XSD::QName.new(NsV5, "Localization")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseDocument,
    :schema_type => XSD::QName.new(NsV5, "CloseDocument"),
    :schema_element => [
      ["type", ["FedexWebServices::Soap::Close::CloseDocumentType", XSD::QName.new(NsV5, "Type")], [0, 1]],
      ["shippingCycle", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ShippingCycle")], [0, 1]],
      ["shippingDocumentDisposition", ["FedexWebServices::Soap::Close::ShippingDocumentDispositionType", XSD::QName.new(NsV5, "ShippingDocumentDisposition")], [0, 1]],
      ["accessReference", ["SOAP::SOAPString", XSD::QName.new(NsV5, "AccessReference")], [0, 1]],
      ["resolution", ["SOAP::SOAPNonNegativeInteger", XSD::QName.new(NsV5, "Resolution")], [0, 1]],
      ["copiesToPrint", ["SOAP::SOAPNonNegativeInteger", XSD::QName.new(NsV5, "CopiesToPrint")], [0, 1]],
      ["parts", ["FedexWebServices::Soap::Close::ShippingDocumentPart[]", XSD::QName.new(NsV5, "Parts")], [0, nil]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseDocumentFormat,
    :schema_type => XSD::QName.new(NsV5, "CloseDocumentFormat"),
    :schema_element => [
      ["dispositions", ["FedexWebServices::Soap::Close::ShippingDocumentDispositionDetail[]", XSD::QName.new(NsV5, "Dispositions")], [0, nil]],
      ["topOfPageOffset", ["FedexWebServices::Soap::Close::LinearMeasure", XSD::QName.new(NsV5, "TopOfPageOffset")], [0, 1]],
      ["imageType", ["FedexWebServices::Soap::Close::ShippingDocumentImageType", XSD::QName.new(NsV5, "ImageType")], [0, 1]],
      ["stockType", ["FedexWebServices::Soap::Close::ShippingDocumentStockType", XSD::QName.new(NsV5, "StockType")], [0, 1]],
      ["provideInstructions", ["SOAP::SOAPBoolean", XSD::QName.new(NsV5, "ProvideInstructions")], [0, 1]],
      ["localization", ["FedexWebServices::Soap::Close::Localization", XSD::QName.new(NsV5, "Localization")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseDocumentSpecification,
    :schema_type => XSD::QName.new(NsV5, "CloseDocumentSpecification"),
    :schema_element => [
      ["closeDocumentTypes", ["FedexWebServices::Soap::Close::CloseDocumentType[]", XSD::QName.new(NsV5, "CloseDocumentTypes")], [0, nil]],
      ["detailedDeliveryManifestDetail", ["FedexWebServices::Soap::Close::DetailedDeliveryManifestDetail", XSD::QName.new(NsV5, "DetailedDeliveryManifestDetail")], [0, 1]],
      ["hazardousMaterialsCertificationDetail", ["FedexWebServices::Soap::Close::HazardousMaterialsCertificationDetail", XSD::QName.new(NsV5, "HazardousMaterialsCertificationDetail")], [0, 1]],
      ["manifestDetail", ["FedexWebServices::Soap::Close::ManifestDetail", XSD::QName.new(NsV5, "ManifestDetail")], [0, 1]],
      ["op950Detail", ["FedexWebServices::Soap::Close::Op950Detail", XSD::QName.new(NsV5, "Op950Detail")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseManifestReferenceDetail,
    :schema_type => XSD::QName.new(NsV5, "CloseManifestReferenceDetail"),
    :schema_element => [
      ["type", ["FedexWebServices::Soap::Close::CustomerReferenceType", XSD::QName.new(NsV5, "Type")], [0, 1]],
      ["value", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Value")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseSmartPostDetail,
    :schema_type => XSD::QName.new(NsV5, "CloseSmartPostDetail"),
    :schema_element => [
      ["hubId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "HubId")], [0, 1]],
      ["customerId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerId")], [0, 1]],
      ["customerManifestId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerManifestId")], [0, 1]],
      ["destinationCountryCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "DestinationCountryCode")], [0, 1]],
      ["pickupCarrier", ["FedexWebServices::Soap::Close::CarrierCodeType", XSD::QName.new(NsV5, "PickupCarrier")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionsRequested,
    :schema_type => XSD::QName.new(NsV5, "CloseWithDocumentsProcessingOptionsRequested"),
    :schema_element => [
      ["options", ["FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionType[]", XSD::QName.new(NsV5, "Options")], [0, nil]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsReply,
    :schema_type => XSD::QName.new(NsV5, "CloseWithDocumentsReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["documents", ["FedexWebServices::Soap::Close::CloseDocument[]", XSD::QName.new(NsV5, "Documents")], [0, nil]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsRequest,
    :schema_type => XSD::QName.new(NsV5, "CloseWithDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["actionType", ["FedexWebServices::Soap::Close::CloseActionType", XSD::QName.new(NsV5, "ActionType")], [0, 1]],
      ["processingOptions", ["FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionsRequested", XSD::QName.new(NsV5, "ProcessingOptions")], [0, 1]],
      ["carrierCode", ["FedexWebServices::Soap::Close::CarrierCodeType", XSD::QName.new(NsV5, "CarrierCode")], [0, 1]],
      ["shippingCycle", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ShippingCycle")], [0, 1]],
      ["reprintCloseDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV5, "ReprintCloseDate")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]],
      ["smartPostDetail", ["FedexWebServices::Soap::Close::CloseSmartPostDetail", XSD::QName.new(NsV5, "SmartPostDetail")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CustomerImageUsage,
    :schema_type => XSD::QName.new(NsV5, "CustomerImageUsage"),
    :schema_element => [
      ["type", ["FedexWebServices::Soap::Close::CustomerImageUsageType", XSD::QName.new(NsV5, "Type")], [0, 1]],
      ["id", ["FedexWebServices::Soap::Close::ImageId", XSD::QName.new(NsV5, "Id")], [0, 1]],
      ["internalId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "InternalId")], [0, 1]],
      ["internalImageType", ["FedexWebServices::Soap::Close::InternalImageType", XSD::QName.new(NsV5, "InternalImageType")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::DetailedDeliveryManifestDetail,
    :schema_type => XSD::QName.new(NsV5, "DetailedDeliveryManifestDetail"),
    :schema_element => [
      ["format", ["FedexWebServices::Soap::Close::CloseDocumentFormat", XSD::QName.new(NsV5, "Format")], [0, 1]],
      ["clientTimeZoneOffset", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ClientTimeZoneOffset")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseDocumentsReply,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseDocumentsReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeDocuments", ["FedexWebServices::Soap::Close::CloseDocument[]", XSD::QName.new(NsV5, "CloseDocuments")], [0, nil]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReply,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["codReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "CodReport")], [0, 1]],
      ["hazMatCertificate", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "HazMatCertificate")], [0, 1]],
      ["manifest", ["FedexWebServices::Soap::Close::ManifestFile", XSD::QName.new(NsV5, "Manifest")], [0, 1]],
      ["multiweightReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "MultiweightReport")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReportsReprintReply,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseReportsReprintReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["codReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "CodReport")], [0, 1]],
      ["hazMatCertificate", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "HazMatCertificate")], [0, 1]],
      ["manifests", ["FedexWebServices::Soap::Close::ManifestFile[]", XSD::QName.new(NsV5, "Manifests")], [0, nil]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReportsReprintRequest,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseReportsReprintRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["reportDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "ReportDate")], [0, 1]],
      ["trackingNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "TrackingNumber")], [0, 1]],
      ["closeReportType", ["FedexWebServices::Soap::Close::CloseReportType", XSD::QName.new(NsV5, "CloseReportType")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseRequest,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeGrouping", ["FedexWebServices::Soap::Close::CloseGroupingType", XSD::QName.new(NsV5, "CloseGrouping")], [0, 1]],
      ["timeUpToWhichShipmentsAreToBeClosed", ["SOAP::SOAPDateTime", XSD::QName.new(NsV5, "TimeUpToWhichShipmentsAreToBeClosed")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseWithDocumentsRequest,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseWithDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "CloseDate")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::HazardousMaterialsCertificationDetail,
    :schema_type => XSD::QName.new(NsV5, "HazardousMaterialsCertificationDetail"),
    :schema_element => [
      ["format", ["FedexWebServices::Soap::Close::CloseDocumentFormat", XSD::QName.new(NsV5, "Format")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::LinearMeasure,
    :schema_type => XSD::QName.new(NsV5, "LinearMeasure"),
    :schema_element => [
      ["value", ["SOAP::SOAPDecimal", XSD::QName.new(NsV5, "Value")], [0, 1]],
      ["units", ["FedexWebServices::Soap::Close::LinearUnits", XSD::QName.new(NsV5, "Units")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::Localization,
    :schema_type => XSD::QName.new(NsV5, "Localization"),
    :schema_element => [
      ["languageCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "LanguageCode")]],
      ["localeCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "LocaleCode")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ManifestDetail,
    :schema_type => XSD::QName.new(NsV5, "ManifestDetail"),
    :schema_element => [
      ["format", ["FedexWebServices::Soap::Close::CloseDocumentFormat", XSD::QName.new(NsV5, "Format")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ManifestFile,
    :schema_type => XSD::QName.new(NsV5, "ManifestFile"),
    :schema_element => [
      ["fileName", ["SOAP::SOAPString", XSD::QName.new(NsV5, "FileName")], [0, 1]],
      ["file", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "File")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::Notification,
    :schema_type => XSD::QName.new(NsV5, "Notification"),
    :schema_element => [
      ["severity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "Severity")], [0, 1]],
      ["source", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Source")], [0, 1]],
      ["code", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Code")], [0, 1]],
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Message")], [0, 1]],
      ["localizedMessage", ["SOAP::SOAPString", XSD::QName.new(NsV5, "LocalizedMessage")], [0, 1]],
      ["messageParameters", ["FedexWebServices::Soap::Close::NotificationParameter[]", XSD::QName.new(NsV5, "MessageParameters")], [0, nil]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::NotificationParameter,
    :schema_type => XSD::QName.new(NsV5, "NotificationParameter"),
    :schema_element => [
      ["id", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Id")], [0, 1]],
      ["value", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Value")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::Op950Detail,
    :schema_type => XSD::QName.new(NsV5, "Op950Detail"),
    :schema_element => [
      ["format", ["FedexWebServices::Soap::Close::CloseDocumentFormat", XSD::QName.new(NsV5, "Format")], [0, 1]],
      ["customerImageUsages", ["FedexWebServices::Soap::Close::CustomerImageUsage[]", XSD::QName.new(NsV5, "CustomerImageUsages")], [0, nil]],
      ["signatureName", ["SOAP::SOAPString", XSD::QName.new(NsV5, "SignatureName")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ReprintGroundCloseDocumentsRequest,
    :schema_type => XSD::QName.new(NsV5, "ReprintGroundCloseDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["reprintOption", ["FedexWebServices::Soap::Close::ReprintGroundCloseDocumentsOptionType", XSD::QName.new(NsV5, "ReprintOption")], [0, 1]],
      ["closeDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "CloseDate")], [0, 1]],
      ["trackingNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "TrackingNumber")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentDispositionDetail,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentDispositionDetail"),
    :schema_element => [
      ["dispositionType", ["FedexWebServices::Soap::Close::ShippingDocumentDispositionType", XSD::QName.new(NsV5, "DispositionType")], [0, 1]],
      ["grouping", ["FedexWebServices::Soap::Close::ShippingDocumentGroupingType", XSD::QName.new(NsV5, "Grouping")], [0, 1]],
      ["storageDetail", ["FedexWebServices::Soap::Close::ShippingDocumentStorageDetail", XSD::QName.new(NsV5, "StorageDetail")], [0, 1]],
      ["eMailDetail", ["FedexWebServices::Soap::Close::ShippingDocumentEMailDetail", XSD::QName.new(NsV5, "EMailDetail")], [0, 1]],
      ["printDetail", ["FedexWebServices::Soap::Close::ShippingDocumentPrintDetail", XSD::QName.new(NsV5, "PrintDetail")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentEMailDetail,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentEMailDetail"),
    :schema_element => [
      ["eMailRecipients", ["FedexWebServices::Soap::Close::ShippingDocumentEMailRecipient[]", XSD::QName.new(NsV5, "EMailRecipients")], [0, nil]],
      ["grouping", ["FedexWebServices::Soap::Close::ShippingDocumentEMailGroupingType", XSD::QName.new(NsV5, "Grouping")], [0, 1]],
      ["localization", ["FedexWebServices::Soap::Close::Localization", XSD::QName.new(NsV5, "Localization")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentEMailRecipient,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentEMailRecipient"),
    :schema_element => [
      ["recipientType", ["FedexWebServices::Soap::Close::EMailNotificationRecipientType", XSD::QName.new(NsV5, "RecipientType")], [0, 1]],
      ["address", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Address")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentPart,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentPart"),
    :schema_element => [
      ["documentPartSequenceNumber", ["SOAP::SOAPPositiveInteger", XSD::QName.new(NsV5, "DocumentPartSequenceNumber")], [0, 1]],
      ["image", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "Image")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentPrintDetail,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentPrintDetail"),
    :schema_element => [
      ["printerId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "PrinterId")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentStorageDetail,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentStorageDetail"),
    :schema_element => [
      ["filePath", ["SOAP::SOAPString", XSD::QName.new(NsV5, "FilePath")], [0, 1]],
      ["fileNaming", ["FedexWebServices::Soap::Close::ShippingDocumentNamingType", XSD::QName.new(NsV5, "FileNaming")], [0, 1]],
      ["fileSuffix", ["SOAP::SOAPString", XSD::QName.new(NsV5, "FileSuffix")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::SmartPostCloseReply,
    :schema_type => XSD::QName.new(NsV5, "SmartPostCloseReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::SmartPostCloseRequest,
    :schema_type => XSD::QName.new(NsV5, "SmartPostCloseRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["hubId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "HubId")], [0, 1]],
      ["customerManifestId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerManifestId")], [0, 1]],
      ["destinationCountryCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "DestinationCountryCode")], [0, 1]],
      ["pickUpCarrier", ["FedexWebServices::Soap::Close::CarrierCodeType", XSD::QName.new(NsV5, "PickUpCarrier")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::TransactionDetail,
    :schema_type => XSD::QName.new(NsV5, "TransactionDetail"),
    :schema_element => [
      ["customerTransactionId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerTransactionId")], [0, 1]],
      ["localization", ["FedexWebServices::Soap::Close::Localization", XSD::QName.new(NsV5, "Localization")], [0, 1]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::WebAuthenticationDetail,
    :schema_type => XSD::QName.new(NsV5, "WebAuthenticationDetail"),
    :schema_element => [
      ["parentCredential", ["FedexWebServices::Soap::Close::WebAuthenticationCredential", XSD::QName.new(NsV5, "ParentCredential")], [0, 1]],
      ["userCredential", ["FedexWebServices::Soap::Close::WebAuthenticationCredential", XSD::QName.new(NsV5, "UserCredential")]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::WebAuthenticationCredential,
    :schema_type => XSD::QName.new(NsV5, "WebAuthenticationCredential"),
    :schema_element => [
      ["key", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Key")]],
      ["password", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Password")]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::VersionId,
    :schema_type => XSD::QName.new(NsV5, "VersionId"),
    :schema_element => [
      ["serviceId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ServiceId")]],
      ["major", ["SOAP::SOAPInt", XSD::QName.new(NsV5, "Major")]],
      ["intermediate", ["SOAP::SOAPInt", XSD::QName.new(NsV5, "Intermediate")]],
      ["minor", ["SOAP::SOAPInt", XSD::QName.new(NsV5, "Minor")]]
    ]
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CarrierCodeType,
    :schema_type => XSD::QName.new(NsV5, "CarrierCodeType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseActionType,
    :schema_type => XSD::QName.new(NsV5, "CloseActionType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseDocumentType,
    :schema_type => XSD::QName.new(NsV5, "CloseDocumentType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseGroupingType,
    :schema_type => XSD::QName.new(NsV5, "CloseGroupingType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseReportType,
    :schema_type => XSD::QName.new(NsV5, "CloseReportType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionType,
    :schema_type => XSD::QName.new(NsV5, "CloseWithDocumentsProcessingOptionType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CustomerImageUsageType,
    :schema_type => XSD::QName.new(NsV5, "CustomerImageUsageType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::CustomerReferenceType,
    :schema_type => XSD::QName.new(NsV5, "CustomerReferenceType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::EMailNotificationRecipientType,
    :schema_type => XSD::QName.new(NsV5, "EMailNotificationRecipientType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ImageId,
    :schema_type => XSD::QName.new(NsV5, "ImageId")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::InternalImageType,
    :schema_type => XSD::QName.new(NsV5, "InternalImageType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::LinearUnits,
    :schema_type => XSD::QName.new(NsV5, "LinearUnits")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::NotificationSeverityType,
    :schema_type => XSD::QName.new(NsV5, "NotificationSeverityType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ReprintGroundCloseDocumentsOptionType,
    :schema_type => XSD::QName.new(NsV5, "ReprintGroundCloseDocumentsOptionType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentDispositionType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentDispositionType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentEMailGroupingType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentEMailGroupingType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentGroupingType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentGroupingType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentImageType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentImageType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentNamingType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentNamingType")
  )

  EncodedRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentStockType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentStockType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ClientDetail,
    :schema_type => XSD::QName.new(NsV5, "ClientDetail"),
    :schema_element => [
      ["accountNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "AccountNumber")]],
      ["meterNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "MeterNumber")]],
      ["integratorId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "IntegratorId")], [0, 1]],
      ["localization", ["FedexWebServices::Soap::Close::Localization", XSD::QName.new(NsV5, "Localization")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseDocument,
    :schema_type => XSD::QName.new(NsV5, "CloseDocument"),
    :schema_element => [
      ["type", ["FedexWebServices::Soap::Close::CloseDocumentType", XSD::QName.new(NsV5, "Type")], [0, 1]],
      ["shippingCycle", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ShippingCycle")], [0, 1]],
      ["shippingDocumentDisposition", ["FedexWebServices::Soap::Close::ShippingDocumentDispositionType", XSD::QName.new(NsV5, "ShippingDocumentDisposition")], [0, 1]],
      ["accessReference", ["SOAP::SOAPString", XSD::QName.new(NsV5, "AccessReference")], [0, 1]],
      ["resolution", ["SOAP::SOAPNonNegativeInteger", XSD::QName.new(NsV5, "Resolution")], [0, 1]],
      ["copiesToPrint", ["SOAP::SOAPNonNegativeInteger", XSD::QName.new(NsV5, "CopiesToPrint")], [0, 1]],
      ["parts", ["FedexWebServices::Soap::Close::ShippingDocumentPart[]", XSD::QName.new(NsV5, "Parts")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseDocumentFormat,
    :schema_type => XSD::QName.new(NsV5, "CloseDocumentFormat"),
    :schema_element => [
      ["dispositions", ["FedexWebServices::Soap::Close::ShippingDocumentDispositionDetail[]", XSD::QName.new(NsV5, "Dispositions")], [0, nil]],
      ["topOfPageOffset", ["FedexWebServices::Soap::Close::LinearMeasure", XSD::QName.new(NsV5, "TopOfPageOffset")], [0, 1]],
      ["imageType", ["FedexWebServices::Soap::Close::ShippingDocumentImageType", XSD::QName.new(NsV5, "ImageType")], [0, 1]],
      ["stockType", ["FedexWebServices::Soap::Close::ShippingDocumentStockType", XSD::QName.new(NsV5, "StockType")], [0, 1]],
      ["provideInstructions", ["SOAP::SOAPBoolean", XSD::QName.new(NsV5, "ProvideInstructions")], [0, 1]],
      ["localization", ["FedexWebServices::Soap::Close::Localization", XSD::QName.new(NsV5, "Localization")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseDocumentSpecification,
    :schema_type => XSD::QName.new(NsV5, "CloseDocumentSpecification"),
    :schema_element => [
      ["closeDocumentTypes", ["FedexWebServices::Soap::Close::CloseDocumentType[]", XSD::QName.new(NsV5, "CloseDocumentTypes")], [0, nil]],
      ["detailedDeliveryManifestDetail", ["FedexWebServices::Soap::Close::DetailedDeliveryManifestDetail", XSD::QName.new(NsV5, "DetailedDeliveryManifestDetail")], [0, 1]],
      ["hazardousMaterialsCertificationDetail", ["FedexWebServices::Soap::Close::HazardousMaterialsCertificationDetail", XSD::QName.new(NsV5, "HazardousMaterialsCertificationDetail")], [0, 1]],
      ["manifestDetail", ["FedexWebServices::Soap::Close::ManifestDetail", XSD::QName.new(NsV5, "ManifestDetail")], [0, 1]],
      ["op950Detail", ["FedexWebServices::Soap::Close::Op950Detail", XSD::QName.new(NsV5, "Op950Detail")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseManifestReferenceDetail,
    :schema_type => XSD::QName.new(NsV5, "CloseManifestReferenceDetail"),
    :schema_element => [
      ["type", ["FedexWebServices::Soap::Close::CustomerReferenceType", XSD::QName.new(NsV5, "Type")], [0, 1]],
      ["value", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Value")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseSmartPostDetail,
    :schema_type => XSD::QName.new(NsV5, "CloseSmartPostDetail"),
    :schema_element => [
      ["hubId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "HubId")], [0, 1]],
      ["customerId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerId")], [0, 1]],
      ["customerManifestId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerManifestId")], [0, 1]],
      ["destinationCountryCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "DestinationCountryCode")], [0, 1]],
      ["pickupCarrier", ["FedexWebServices::Soap::Close::CarrierCodeType", XSD::QName.new(NsV5, "PickupCarrier")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionsRequested,
    :schema_type => XSD::QName.new(NsV5, "CloseWithDocumentsProcessingOptionsRequested"),
    :schema_element => [
      ["options", ["FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionType[]", XSD::QName.new(NsV5, "Options")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsReply,
    :schema_type => XSD::QName.new(NsV5, "CloseWithDocumentsReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["documents", ["FedexWebServices::Soap::Close::CloseDocument[]", XSD::QName.new(NsV5, "Documents")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsRequest,
    :schema_type => XSD::QName.new(NsV5, "CloseWithDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["actionType", ["FedexWebServices::Soap::Close::CloseActionType", XSD::QName.new(NsV5, "ActionType")], [0, 1]],
      ["processingOptions", ["FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionsRequested", XSD::QName.new(NsV5, "ProcessingOptions")], [0, 1]],
      ["carrierCode", ["FedexWebServices::Soap::Close::CarrierCodeType", XSD::QName.new(NsV5, "CarrierCode")], [0, 1]],
      ["shippingCycle", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ShippingCycle")], [0, 1]],
      ["reprintCloseDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV5, "ReprintCloseDate")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]],
      ["smartPostDetail", ["FedexWebServices::Soap::Close::CloseSmartPostDetail", XSD::QName.new(NsV5, "SmartPostDetail")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CustomerImageUsage,
    :schema_type => XSD::QName.new(NsV5, "CustomerImageUsage"),
    :schema_element => [
      ["type", ["FedexWebServices::Soap::Close::CustomerImageUsageType", XSD::QName.new(NsV5, "Type")], [0, 1]],
      ["id", ["FedexWebServices::Soap::Close::ImageId", XSD::QName.new(NsV5, "Id")], [0, 1]],
      ["internalId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "InternalId")], [0, 1]],
      ["internalImageType", ["FedexWebServices::Soap::Close::InternalImageType", XSD::QName.new(NsV5, "InternalImageType")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::DetailedDeliveryManifestDetail,
    :schema_type => XSD::QName.new(NsV5, "DetailedDeliveryManifestDetail"),
    :schema_element => [
      ["format", ["FedexWebServices::Soap::Close::CloseDocumentFormat", XSD::QName.new(NsV5, "Format")], [0, 1]],
      ["clientTimeZoneOffset", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ClientTimeZoneOffset")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseDocumentsReply,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseDocumentsReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeDocuments", ["FedexWebServices::Soap::Close::CloseDocument[]", XSD::QName.new(NsV5, "CloseDocuments")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReply,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["codReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "CodReport")], [0, 1]],
      ["hazMatCertificate", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "HazMatCertificate")], [0, 1]],
      ["manifest", ["FedexWebServices::Soap::Close::ManifestFile", XSD::QName.new(NsV5, "Manifest")], [0, 1]],
      ["multiweightReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "MultiweightReport")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReportsReprintReply,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseReportsReprintReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["codReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "CodReport")], [0, 1]],
      ["hazMatCertificate", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "HazMatCertificate")], [0, 1]],
      ["manifests", ["FedexWebServices::Soap::Close::ManifestFile[]", XSD::QName.new(NsV5, "Manifests")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReportsReprintRequest,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseReportsReprintRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["reportDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "ReportDate")], [0, 1]],
      ["trackingNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "TrackingNumber")], [0, 1]],
      ["closeReportType", ["FedexWebServices::Soap::Close::CloseReportType", XSD::QName.new(NsV5, "CloseReportType")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseRequest,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeGrouping", ["FedexWebServices::Soap::Close::CloseGroupingType", XSD::QName.new(NsV5, "CloseGrouping")], [0, 1]],
      ["timeUpToWhichShipmentsAreToBeClosed", ["SOAP::SOAPDateTime", XSD::QName.new(NsV5, "TimeUpToWhichShipmentsAreToBeClosed")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseWithDocumentsRequest,
    :schema_type => XSD::QName.new(NsV5, "GroundCloseWithDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "CloseDate")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::HazardousMaterialsCertificationDetail,
    :schema_type => XSD::QName.new(NsV5, "HazardousMaterialsCertificationDetail"),
    :schema_element => [
      ["format", ["FedexWebServices::Soap::Close::CloseDocumentFormat", XSD::QName.new(NsV5, "Format")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::LinearMeasure,
    :schema_type => XSD::QName.new(NsV5, "LinearMeasure"),
    :schema_element => [
      ["value", ["SOAP::SOAPDecimal", XSD::QName.new(NsV5, "Value")], [0, 1]],
      ["units", ["FedexWebServices::Soap::Close::LinearUnits", XSD::QName.new(NsV5, "Units")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::Localization,
    :schema_type => XSD::QName.new(NsV5, "Localization"),
    :schema_element => [
      ["languageCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "LanguageCode")]],
      ["localeCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "LocaleCode")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ManifestDetail,
    :schema_type => XSD::QName.new(NsV5, "ManifestDetail"),
    :schema_element => [
      ["format", ["FedexWebServices::Soap::Close::CloseDocumentFormat", XSD::QName.new(NsV5, "Format")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ManifestFile,
    :schema_type => XSD::QName.new(NsV5, "ManifestFile"),
    :schema_element => [
      ["fileName", ["SOAP::SOAPString", XSD::QName.new(NsV5, "FileName")], [0, 1]],
      ["file", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "File")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::Notification,
    :schema_type => XSD::QName.new(NsV5, "Notification"),
    :schema_element => [
      ["severity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "Severity")], [0, 1]],
      ["source", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Source")], [0, 1]],
      ["code", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Code")], [0, 1]],
      ["message", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Message")], [0, 1]],
      ["localizedMessage", ["SOAP::SOAPString", XSD::QName.new(NsV5, "LocalizedMessage")], [0, 1]],
      ["messageParameters", ["FedexWebServices::Soap::Close::NotificationParameter[]", XSD::QName.new(NsV5, "MessageParameters")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::NotificationParameter,
    :schema_type => XSD::QName.new(NsV5, "NotificationParameter"),
    :schema_element => [
      ["id", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Id")], [0, 1]],
      ["value", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Value")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::Op950Detail,
    :schema_type => XSD::QName.new(NsV5, "Op950Detail"),
    :schema_element => [
      ["format", ["FedexWebServices::Soap::Close::CloseDocumentFormat", XSD::QName.new(NsV5, "Format")], [0, 1]],
      ["customerImageUsages", ["FedexWebServices::Soap::Close::CustomerImageUsage[]", XSD::QName.new(NsV5, "CustomerImageUsages")], [0, nil]],
      ["signatureName", ["SOAP::SOAPString", XSD::QName.new(NsV5, "SignatureName")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ReprintGroundCloseDocumentsRequest,
    :schema_type => XSD::QName.new(NsV5, "ReprintGroundCloseDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["reprintOption", ["FedexWebServices::Soap::Close::ReprintGroundCloseDocumentsOptionType", XSD::QName.new(NsV5, "ReprintOption")], [0, 1]],
      ["closeDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "CloseDate")], [0, 1]],
      ["trackingNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "TrackingNumber")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentDispositionDetail,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentDispositionDetail"),
    :schema_element => [
      ["dispositionType", ["FedexWebServices::Soap::Close::ShippingDocumentDispositionType", XSD::QName.new(NsV5, "DispositionType")], [0, 1]],
      ["grouping", ["FedexWebServices::Soap::Close::ShippingDocumentGroupingType", XSD::QName.new(NsV5, "Grouping")], [0, 1]],
      ["storageDetail", ["FedexWebServices::Soap::Close::ShippingDocumentStorageDetail", XSD::QName.new(NsV5, "StorageDetail")], [0, 1]],
      ["eMailDetail", ["FedexWebServices::Soap::Close::ShippingDocumentEMailDetail", XSD::QName.new(NsV5, "EMailDetail")], [0, 1]],
      ["printDetail", ["FedexWebServices::Soap::Close::ShippingDocumentPrintDetail", XSD::QName.new(NsV5, "PrintDetail")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentEMailDetail,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentEMailDetail"),
    :schema_element => [
      ["eMailRecipients", ["FedexWebServices::Soap::Close::ShippingDocumentEMailRecipient[]", XSD::QName.new(NsV5, "EMailRecipients")], [0, nil]],
      ["grouping", ["FedexWebServices::Soap::Close::ShippingDocumentEMailGroupingType", XSD::QName.new(NsV5, "Grouping")], [0, 1]],
      ["localization", ["FedexWebServices::Soap::Close::Localization", XSD::QName.new(NsV5, "Localization")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentEMailRecipient,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentEMailRecipient"),
    :schema_element => [
      ["recipientType", ["FedexWebServices::Soap::Close::EMailNotificationRecipientType", XSD::QName.new(NsV5, "RecipientType")], [0, 1]],
      ["address", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Address")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentPart,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentPart"),
    :schema_element => [
      ["documentPartSequenceNumber", ["SOAP::SOAPPositiveInteger", XSD::QName.new(NsV5, "DocumentPartSequenceNumber")], [0, 1]],
      ["image", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "Image")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentPrintDetail,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentPrintDetail"),
    :schema_element => [
      ["printerId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "PrinterId")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentStorageDetail,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentStorageDetail"),
    :schema_element => [
      ["filePath", ["SOAP::SOAPString", XSD::QName.new(NsV5, "FilePath")], [0, 1]],
      ["fileNaming", ["FedexWebServices::Soap::Close::ShippingDocumentNamingType", XSD::QName.new(NsV5, "FileNaming")], [0, 1]],
      ["fileSuffix", ["SOAP::SOAPString", XSD::QName.new(NsV5, "FileSuffix")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::SmartPostCloseReply,
    :schema_type => XSD::QName.new(NsV5, "SmartPostCloseReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::SmartPostCloseRequest,
    :schema_type => XSD::QName.new(NsV5, "SmartPostCloseRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["hubId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "HubId")], [0, 1]],
      ["customerManifestId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerManifestId")], [0, 1]],
      ["destinationCountryCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "DestinationCountryCode")], [0, 1]],
      ["pickUpCarrier", ["FedexWebServices::Soap::Close::CarrierCodeType", XSD::QName.new(NsV5, "PickUpCarrier")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::TransactionDetail,
    :schema_type => XSD::QName.new(NsV5, "TransactionDetail"),
    :schema_element => [
      ["customerTransactionId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerTransactionId")], [0, 1]],
      ["localization", ["FedexWebServices::Soap::Close::Localization", XSD::QName.new(NsV5, "Localization")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::WebAuthenticationDetail,
    :schema_type => XSD::QName.new(NsV5, "WebAuthenticationDetail"),
    :schema_element => [
      ["parentCredential", ["FedexWebServices::Soap::Close::WebAuthenticationCredential", XSD::QName.new(NsV5, "ParentCredential")], [0, 1]],
      ["userCredential", ["FedexWebServices::Soap::Close::WebAuthenticationCredential", XSD::QName.new(NsV5, "UserCredential")]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::WebAuthenticationCredential,
    :schema_type => XSD::QName.new(NsV5, "WebAuthenticationCredential"),
    :schema_element => [
      ["key", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Key")]],
      ["password", ["SOAP::SOAPString", XSD::QName.new(NsV5, "Password")]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::VersionId,
    :schema_type => XSD::QName.new(NsV5, "VersionId"),
    :schema_element => [
      ["serviceId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ServiceId")]],
      ["major", ["SOAP::SOAPInt", XSD::QName.new(NsV5, "Major")]],
      ["intermediate", ["SOAP::SOAPInt", XSD::QName.new(NsV5, "Intermediate")]],
      ["minor", ["SOAP::SOAPInt", XSD::QName.new(NsV5, "Minor")]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CarrierCodeType,
    :schema_type => XSD::QName.new(NsV5, "CarrierCodeType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseActionType,
    :schema_type => XSD::QName.new(NsV5, "CloseActionType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseDocumentType,
    :schema_type => XSD::QName.new(NsV5, "CloseDocumentType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseGroupingType,
    :schema_type => XSD::QName.new(NsV5, "CloseGroupingType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseReportType,
    :schema_type => XSD::QName.new(NsV5, "CloseReportType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionType,
    :schema_type => XSD::QName.new(NsV5, "CloseWithDocumentsProcessingOptionType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CustomerImageUsageType,
    :schema_type => XSD::QName.new(NsV5, "CustomerImageUsageType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CustomerReferenceType,
    :schema_type => XSD::QName.new(NsV5, "CustomerReferenceType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::EMailNotificationRecipientType,
    :schema_type => XSD::QName.new(NsV5, "EMailNotificationRecipientType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ImageId,
    :schema_type => XSD::QName.new(NsV5, "ImageId")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::InternalImageType,
    :schema_type => XSD::QName.new(NsV5, "InternalImageType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::LinearUnits,
    :schema_type => XSD::QName.new(NsV5, "LinearUnits")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::NotificationSeverityType,
    :schema_type => XSD::QName.new(NsV5, "NotificationSeverityType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ReprintGroundCloseDocumentsOptionType,
    :schema_type => XSD::QName.new(NsV5, "ReprintGroundCloseDocumentsOptionType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentDispositionType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentDispositionType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentEMailGroupingType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentEMailGroupingType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentGroupingType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentGroupingType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentImageType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentImageType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentNamingType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentNamingType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ShippingDocumentStockType,
    :schema_type => XSD::QName.new(NsV5, "ShippingDocumentStockType")
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsReply,
    :schema_name => XSD::QName.new(NsV5, "CloseWithDocumentsReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["documents", ["FedexWebServices::Soap::Close::CloseDocument[]", XSD::QName.new(NsV5, "Documents")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::CloseWithDocumentsRequest,
    :schema_name => XSD::QName.new(NsV5, "CloseWithDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["actionType", ["FedexWebServices::Soap::Close::CloseActionType", XSD::QName.new(NsV5, "ActionType")], [0, 1]],
      ["processingOptions", ["FedexWebServices::Soap::Close::CloseWithDocumentsProcessingOptionsRequested", XSD::QName.new(NsV5, "ProcessingOptions")], [0, 1]],
      ["carrierCode", ["FedexWebServices::Soap::Close::CarrierCodeType", XSD::QName.new(NsV5, "CarrierCode")], [0, 1]],
      ["shippingCycle", ["SOAP::SOAPString", XSD::QName.new(NsV5, "ShippingCycle")], [0, 1]],
      ["reprintCloseDate", ["SOAP::SOAPDateTime", XSD::QName.new(NsV5, "ReprintCloseDate")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]],
      ["smartPostDetail", ["FedexWebServices::Soap::Close::CloseSmartPostDetail", XSD::QName.new(NsV5, "SmartPostDetail")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseDocumentsReply,
    :schema_name => XSD::QName.new(NsV5, "GroundCloseDocumentsReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeDocuments", ["FedexWebServices::Soap::Close::CloseDocument[]", XSD::QName.new(NsV5, "CloseDocuments")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReply,
    :schema_name => XSD::QName.new(NsV5, "GroundCloseReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["codReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "CodReport")], [0, 1]],
      ["hazMatCertificate", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "HazMatCertificate")], [0, 1]],
      ["manifest", ["FedexWebServices::Soap::Close::ManifestFile", XSD::QName.new(NsV5, "Manifest")], [0, 1]],
      ["multiweightReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "MultiweightReport")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReportsReprintReply,
    :schema_name => XSD::QName.new(NsV5, "GroundCloseReportsReprintReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["codReport", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "CodReport")], [0, 1]],
      ["hazMatCertificate", ["SOAP::SOAPBase64", XSD::QName.new(NsV5, "HazMatCertificate")], [0, 1]],
      ["manifests", ["FedexWebServices::Soap::Close::ManifestFile[]", XSD::QName.new(NsV5, "Manifests")], [0, nil]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseReportsReprintRequest,
    :schema_name => XSD::QName.new(NsV5, "GroundCloseReportsReprintRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["reportDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "ReportDate")], [0, 1]],
      ["trackingNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "TrackingNumber")], [0, 1]],
      ["closeReportType", ["FedexWebServices::Soap::Close::CloseReportType", XSD::QName.new(NsV5, "CloseReportType")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseRequest,
    :schema_name => XSD::QName.new(NsV5, "GroundCloseRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeGrouping", ["FedexWebServices::Soap::Close::CloseGroupingType", XSD::QName.new(NsV5, "CloseGrouping")], [0, 1]],
      ["timeUpToWhichShipmentsAreToBeClosed", ["SOAP::SOAPDateTime", XSD::QName.new(NsV5, "TimeUpToWhichShipmentsAreToBeClosed")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::GroundCloseWithDocumentsRequest,
    :schema_name => XSD::QName.new(NsV5, "GroundCloseWithDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["closeDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "CloseDate")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::ReprintGroundCloseDocumentsRequest,
    :schema_name => XSD::QName.new(NsV5, "ReprintGroundCloseDocumentsRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["reprintOption", ["FedexWebServices::Soap::Close::ReprintGroundCloseDocumentsOptionType", XSD::QName.new(NsV5, "ReprintOption")], [0, 1]],
      ["closeDate", ["SOAP::SOAPDate", XSD::QName.new(NsV5, "CloseDate")], [0, 1]],
      ["trackingNumber", ["SOAP::SOAPString", XSD::QName.new(NsV5, "TrackingNumber")], [0, 1]],
      ["closeDocumentSpecification", ["FedexWebServices::Soap::Close::CloseDocumentSpecification", XSD::QName.new(NsV5, "CloseDocumentSpecification")], [0, 1]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::SmartPostCloseReply,
    :schema_name => XSD::QName.new(NsV5, "SmartPostCloseReply"),
    :schema_element => [
      ["highestSeverity", ["FedexWebServices::Soap::Close::NotificationSeverityType", XSD::QName.new(NsV5, "HighestSeverity")]],
      ["notifications", ["FedexWebServices::Soap::Close::Notification[]", XSD::QName.new(NsV5, "Notifications")], [1, nil]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]]
    ]
  )

  LiteralRegistry.register(
    :class => FedexWebServices::Soap::Close::SmartPostCloseRequest,
    :schema_name => XSD::QName.new(NsV5, "SmartPostCloseRequest"),
    :schema_element => [
      ["webAuthenticationDetail", ["FedexWebServices::Soap::Close::WebAuthenticationDetail", XSD::QName.new(NsV5, "WebAuthenticationDetail")]],
      ["clientDetail", ["FedexWebServices::Soap::Close::ClientDetail", XSD::QName.new(NsV5, "ClientDetail")]],
      ["transactionDetail", ["FedexWebServices::Soap::Close::TransactionDetail", XSD::QName.new(NsV5, "TransactionDetail")], [0, 1]],
      ["version", ["FedexWebServices::Soap::Close::VersionId", XSD::QName.new(NsV5, "Version")]],
      ["hubId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "HubId")], [0, 1]],
      ["customerManifestId", ["SOAP::SOAPString", XSD::QName.new(NsV5, "CustomerManifestId")], [0, 1]],
      ["destinationCountryCode", ["SOAP::SOAPString", XSD::QName.new(NsV5, "DestinationCountryCode")], [0, 1]],
      ["pickUpCarrier", ["FedexWebServices::Soap::Close::CarrierCodeType", XSD::QName.new(NsV5, "PickUpCarrier")], [0, 1]],
      ["manifestReferenceDetail", ["FedexWebServices::Soap::Close::CloseManifestReferenceDetail", XSD::QName.new(NsV5, "ManifestReferenceDetail")], [0, 1]]
    ]
  )
end

end; end; end
