# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require_relative 'LocationsServiceDefinitions.rb'
require_relative 'LocationsServiceDefinitionsMappingRegistry.rb'
require 'soap/rpc/driver'

module FedexWebServices::Soap::Locations

class LocationsPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://wsbeta.fedex.com:443/web-services/locs"

  Methods = [
    [ "http://fedex.com/ws/locs/v12/searchLocations",
      "searchLocations",
      [ [:in, "SearchLocationsRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/locs/v12", "SearchLocationsRequest"]],
        [:out, "SearchLocationsReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/locs/v12", "SearchLocationsReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = LocationsServiceDefinitionsMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = LocationsServiceDefinitionsMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
