# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require_relative 'PickupServiceDefinitions.rb'
require_relative 'PickupServiceDefinitionsMappingRegistry.rb'
require 'soap/rpc/driver'

module FedexWebServices::Soap::Pickup

class PickupPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://wsbeta.fedex.com:443/web-services/pickup"

  Methods = [
    [ "http://fedex.com/ws/pickup/v22/getPickupAvailability",
      "getPickupAvailability",
      [ [:in, "PickupAvailabilityRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/pickup/v22", "PickupAvailabilityRequest"]],
        [:out, "PickupAvailabilityReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/pickup/v22", "PickupAvailabilityReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://fedex.com/ws/pickup/v22/createPickup",
      "createPickup",
      [ [:in, "CreatePickupRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/pickup/v22", "CreatePickupRequest"]],
        [:out, "CreatePickupReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/pickup/v22", "CreatePickupReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://fedex.com/ws/pickup/v22/cancelPickup",
      "cancelPickup",
      [ [:in, "CancelPickupRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/pickup/v22", "CancelPickupRequest"]],
        [:out, "CancelPickupReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/pickup/v22", "CancelPickupReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = PickupServiceDefinitionsMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = PickupServiceDefinitionsMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
