# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require 'xsd/qname'

module FedexWebServices; module Soap; module Pickup


# {http://fedex.com/ws/pickup/v22}Address
#   streetLines - SOAP::SOAPString
#   city - SOAP::SOAPString
#   stateOrProvinceCode - SOAP::SOAPString
#   postalCode - SOAP::SOAPString
#   urbanizationCode - SOAP::SOAPString
#   countryCode - SOAP::SOAPString
#   countryName - SOAP::SOAPString
#   residential - SOAP::SOAPBoolean
#   geographicCoordinates - SOAP::SOAPString
class Address
  attr_accessor :streetLines
  attr_accessor :city
  attr_accessor :stateOrProvinceCode
  attr_accessor :postalCode
  attr_accessor :urbanizationCode
  attr_accessor :countryCode
  attr_accessor :countryName
  attr_accessor :residential
  attr_accessor :geographicCoordinates

  def initialize(streetLines = [], city = nil, stateOrProvinceCode = nil, postalCode = nil, urbanizationCode = nil, countryCode = nil, countryName = nil, residential = nil, geographicCoordinates = nil)
    @streetLines = streetLines
    @city = city
    @stateOrProvinceCode = stateOrProvinceCode
    @postalCode = postalCode
    @urbanizationCode = urbanizationCode
    @countryCode = countryCode
    @countryName = countryName
    @residential = residential
    @geographicCoordinates = geographicCoordinates
  end
end

# {http://fedex.com/ws/pickup/v22}AssociatedAccount
#   type - FedexWebServices::Soap::Pickup::AssociatedAccountNumberType
#   accountNumber - SOAP::SOAPString
class AssociatedAccount
  attr_accessor :type
  attr_accessor :accountNumber

  def initialize(type = nil, accountNumber = nil)
    @type = type
    @accountNumber = accountNumber
  end
end

# {http://fedex.com/ws/pickup/v22}CancelPickupReply
#   highestSeverity - FedexWebServices::Soap::Pickup::NotificationSeverityType
#   notifications - FedexWebServices::Soap::Pickup::Notification
#   transactionDetail - FedexWebServices::Soap::Pickup::TransactionDetail
#   version - FedexWebServices::Soap::Pickup::VersionId
#   message - SOAP::SOAPString
class CancelPickupReply
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :message

  def initialize(highestSeverity = nil, notifications = [], transactionDetail = nil, version = nil, message = nil)
    @highestSeverity = highestSeverity
    @notifications = notifications
    @transactionDetail = transactionDetail
    @version = version
    @message = message
  end
end

# {http://fedex.com/ws/pickup/v22}CancelPickupRequest
#   webAuthenticationDetail - FedexWebServices::Soap::Pickup::WebAuthenticationDetail
#   clientDetail - FedexWebServices::Soap::Pickup::ClientDetail
#   transactionDetail - FedexWebServices::Soap::Pickup::TransactionDetail
#   version - FedexWebServices::Soap::Pickup::VersionId
#   carrierCode - FedexWebServices::Soap::Pickup::CarrierCodeType
#   pickupConfirmationNumber - SOAP::SOAPString
#   scheduledDate - SOAP::SOAPDate
#   endDate - SOAP::SOAPDate
#   location - SOAP::SOAPString
#   remarks - SOAP::SOAPString
#   shippingChargesPayment - FedexWebServices::Soap::Pickup::Payment
#   reason - SOAP::SOAPString
#   contactName - SOAP::SOAPString
#   phoneNumber - SOAP::SOAPString
#   phoneExtension - SOAP::SOAPString
class CancelPickupRequest
  attr_accessor :webAuthenticationDetail
  attr_accessor :clientDetail
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :carrierCode
  attr_accessor :pickupConfirmationNumber
  attr_accessor :scheduledDate
  attr_accessor :endDate
  attr_accessor :location
  attr_accessor :remarks
  attr_accessor :shippingChargesPayment
  attr_accessor :reason
  attr_accessor :contactName
  attr_accessor :phoneNumber
  attr_accessor :phoneExtension

  def initialize(webAuthenticationDetail = nil, clientDetail = nil, transactionDetail = nil, version = nil, carrierCode = nil, pickupConfirmationNumber = nil, scheduledDate = nil, endDate = nil, location = nil, remarks = nil, shippingChargesPayment = nil, reason = nil, contactName = nil, phoneNumber = nil, phoneExtension = nil)
    @webAuthenticationDetail = webAuthenticationDetail
    @clientDetail = clientDetail
    @transactionDetail = transactionDetail
    @version = version
    @carrierCode = carrierCode
    @pickupConfirmationNumber = pickupConfirmationNumber
    @scheduledDate = scheduledDate
    @endDate = endDate
    @location = location
    @remarks = remarks
    @shippingChargesPayment = shippingChargesPayment
    @reason = reason
    @contactName = contactName
    @phoneNumber = phoneNumber
    @phoneExtension = phoneExtension
  end
end

# {http://fedex.com/ws/pickup/v22}ClientDetail
#   accountNumber - SOAP::SOAPString
#   meterNumber - SOAP::SOAPString
#   meterInstance - SOAP::SOAPString
#   integratorId - SOAP::SOAPString
#   region - FedexWebServices::Soap::Pickup::ExpressRegionCode
#   localization - FedexWebServices::Soap::Pickup::Localization
class ClientDetail
  attr_accessor :accountNumber
  attr_accessor :meterNumber
  attr_accessor :meterInstance
  attr_accessor :integratorId
  attr_accessor :region
  attr_accessor :localization

  def initialize(accountNumber = nil, meterNumber = nil, meterInstance = nil, integratorId = nil, region = nil, localization = nil)
    @accountNumber = accountNumber
    @meterNumber = meterNumber
    @meterInstance = meterInstance
    @integratorId = integratorId
    @region = region
    @localization = localization
  end
end

# {http://fedex.com/ws/pickup/v22}CodAddTransportationChargesDetail
#   rateTypeBasis - FedexWebServices::Soap::Pickup::RateTypeBasisType
#   chargeBasis - FedexWebServices::Soap::Pickup::CodAddTransportationChargeBasisType
#   chargeBasisLevel - FedexWebServices::Soap::Pickup::ChargeBasisLevelType
#   rateLevelBasis - FedexWebServices::Soap::Pickup::RateLevelBasisType
class CodAddTransportationChargesDetail
  attr_accessor :rateTypeBasis
  attr_accessor :chargeBasis
  attr_accessor :chargeBasisLevel
  attr_accessor :rateLevelBasis

  def initialize(rateTypeBasis = nil, chargeBasis = nil, chargeBasisLevel = nil, rateLevelBasis = nil)
    @rateTypeBasis = rateTypeBasis
    @chargeBasis = chargeBasis
    @chargeBasisLevel = chargeBasisLevel
    @rateLevelBasis = rateLevelBasis
  end
end

# {http://fedex.com/ws/pickup/v22}CodDetail
#   codCollectionAmount - FedexWebServices::Soap::Pickup::Money
#   addTransportationChargesDetail - FedexWebServices::Soap::Pickup::CodAddTransportationChargesDetail
#   collectionType - FedexWebServices::Soap::Pickup::CodCollectionType
#   codRecipient - FedexWebServices::Soap::Pickup::Party
#   financialInstitutionContactAndAddress - FedexWebServices::Soap::Pickup::ContactAndAddress
#   remitToName - SOAP::SOAPString
#   referenceIndicator - FedexWebServices::Soap::Pickup::CodReturnReferenceIndicatorType
#   returnTrackingId - FedexWebServices::Soap::Pickup::TrackingId
class CodDetail
  attr_accessor :codCollectionAmount
  attr_accessor :addTransportationChargesDetail
  attr_accessor :collectionType
  attr_accessor :codRecipient
  attr_accessor :financialInstitutionContactAndAddress
  attr_accessor :remitToName
  attr_accessor :referenceIndicator
  attr_accessor :returnTrackingId

  def initialize(codCollectionAmount = nil, addTransportationChargesDetail = nil, collectionType = nil, codRecipient = nil, financialInstitutionContactAndAddress = nil, remitToName = nil, referenceIndicator = nil, returnTrackingId = nil)
    @codCollectionAmount = codCollectionAmount
    @addTransportationChargesDetail = addTransportationChargesDetail
    @collectionType = collectionType
    @codRecipient = codRecipient
    @financialInstitutionContactAndAddress = financialInstitutionContactAndAddress
    @remitToName = remitToName
    @referenceIndicator = referenceIndicator
    @returnTrackingId = returnTrackingId
  end
end

# {http://fedex.com/ws/pickup/v22}CompletedFreightPickupDetail
#   origin - FedexWebServices::Soap::Pickup::FreightServiceCenterDetail
#   lineItems - FedexWebServices::Soap::Pickup::CompletedFreightPickupLineItem
#   totalPieces - SOAP::SOAPNonNegativeInteger
#   totalWeight - FedexWebServices::Soap::Pickup::Weight
#   totalHandlingUnits - SOAP::SOAPNonNegativeInteger
#   status - FedexWebServices::Soap::Pickup::PickupEventType
class CompletedFreightPickupDetail
  attr_accessor :origin
  attr_accessor :lineItems
  attr_accessor :totalPieces
  attr_accessor :totalWeight
  attr_accessor :totalHandlingUnits
  attr_accessor :status

  def initialize(origin = nil, lineItems = [], totalPieces = nil, totalWeight = nil, totalHandlingUnits = nil, status = nil)
    @origin = origin
    @lineItems = lineItems
    @totalPieces = totalPieces
    @totalWeight = totalWeight
    @totalHandlingUnits = totalHandlingUnits
    @status = status
  end
end

# {http://fedex.com/ws/pickup/v22}CompletedFreightPickupLineItem
#   sequenceNumber - SOAP::SOAPInt
#   destination - FedexWebServices::Soap::Pickup::FreightServiceCenterDetail
#   totalTravelTime - SOAP::SOAPDuration
#   etaDeliveryTimestamp - SOAP::SOAPDateTime
class CompletedFreightPickupLineItem
  attr_accessor :sequenceNumber
  attr_accessor :destination
  attr_accessor :totalTravelTime
  attr_accessor :etaDeliveryTimestamp

  def initialize(sequenceNumber = nil, destination = nil, totalTravelTime = nil, etaDeliveryTimestamp = nil)
    @sequenceNumber = sequenceNumber
    @destination = destination
    @totalTravelTime = totalTravelTime
    @etaDeliveryTimestamp = etaDeliveryTimestamp
  end
end

# {http://fedex.com/ws/pickup/v22}Contact
#   contactId - SOAP::SOAPString
#   personName - SOAP::SOAPString
#   title - SOAP::SOAPString
#   companyName - SOAP::SOAPString
#   phoneNumber - SOAP::SOAPString
#   phoneExtension - SOAP::SOAPString
#   tollFreePhoneNumber - SOAP::SOAPString
#   pagerNumber - SOAP::SOAPString
#   faxNumber - SOAP::SOAPString
#   eMailAddress - SOAP::SOAPString
class Contact
  attr_accessor :contactId
  attr_accessor :personName
  attr_accessor :title
  attr_accessor :companyName
  attr_accessor :phoneNumber
  attr_accessor :phoneExtension
  attr_accessor :tollFreePhoneNumber
  attr_accessor :pagerNumber
  attr_accessor :faxNumber
  attr_accessor :eMailAddress

  def initialize(contactId = nil, personName = nil, title = nil, companyName = nil, phoneNumber = nil, phoneExtension = nil, tollFreePhoneNumber = nil, pagerNumber = nil, faxNumber = nil, eMailAddress = nil)
    @contactId = contactId
    @personName = personName
    @title = title
    @companyName = companyName
    @phoneNumber = phoneNumber
    @phoneExtension = phoneExtension
    @tollFreePhoneNumber = tollFreePhoneNumber
    @pagerNumber = pagerNumber
    @faxNumber = faxNumber
    @eMailAddress = eMailAddress
  end
end

# {http://fedex.com/ws/pickup/v22}ContactAndAddress
#   contact - FedexWebServices::Soap::Pickup::Contact
#   address - FedexWebServices::Soap::Pickup::Address
class ContactAndAddress
  attr_accessor :contact
  attr_accessor :address

  def initialize(contact = nil, address = nil)
    @contact = contact
    @address = address
  end
end

# {http://fedex.com/ws/pickup/v22}CreatePickupReply
#   highestSeverity - FedexWebServices::Soap::Pickup::NotificationSeverityType
#   notifications - FedexWebServices::Soap::Pickup::Notification
#   transactionDetail - FedexWebServices::Soap::Pickup::TransactionDetail
#   version - FedexWebServices::Soap::Pickup::VersionId
#   pickupConfirmationNumber - SOAP::SOAPString
#   location - SOAP::SOAPString
#   messageCode - SOAP::SOAPString
#   message - SOAP::SOAPString
#   pRPControlNumber - SOAP::SOAPString
#   lastAccessTime - SOAP::SOAPTime
#   completedFreightPickupDetail - FedexWebServices::Soap::Pickup::CompletedFreightPickupDetail
class CreatePickupReply
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :pickupConfirmationNumber
  attr_accessor :location
  attr_accessor :messageCode
  attr_accessor :message
  attr_accessor :pRPControlNumber
  attr_accessor :lastAccessTime
  attr_accessor :completedFreightPickupDetail

  def initialize(highestSeverity = nil, notifications = [], transactionDetail = nil, version = nil, pickupConfirmationNumber = nil, location = nil, messageCode = nil, message = nil, pRPControlNumber = nil, lastAccessTime = nil, completedFreightPickupDetail = nil)
    @highestSeverity = highestSeverity
    @notifications = notifications
    @transactionDetail = transactionDetail
    @version = version
    @pickupConfirmationNumber = pickupConfirmationNumber
    @location = location
    @messageCode = messageCode
    @message = message
    @pRPControlNumber = pRPControlNumber
    @lastAccessTime = lastAccessTime
    @completedFreightPickupDetail = completedFreightPickupDetail
  end
end

# {http://fedex.com/ws/pickup/v22}CreatePickupRequest
#   webAuthenticationDetail - FedexWebServices::Soap::Pickup::WebAuthenticationDetail
#   clientDetail - FedexWebServices::Soap::Pickup::ClientDetail
#   transactionDetail - FedexWebServices::Soap::Pickup::TransactionDetail
#   version - FedexWebServices::Soap::Pickup::VersionId
#   associatedAccountNumber - FedexWebServices::Soap::Pickup::AssociatedAccount
#   trackingNumber - SOAP::SOAPString
#   originDetail - FedexWebServices::Soap::Pickup::PickupOriginDetail
#   pickupServiceCategory - FedexWebServices::Soap::Pickup::PickupServiceCategoryType
#   freightPickupDetail - FedexWebServices::Soap::Pickup::FreightPickupDetail
#   expressFreightDetail - FedexWebServices::Soap::Pickup::ExpressFreightPickupDetail
#   packageCount - SOAP::SOAPPositiveInteger
#   totalWeight - FedexWebServices::Soap::Pickup::Weight
#   carrierCode - FedexWebServices::Soap::Pickup::CarrierCodeType
#   oversizePackageCount - SOAP::SOAPNonNegativeInteger
#   remarks - SOAP::SOAPString
#   commodityDescription - SOAP::SOAPString
#   countryRelationship - FedexWebServices::Soap::Pickup::CountryRelationshipType
class CreatePickupRequest
  attr_accessor :webAuthenticationDetail
  attr_accessor :clientDetail
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :associatedAccountNumber
  attr_accessor :trackingNumber
  attr_accessor :originDetail
  attr_accessor :pickupServiceCategory
  attr_accessor :freightPickupDetail
  attr_accessor :expressFreightDetail
  attr_accessor :packageCount
  attr_accessor :totalWeight
  attr_accessor :carrierCode
  attr_accessor :oversizePackageCount
  attr_accessor :remarks
  attr_accessor :commodityDescription
  attr_accessor :countryRelationship

  def initialize(webAuthenticationDetail = nil, clientDetail = nil, transactionDetail = nil, version = nil, associatedAccountNumber = nil, trackingNumber = nil, originDetail = nil, pickupServiceCategory = nil, freightPickupDetail = nil, expressFreightDetail = nil, packageCount = nil, totalWeight = nil, carrierCode = nil, oversizePackageCount = nil, remarks = nil, commodityDescription = nil, countryRelationship = nil)
    @webAuthenticationDetail = webAuthenticationDetail
    @clientDetail = clientDetail
    @transactionDetail = transactionDetail
    @version = version
    @associatedAccountNumber = associatedAccountNumber
    @trackingNumber = trackingNumber
    @originDetail = originDetail
    @pickupServiceCategory = pickupServiceCategory
    @freightPickupDetail = freightPickupDetail
    @expressFreightDetail = expressFreightDetail
    @packageCount = packageCount
    @totalWeight = totalWeight
    @carrierCode = carrierCode
    @oversizePackageCount = oversizePackageCount
    @remarks = remarks
    @commodityDescription = commodityDescription
    @countryRelationship = countryRelationship
  end
end

# {http://fedex.com/ws/pickup/v22}CustomDeliveryWindowDetail
#   type - FedexWebServices::Soap::Pickup::CustomDeliveryWindowType
#   requestTime - SOAP::SOAPTime
#   requestRange - FedexWebServices::Soap::Pickup::DateRange
#   requestDate - SOAP::SOAPDate
class CustomDeliveryWindowDetail
  attr_accessor :type
  attr_accessor :requestTime
  attr_accessor :requestRange
  attr_accessor :requestDate

  def initialize(type = nil, requestTime = nil, requestRange = nil, requestDate = nil)
    @type = type
    @requestTime = requestTime
    @requestRange = requestRange
    @requestDate = requestDate
  end
end

# {http://fedex.com/ws/pickup/v22}DateRange
#   begins - SOAP::SOAPDate
#   ends - SOAP::SOAPDate
class DateRange
  attr_accessor :begins
  attr_accessor :ends

  def initialize(begins = nil, ends = nil)
    @begins = begins
    @ends = ends
  end
end

# {http://fedex.com/ws/pickup/v22}DeliveryOnInvoiceAcceptanceDetail
#   recipient - FedexWebServices::Soap::Pickup::Party
#   trackingId - FedexWebServices::Soap::Pickup::TrackingId
class DeliveryOnInvoiceAcceptanceDetail
  attr_accessor :recipient
  attr_accessor :trackingId

  def initialize(recipient = nil, trackingId = nil)
    @recipient = recipient
    @trackingId = trackingId
  end
end

# {http://fedex.com/ws/pickup/v22}DetentionDetail
#   duration - SOAP::SOAPDuration
class DetentionDetail
  attr_accessor :duration

  def initialize(duration = nil)
    @duration = duration
  end
end

# {http://fedex.com/ws/pickup/v22}Dimensions
#   length - SOAP::SOAPNonNegativeInteger
#   width - SOAP::SOAPNonNegativeInteger
#   height - SOAP::SOAPNonNegativeInteger
#   units - FedexWebServices::Soap::Pickup::LinearUnits
class Dimensions
  attr_accessor :length
  attr_accessor :width
  attr_accessor :height
  attr_accessor :units

  def initialize(length = nil, width = nil, height = nil, units = nil)
    @length = length
    @width = width
    @height = height
    @units = units
  end
end

# {http://fedex.com/ws/pickup/v22}Distance
#   value - SOAP::SOAPDecimal
#   units - FedexWebServices::Soap::Pickup::DistanceUnits
class Distance
  attr_accessor :value
  attr_accessor :units

  def initialize(value = nil, units = nil)
    @value = value
    @units = units
  end
end

# {http://fedex.com/ws/pickup/v22}EMailDetail
#   emailAddress - SOAP::SOAPString
#   name - SOAP::SOAPString
class EMailDetail
  attr_accessor :emailAddress
  attr_accessor :name

  def initialize(emailAddress = nil, name = nil)
    @emailAddress = emailAddress
    @name = name
  end
end

# {http://fedex.com/ws/pickup/v22}EMailLabelDetail
#   message - SOAP::SOAPString
#   recipients - FedexWebServices::Soap::Pickup::EMailRecipient
class EMailLabelDetail
  attr_accessor :message
  attr_accessor :recipients

  def initialize(message = nil, recipients = [])
    @message = message
    @recipients = recipients
  end
end

# {http://fedex.com/ws/pickup/v22}EMailRecipient
#   emailAddress - SOAP::SOAPString
#   role - FedexWebServices::Soap::Pickup::AccessorRoleType
#   optionsRequested - FedexWebServices::Soap::Pickup::EmailOptionsRequested
#   localization - FedexWebServices::Soap::Pickup::Localization
class EMailRecipient
  attr_accessor :emailAddress
  attr_accessor :role
  attr_accessor :optionsRequested
  attr_accessor :localization

  def initialize(emailAddress = nil, role = nil, optionsRequested = nil, localization = nil)
    @emailAddress = emailAddress
    @role = role
    @optionsRequested = optionsRequested
    @localization = localization
  end
end

# {http://fedex.com/ws/pickup/v22}EmailOptionsRequested
class EmailOptionsRequested < ::Array
end

# {http://fedex.com/ws/pickup/v22}EtdDetail
#   confirmation - FedexWebServices::Soap::Pickup::EtdConfirmationType
#   attributes - FedexWebServices::Soap::Pickup::EtdAttributeType
#   requestedDocumentCopies - FedexWebServices::Soap::Pickup::RequestedShippingDocumentType
#   documents - FedexWebServices::Soap::Pickup::UploadDocumentDetail
#   documentReferences - FedexWebServices::Soap::Pickup::UploadDocumentReferenceDetail
class EtdDetail
  attr_accessor :confirmation
  attr_accessor :attributes
  attr_accessor :requestedDocumentCopies
  attr_accessor :documents
  attr_accessor :documentReferences

  def initialize(confirmation = nil, attributes = [], requestedDocumentCopies = [], documents = [], documentReferences = [])
    @confirmation = confirmation
    @attributes = attributes
    @requestedDocumentCopies = requestedDocumentCopies
    @documents = documents
    @documentReferences = documentReferences
  end
end

# {http://fedex.com/ws/pickup/v22}ExpressFreightPickupDetail
#   service - SOAP::SOAPString
#   bookingNumber - SOAP::SOAPString
#   dimensions - FedexWebServices::Soap::Pickup::Dimensions
#   truckType - FedexWebServices::Soap::Pickup::TruckType
#   trailerSize - FedexWebServices::Soap::Pickup::TrailerSizeType
class ExpressFreightPickupDetail
  attr_accessor :service
  attr_accessor :bookingNumber
  attr_accessor :dimensions
  attr_accessor :truckType
  attr_accessor :trailerSize

  def initialize(service = nil, bookingNumber = nil, dimensions = nil, truckType = nil, trailerSize = nil)
    @service = service
    @bookingNumber = bookingNumber
    @dimensions = dimensions
    @truckType = truckType
    @trailerSize = trailerSize
  end
end

# {http://fedex.com/ws/pickup/v22}ExtraLaborDetail
#   duration - SOAP::SOAPDuration
class ExtraLaborDetail
  attr_accessor :duration

  def initialize(duration = nil)
    @duration = duration
  end
end

# {http://fedex.com/ws/pickup/v22}FaxDetail
#   phoneNumber - SOAP::SOAPString
class FaxDetail
  attr_accessor :phoneNumber

  def initialize(phoneNumber = nil)
    @phoneNumber = phoneNumber
  end
end

# {http://fedex.com/ws/pickup/v22}FlatbedTrailerDetail
class FlatbedTrailerDetail < ::Array
end

# {http://fedex.com/ws/pickup/v22}FreightGuaranteeDetail
#   type - FedexWebServices::Soap::Pickup::FreightGuaranteeType
#   date - SOAP::SOAPDate
#   time - SOAP::SOAPTime
class FreightGuaranteeDetail
  attr_accessor :type
  attr_accessor :date
  attr_accessor :time

  def initialize(type = nil, date = nil, time = nil)
    @type = type
    @date = date
    @time = time
  end
end

# {http://fedex.com/ws/pickup/v22}FreightPickupDetail
#   approvedBy - FedexWebServices::Soap::Pickup::Contact
#   payment - FedexWebServices::Soap::Pickup::PaymentType
#   role - FedexWebServices::Soap::Pickup::FreightShipmentRoleType
#   alternateBilling - FedexWebServices::Soap::Pickup::Party
#   submittedBy - FedexWebServices::Soap::Pickup::Contact
#   lineItems - FedexWebServices::Soap::Pickup::FreightPickupLineItem
class FreightPickupDetail
  attr_accessor :approvedBy
  attr_accessor :payment
  attr_accessor :role
  attr_accessor :alternateBilling
  attr_accessor :submittedBy
  attr_accessor :lineItems

  def initialize(approvedBy = nil, payment = nil, role = nil, alternateBilling = nil, submittedBy = nil, lineItems = [])
    @approvedBy = approvedBy
    @payment = payment
    @role = role
    @alternateBilling = alternateBilling
    @submittedBy = submittedBy
    @lineItems = lineItems
  end
end

# {http://fedex.com/ws/pickup/v22}FreightPickupLineItem
#   trackingNumber - SOAP::SOAPString
#   service - SOAP::SOAPString
#   sequenceNumber - SOAP::SOAPNonNegativeInteger
#   destination - FedexWebServices::Soap::Pickup::Address
#   packaging - FedexWebServices::Soap::Pickup::PhysicalPackagingType
#   pieces - SOAP::SOAPInt
#   weight - FedexWebServices::Soap::Pickup::Weight
#   totalHandlingUnits - SOAP::SOAPInt
#   purchaseOrderNumber - SOAP::SOAPString
#   justOneMore - SOAP::SOAPBoolean
#   specialServicesRequested - FedexWebServices::Soap::Pickup::ShipmentSpecialServicesRequested
#   description - SOAP::SOAPString
class FreightPickupLineItem
  attr_accessor :trackingNumber
  attr_accessor :service
  attr_accessor :sequenceNumber
  attr_accessor :destination
  attr_accessor :packaging
  attr_accessor :pieces
  attr_accessor :weight
  attr_accessor :totalHandlingUnits
  attr_accessor :purchaseOrderNumber
  attr_accessor :justOneMore
  attr_accessor :specialServicesRequested
  attr_accessor :description

  def initialize(trackingNumber = nil, service = nil, sequenceNumber = nil, destination = nil, packaging = nil, pieces = nil, weight = nil, totalHandlingUnits = nil, purchaseOrderNumber = nil, justOneMore = nil, specialServicesRequested = nil, description = nil)
    @trackingNumber = trackingNumber
    @service = service
    @sequenceNumber = sequenceNumber
    @destination = destination
    @packaging = packaging
    @pieces = pieces
    @weight = weight
    @totalHandlingUnits = totalHandlingUnits
    @purchaseOrderNumber = purchaseOrderNumber
    @justOneMore = justOneMore
    @specialServicesRequested = specialServicesRequested
    @description = description
  end
end

# {http://fedex.com/ws/pickup/v22}FreightServiceCenterDetail
#   interlineCarrierCode - SOAP::SOAPString
#   interlineCarrierName - SOAP::SOAPString
#   additionalDays - SOAP::SOAPInt
#   localService - SOAP::SOAPString
#   localDistance - FedexWebServices::Soap::Pickup::Distance
#   localDuration - SOAP::SOAPDuration
#   localServiceScheduling - FedexWebServices::Soap::Pickup::FreightServiceSchedulingType
#   limitedServiceDays - FedexWebServices::Soap::Pickup::DayOfWeekType
#   gatewayLocationId - SOAP::SOAPString
#   location - SOAP::SOAPString
#   contactAndAddress - FedexWebServices::Soap::Pickup::ContactAndAddress
class FreightServiceCenterDetail
  attr_accessor :interlineCarrierCode
  attr_accessor :interlineCarrierName
  attr_accessor :additionalDays
  attr_accessor :localService
  attr_accessor :localDistance
  attr_accessor :localDuration
  attr_accessor :localServiceScheduling
  attr_accessor :limitedServiceDays
  attr_accessor :gatewayLocationId
  attr_accessor :location
  attr_accessor :contactAndAddress

  def initialize(interlineCarrierCode = nil, interlineCarrierName = nil, additionalDays = nil, localService = nil, localDistance = nil, localDuration = nil, localServiceScheduling = nil, limitedServiceDays = [], gatewayLocationId = nil, location = nil, contactAndAddress = nil)
    @interlineCarrierCode = interlineCarrierCode
    @interlineCarrierName = interlineCarrierName
    @additionalDays = additionalDays
    @localService = localService
    @localDistance = localDistance
    @localDuration = localDuration
    @localServiceScheduling = localServiceScheduling
    @limitedServiceDays = limitedServiceDays
    @gatewayLocationId = gatewayLocationId
    @location = location
    @contactAndAddress = contactAndAddress
  end
end

# {http://fedex.com/ws/pickup/v22}HoldAtLocationDetail
#   phoneNumber - SOAP::SOAPString
#   locationContactAndAddress - FedexWebServices::Soap::Pickup::ContactAndAddress
#   locationType - FedexWebServices::Soap::Pickup::FedExLocationType
#   locationId - SOAP::SOAPString
#   locationNumber - SOAP::SOAPInt
class HoldAtLocationDetail
  attr_accessor :phoneNumber
  attr_accessor :locationContactAndAddress
  attr_accessor :locationType
  attr_accessor :locationId
  attr_accessor :locationNumber

  def initialize(phoneNumber = nil, locationContactAndAddress = nil, locationType = nil, locationId = nil, locationNumber = nil)
    @phoneNumber = phoneNumber
    @locationContactAndAddress = locationContactAndAddress
    @locationType = locationType
    @locationId = locationId
    @locationNumber = locationNumber
  end
end

# {http://fedex.com/ws/pickup/v22}HomeDeliveryPremiumDetail
#   homeDeliveryPremiumType - FedexWebServices::Soap::Pickup::HomeDeliveryPremiumType
#   date - SOAP::SOAPDate
#   phoneNumber - SOAP::SOAPString
class HomeDeliveryPremiumDetail
  attr_accessor :homeDeliveryPremiumType
  attr_accessor :date
  attr_accessor :phoneNumber

  def initialize(homeDeliveryPremiumType = nil, date = nil, phoneNumber = nil)
    @homeDeliveryPremiumType = homeDeliveryPremiumType
    @date = date
    @phoneNumber = phoneNumber
  end
end

# {http://fedex.com/ws/pickup/v22}InternationalControlledExportDetail
#   type - FedexWebServices::Soap::Pickup::InternationalControlledExportType
#   foreignTradeZoneCode - SOAP::SOAPString
#   entryNumber - SOAP::SOAPString
#   licenseOrPermitNumber - SOAP::SOAPString
#   licenseOrPermitExpirationDate - SOAP::SOAPDate
class InternationalControlledExportDetail
  attr_accessor :type
  attr_accessor :foreignTradeZoneCode
  attr_accessor :entryNumber
  attr_accessor :licenseOrPermitNumber
  attr_accessor :licenseOrPermitExpirationDate

  def initialize(type = nil, foreignTradeZoneCode = nil, entryNumber = nil, licenseOrPermitNumber = nil, licenseOrPermitExpirationDate = nil)
    @type = type
    @foreignTradeZoneCode = foreignTradeZoneCode
    @entryNumber = entryNumber
    @licenseOrPermitNumber = licenseOrPermitNumber
    @licenseOrPermitExpirationDate = licenseOrPermitExpirationDate
  end
end

# {http://fedex.com/ws/pickup/v22}InternationalTrafficInArmsRegulationsDetail
#   licenseOrExemptionNumber - SOAP::SOAPString
class InternationalTrafficInArmsRegulationsDetail
  attr_accessor :licenseOrExemptionNumber

  def initialize(licenseOrExemptionNumber = nil)
    @licenseOrExemptionNumber = licenseOrExemptionNumber
  end
end

# {http://fedex.com/ws/pickup/v22}Localization
#   languageCode - SOAP::SOAPString
#   localeCode - SOAP::SOAPString
class Localization
  attr_accessor :languageCode
  attr_accessor :localeCode

  def initialize(languageCode = nil, localeCode = nil)
    @languageCode = languageCode
    @localeCode = localeCode
  end
end

# {http://fedex.com/ws/pickup/v22}MarkingOrTaggingDetail
#   count - SOAP::SOAPPositiveInteger
class MarkingOrTaggingDetail
  attr_accessor :count

  def initialize(count = nil)
    @count = count
  end
end

# {http://fedex.com/ws/pickup/v22}Money
#   currency - SOAP::SOAPString
#   amount - SOAP::SOAPDecimal
class Money
  attr_accessor :currency
  attr_accessor :amount

  def initialize(currency = nil, amount = nil)
    @currency = currency
    @amount = amount
  end
end

# {http://fedex.com/ws/pickup/v22}NonBusinessTimeDetail
#   personDays - SOAP::SOAPNonNegativeInteger
#   personHours - SOAP::SOAPNonNegativeInteger
class NonBusinessTimeDetail
  attr_accessor :personDays
  attr_accessor :personHours

  def initialize(personDays = nil, personHours = nil)
    @personDays = personDays
    @personHours = personHours
  end
end

# {http://fedex.com/ws/pickup/v22}Notification
#   severity - FedexWebServices::Soap::Pickup::NotificationSeverityType
#   source - SOAP::SOAPString
#   code - SOAP::SOAPString
#   message - SOAP::SOAPString
#   localizedMessage - SOAP::SOAPString
#   messageParameters - FedexWebServices::Soap::Pickup::NotificationParameter
class Notification
  attr_accessor :severity
  attr_accessor :source
  attr_accessor :code
  attr_accessor :message
  attr_accessor :localizedMessage
  attr_accessor :messageParameters

  def initialize(severity = nil, source = nil, code = nil, message = nil, localizedMessage = nil, messageParameters = [])
    @severity = severity
    @source = source
    @code = code
    @message = message
    @localizedMessage = localizedMessage
    @messageParameters = messageParameters
  end
end

# {http://fedex.com/ws/pickup/v22}NotificationDetail
#   notificationType - FedexWebServices::Soap::Pickup::NotificationType
#   emailDetail - FedexWebServices::Soap::Pickup::EMailDetail
#   faxDetail - FedexWebServices::Soap::Pickup::FaxDetail
#   smsDetail - FedexWebServices::Soap::Pickup::SmsDetail
#   localization - FedexWebServices::Soap::Pickup::Localization
class NotificationDetail
  attr_accessor :notificationType
  attr_accessor :emailDetail
  attr_accessor :faxDetail
  attr_accessor :smsDetail
  attr_accessor :localization

  def initialize(notificationType = nil, emailDetail = nil, faxDetail = nil, smsDetail = nil, localization = nil)
    @notificationType = notificationType
    @emailDetail = emailDetail
    @faxDetail = faxDetail
    @smsDetail = smsDetail
    @localization = localization
  end
end

# {http://fedex.com/ws/pickup/v22}NotificationParameter
#   id - SOAP::SOAPString
#   value - SOAP::SOAPString
class NotificationParameter
  attr_accessor :id
  attr_accessor :value

  def initialize(id = nil, value = nil)
    @id = id
    @value = value
  end
end

# {http://fedex.com/ws/pickup/v22}PalletShrinkwrapDetail
#   palletCount - SOAP::SOAPPositiveInteger
class PalletShrinkwrapDetail
  attr_accessor :palletCount

  def initialize(palletCount = nil)
    @palletCount = palletCount
  end
end

# {http://fedex.com/ws/pickup/v22}PalletsProvidedDetail
#   palletCount - SOAP::SOAPPositiveInteger
class PalletsProvidedDetail
  attr_accessor :palletCount

  def initialize(palletCount = nil)
    @palletCount = palletCount
  end
end

# {http://fedex.com/ws/pickup/v22}Party
#   accountNumber - SOAP::SOAPString
#   tins - FedexWebServices::Soap::Pickup::TaxpayerIdentification
#   contact - FedexWebServices::Soap::Pickup::Contact
#   address - FedexWebServices::Soap::Pickup::Address
class Party
  attr_accessor :accountNumber
  attr_accessor :tins
  attr_accessor :contact
  attr_accessor :address

  def initialize(accountNumber = nil, tins = [], contact = nil, address = nil)
    @accountNumber = accountNumber
    @tins = tins
    @contact = contact
    @address = address
  end
end

# {http://fedex.com/ws/pickup/v22}Payment
#   paymentType - FedexWebServices::Soap::Pickup::PaymentType
#   payor - FedexWebServices::Soap::Pickup::Payor
#   amount - FedexWebServices::Soap::Pickup::Money
class Payment
  attr_accessor :paymentType
  attr_accessor :payor
  attr_accessor :amount

  def initialize(paymentType = nil, payor = nil, amount = nil)
    @paymentType = paymentType
    @payor = payor
    @amount = amount
  end
end

# {http://fedex.com/ws/pickup/v22}Payor
#   responsibleParty - FedexWebServices::Soap::Pickup::Party
#   associatedAccounts - FedexWebServices::Soap::Pickup::AssociatedAccount
class Payor
  attr_accessor :responsibleParty
  attr_accessor :associatedAccounts

  def initialize(responsibleParty = nil, associatedAccounts = [])
    @responsibleParty = responsibleParty
    @associatedAccounts = associatedAccounts
  end
end

# {http://fedex.com/ws/pickup/v22}PendingShipmentDetail
#   type - FedexWebServices::Soap::Pickup::PendingShipmentType
#   expirationDate - SOAP::SOAPDate
#   emailLabelDetail - FedexWebServices::Soap::Pickup::EMailLabelDetail
#   processingOptions - FedexWebServices::Soap::Pickup::PendingShipmentProcessingOptionsRequested
#   recommendedDocumentSpecification - FedexWebServices::Soap::Pickup::RecommendedDocumentSpecification
#   documentReferences - FedexWebServices::Soap::Pickup::UploadDocumentReferenceDetail
class PendingShipmentDetail
  attr_accessor :type
  attr_accessor :expirationDate
  attr_accessor :emailLabelDetail
  attr_accessor :processingOptions
  attr_accessor :recommendedDocumentSpecification
  attr_accessor :documentReferences

  def initialize(type = nil, expirationDate = nil, emailLabelDetail = nil, processingOptions = nil, recommendedDocumentSpecification = nil, documentReferences = [])
    @type = type
    @expirationDate = expirationDate
    @emailLabelDetail = emailLabelDetail
    @processingOptions = processingOptions
    @recommendedDocumentSpecification = recommendedDocumentSpecification
    @documentReferences = documentReferences
  end
end

# {http://fedex.com/ws/pickup/v22}PendingShipmentProcessingOptionsRequested
class PendingShipmentProcessingOptionsRequested < ::Array
end

# {http://fedex.com/ws/pickup/v22}PickupAvailabilityReply
#   highestSeverity - FedexWebServices::Soap::Pickup::NotificationSeverityType
#   notifications - FedexWebServices::Soap::Pickup::Notification
#   transactionDetail - FedexWebServices::Soap::Pickup::TransactionDetail
#   version - FedexWebServices::Soap::Pickup::VersionId
#   requestTimestamp - SOAP::SOAPDateTime
#   options - FedexWebServices::Soap::Pickup::PickupScheduleOption
#   closeTimeType - FedexWebServices::Soap::Pickup::CloseTimeType
#   closeTime - SOAP::SOAPTime
#   openTime - SOAP::SOAPTime
#   localTime - SOAP::SOAPTime
class PickupAvailabilityReply
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :requestTimestamp
  attr_accessor :options
  attr_accessor :closeTimeType
  attr_accessor :closeTime
  attr_accessor :openTime
  attr_accessor :localTime

  def initialize(highestSeverity = nil, notifications = [], transactionDetail = nil, version = nil, requestTimestamp = nil, options = [], closeTimeType = nil, closeTime = nil, openTime = nil, localTime = nil)
    @highestSeverity = highestSeverity
    @notifications = notifications
    @transactionDetail = transactionDetail
    @version = version
    @requestTimestamp = requestTimestamp
    @options = options
    @closeTimeType = closeTimeType
    @closeTime = closeTime
    @openTime = openTime
    @localTime = localTime
  end
end

# {http://fedex.com/ws/pickup/v22}PickupAvailabilityRequest
#   webAuthenticationDetail - FedexWebServices::Soap::Pickup::WebAuthenticationDetail
#   clientDetail - FedexWebServices::Soap::Pickup::ClientDetail
#   transactionDetail - FedexWebServices::Soap::Pickup::TransactionDetail
#   version - FedexWebServices::Soap::Pickup::VersionId
#   pickupType - FedexWebServices::Soap::Pickup::PickupType
#   accountNumber - FedexWebServices::Soap::Pickup::AssociatedAccount
#   pickupAddress - FedexWebServices::Soap::Pickup::Address
#   pickupRequestType - FedexWebServices::Soap::Pickup::PickupRequestType
#   dispatchDate - SOAP::SOAPDate
#   numberOfBusinessDays - SOAP::SOAPPositiveInteger
#   packageReadyTime - SOAP::SOAPTime
#   customerCloseTime - SOAP::SOAPTime
#   carriers - FedexWebServices::Soap::Pickup::CarrierCodeType
#   shipmentAttributes - FedexWebServices::Soap::Pickup::PickupShipmentAttributes
#   packageDetails - FedexWebServices::Soap::Pickup::RequestedPickupPackageDetail
class PickupAvailabilityRequest
  attr_accessor :webAuthenticationDetail
  attr_accessor :clientDetail
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :pickupType
  attr_accessor :accountNumber
  attr_accessor :pickupAddress
  attr_accessor :pickupRequestType
  attr_accessor :dispatchDate
  attr_accessor :numberOfBusinessDays
  attr_accessor :packageReadyTime
  attr_accessor :customerCloseTime
  attr_accessor :carriers
  attr_accessor :shipmentAttributes
  attr_accessor :packageDetails

  def initialize(webAuthenticationDetail = nil, clientDetail = nil, transactionDetail = nil, version = nil, pickupType = nil, accountNumber = nil, pickupAddress = nil, pickupRequestType = [], dispatchDate = nil, numberOfBusinessDays = nil, packageReadyTime = nil, customerCloseTime = nil, carriers = [], shipmentAttributes = nil, packageDetails = [])
    @webAuthenticationDetail = webAuthenticationDetail
    @clientDetail = clientDetail
    @transactionDetail = transactionDetail
    @version = version
    @pickupType = pickupType
    @accountNumber = accountNumber
    @pickupAddress = pickupAddress
    @pickupRequestType = pickupRequestType
    @dispatchDate = dispatchDate
    @numberOfBusinessDays = numberOfBusinessDays
    @packageReadyTime = packageReadyTime
    @customerCloseTime = customerCloseTime
    @carriers = carriers
    @shipmentAttributes = shipmentAttributes
    @packageDetails = packageDetails
  end
end

# {http://fedex.com/ws/pickup/v22}PickupDangerousGoodsDetail
#   regulation - FedexWebServices::Soap::Pickup::HazardousCommodityRegulationType
#   accessibility - FedexWebServices::Soap::Pickup::DangerousGoodsAccessibilityType
#   options - FedexWebServices::Soap::Pickup::HazardousCommodityOptionType
class PickupDangerousGoodsDetail
  attr_accessor :regulation
  attr_accessor :accessibility
  attr_accessor :options

  def initialize(regulation = nil, accessibility = nil, options = [])
    @regulation = regulation
    @accessibility = accessibility
    @options = options
  end
end

# {http://fedex.com/ws/pickup/v22}PickupOriginDetail
#   useAccountAddress - SOAP::SOAPBoolean
#   addressId - SOAP::SOAPString
#   pickupLocation - FedexWebServices::Soap::Pickup::ContactAndAddress
#   packageLocation - FedexWebServices::Soap::Pickup::PickupBuildingLocationType
#   buildingPart - FedexWebServices::Soap::Pickup::BuildingPartCode
#   buildingPartDescription - SOAP::SOAPString
#   readyTimestamp - SOAP::SOAPDateTime
#   companyCloseTime - SOAP::SOAPTime
#   stayLate - SOAP::SOAPBoolean
#   pickupDateType - FedexWebServices::Soap::Pickup::PickupRequestType
#   lastAccessTime - SOAP::SOAPTime
#   geographicalPostalCode - SOAP::SOAPString
#   location - SOAP::SOAPString
#   deleteLastUsed - SOAP::SOAPBoolean
#   suppliesRequested - SOAP::SOAPString
#   earlyPickup - SOAP::SOAPBoolean
class PickupOriginDetail
  attr_accessor :useAccountAddress
  attr_accessor :addressId
  attr_accessor :pickupLocation
  attr_accessor :packageLocation
  attr_accessor :buildingPart
  attr_accessor :buildingPartDescription
  attr_accessor :readyTimestamp
  attr_accessor :companyCloseTime
  attr_accessor :stayLate
  attr_accessor :pickupDateType
  attr_accessor :lastAccessTime
  attr_accessor :geographicalPostalCode
  attr_accessor :location
  attr_accessor :deleteLastUsed
  attr_accessor :suppliesRequested
  attr_accessor :earlyPickup

  def initialize(useAccountAddress = nil, addressId = nil, pickupLocation = nil, packageLocation = nil, buildingPart = nil, buildingPartDescription = nil, readyTimestamp = nil, companyCloseTime = nil, stayLate = nil, pickupDateType = nil, lastAccessTime = nil, geographicalPostalCode = nil, location = nil, deleteLastUsed = nil, suppliesRequested = nil, earlyPickup = nil)
    @useAccountAddress = useAccountAddress
    @addressId = addressId
    @pickupLocation = pickupLocation
    @packageLocation = packageLocation
    @buildingPart = buildingPart
    @buildingPartDescription = buildingPartDescription
    @readyTimestamp = readyTimestamp
    @companyCloseTime = companyCloseTime
    @stayLate = stayLate
    @pickupDateType = pickupDateType
    @lastAccessTime = lastAccessTime
    @geographicalPostalCode = geographicalPostalCode
    @location = location
    @deleteLastUsed = deleteLastUsed
    @suppliesRequested = suppliesRequested
    @earlyPickup = earlyPickup
  end
end

# {http://fedex.com/ws/pickup/v22}PickupPackageSpecialServicesRequested
#   specialServiceTypes - SOAP::SOAPString
#   dangerousGoodsDetail - FedexWebServices::Soap::Pickup::PickupDangerousGoodsDetail
#   priorityAlertDetail - FedexWebServices::Soap::Pickup::PriorityAlertDetail
class PickupPackageSpecialServicesRequested
  attr_accessor :specialServiceTypes
  attr_accessor :dangerousGoodsDetail
  attr_accessor :priorityAlertDetail

  def initialize(specialServiceTypes = [], dangerousGoodsDetail = nil, priorityAlertDetail = nil)
    @specialServiceTypes = specialServiceTypes
    @dangerousGoodsDetail = dangerousGoodsDetail
    @priorityAlertDetail = priorityAlertDetail
  end
end

# {http://fedex.com/ws/pickup/v22}PickupScheduleOption
#   carrier - FedexWebServices::Soap::Pickup::CarrierCodeType
#   description - SOAP::SOAPString
#   scheduleDay - FedexWebServices::Soap::Pickup::PickupRequestType
#   available - SOAP::SOAPBoolean
#   pickupDate - SOAP::SOAPDate
#   cutOffTime - SOAP::SOAPTime
#   accessTime - SOAP::SOAPDuration
#   residentialAvailable - SOAP::SOAPBoolean
#   countryRelationship - FedexWebServices::Soap::Pickup::CountryRelationshipType
class PickupScheduleOption
  attr_accessor :carrier
  attr_accessor :description
  attr_accessor :scheduleDay
  attr_accessor :available
  attr_accessor :pickupDate
  attr_accessor :cutOffTime
  attr_accessor :accessTime
  attr_accessor :residentialAvailable
  attr_accessor :countryRelationship

  def initialize(carrier = nil, description = nil, scheduleDay = nil, available = nil, pickupDate = nil, cutOffTime = nil, accessTime = nil, residentialAvailable = nil, countryRelationship = nil)
    @carrier = carrier
    @description = description
    @scheduleDay = scheduleDay
    @available = available
    @pickupDate = pickupDate
    @cutOffTime = cutOffTime
    @accessTime = accessTime
    @residentialAvailable = residentialAvailable
    @countryRelationship = countryRelationship
  end
end

# {http://fedex.com/ws/pickup/v22}PickupShipmentAttributes
#   serviceType - SOAP::SOAPString
#   packagingType - SOAP::SOAPString
#   dimensions - FedexWebServices::Soap::Pickup::Dimensions
#   weight - FedexWebServices::Soap::Pickup::Weight
class PickupShipmentAttributes
  attr_accessor :serviceType
  attr_accessor :packagingType
  attr_accessor :dimensions
  attr_accessor :weight

  def initialize(serviceType = nil, packagingType = nil, dimensions = nil, weight = nil)
    @serviceType = serviceType
    @packagingType = packagingType
    @dimensions = dimensions
    @weight = weight
  end
end

# {http://fedex.com/ws/pickup/v22}PriorityAlertDetail
#   enhancementTypes - FedexWebServices::Soap::Pickup::PriorityAlertEnhancementType
#   content - SOAP::SOAPString
class PriorityAlertDetail
  attr_accessor :enhancementTypes
  attr_accessor :content

  def initialize(enhancementTypes = [], content = [])
    @enhancementTypes = enhancementTypes
    @content = content
  end
end

# {http://fedex.com/ws/pickup/v22}RecommendedDocumentSpecification
class RecommendedDocumentSpecification < ::Array
end

# {http://fedex.com/ws/pickup/v22}RequestedPickupPackageDetail
#   packageSpecialServices - FedexWebServices::Soap::Pickup::PickupPackageSpecialServicesRequested
#   weight - FedexWebServices::Soap::Pickup::Weight
class RequestedPickupPackageDetail
  attr_accessor :packageSpecialServices
  attr_accessor :weight

  def initialize(packageSpecialServices = nil, weight = nil)
    @packageSpecialServices = packageSpecialServices
    @weight = weight
  end
end

# {http://fedex.com/ws/pickup/v22}ReturnAssociationDetail
#   trackingNumber - SOAP::SOAPString
#   shipDate - SOAP::SOAPDate
class ReturnAssociationDetail
  attr_accessor :trackingNumber
  attr_accessor :shipDate

  def initialize(trackingNumber = nil, shipDate = nil)
    @trackingNumber = trackingNumber
    @shipDate = shipDate
  end
end

# {http://fedex.com/ws/pickup/v22}ReturnEMailDetail
#   merchantPhoneNumber - SOAP::SOAPString
#   allowedSpecialServices - FedexWebServices::Soap::Pickup::ReturnEMailAllowedSpecialServiceType
class ReturnEMailDetail
  attr_accessor :merchantPhoneNumber
  attr_accessor :allowedSpecialServices

  def initialize(merchantPhoneNumber = nil, allowedSpecialServices = [])
    @merchantPhoneNumber = merchantPhoneNumber
    @allowedSpecialServices = allowedSpecialServices
  end
end

# {http://fedex.com/ws/pickup/v22}ReturnShipmentDetail
#   returnType - FedexWebServices::Soap::Pickup::ReturnType
#   rma - FedexWebServices::Soap::Pickup::Rma
#   returnEMailDetail - FedexWebServices::Soap::Pickup::ReturnEMailDetail
#   returnAssociation - FedexWebServices::Soap::Pickup::ReturnAssociationDetail
class ReturnShipmentDetail
  attr_accessor :returnType
  attr_accessor :rma
  attr_accessor :returnEMailDetail
  attr_accessor :returnAssociation

  def initialize(returnType = nil, rma = nil, returnEMailDetail = nil, returnAssociation = nil)
    @returnType = returnType
    @rma = rma
    @returnEMailDetail = returnEMailDetail
    @returnAssociation = returnAssociation
  end
end

# {http://fedex.com/ws/pickup/v22}Rma
#   reason - SOAP::SOAPString
class Rma
  attr_accessor :reason

  def initialize(reason = nil)
    @reason = reason
  end
end

# {http://fedex.com/ws/pickup/v22}ShipmentAssemblyDetail
#   pieceCount - SOAP::SOAPNonNegativeInteger
#   weight - FedexWebServices::Soap::Pickup::Weight
class ShipmentAssemblyDetail
  attr_accessor :pieceCount
  attr_accessor :weight

  def initialize(pieceCount = nil, weight = nil)
    @pieceCount = pieceCount
    @weight = weight
  end
end

# {http://fedex.com/ws/pickup/v22}ShipmentDryIceDetail
#   packageCount - SOAP::SOAPNonNegativeInteger
#   totalWeight - FedexWebServices::Soap::Pickup::Weight
#   processingOptions - FedexWebServices::Soap::Pickup::ShipmentDryIceProcessingOptionsRequested
class ShipmentDryIceDetail
  attr_accessor :packageCount
  attr_accessor :totalWeight
  attr_accessor :processingOptions

  def initialize(packageCount = nil, totalWeight = nil, processingOptions = nil)
    @packageCount = packageCount
    @totalWeight = totalWeight
    @processingOptions = processingOptions
  end
end

# {http://fedex.com/ws/pickup/v22}ShipmentDryIceProcessingOptionsRequested
class ShipmentDryIceProcessingOptionsRequested < ::Array
end

# {http://fedex.com/ws/pickup/v22}ShipmentEventNotificationDetail
#   aggregationType - FedexWebServices::Soap::Pickup::ShipmentNotificationAggregationType
#   personalMessage - SOAP::SOAPString
#   eventNotifications - FedexWebServices::Soap::Pickup::ShipmentEventNotificationSpecification
class ShipmentEventNotificationDetail
  attr_accessor :aggregationType
  attr_accessor :personalMessage
  attr_accessor :eventNotifications

  def initialize(aggregationType = nil, personalMessage = nil, eventNotifications = [])
    @aggregationType = aggregationType
    @personalMessage = personalMessage
    @eventNotifications = eventNotifications
  end
end

# {http://fedex.com/ws/pickup/v22}ShipmentEventNotificationSpecification
#   role - FedexWebServices::Soap::Pickup::ShipmentNotificationRoleType
#   events - FedexWebServices::Soap::Pickup::NotificationEventType
#   notificationDetail - FedexWebServices::Soap::Pickup::NotificationDetail
#   formatSpecification - FedexWebServices::Soap::Pickup::ShipmentNotificationFormatSpecification
class ShipmentEventNotificationSpecification
  attr_accessor :role
  attr_accessor :events
  attr_accessor :notificationDetail
  attr_accessor :formatSpecification

  def initialize(role = nil, events = [], notificationDetail = nil, formatSpecification = nil)
    @role = role
    @events = events
    @notificationDetail = notificationDetail
    @formatSpecification = formatSpecification
  end
end

# {http://fedex.com/ws/pickup/v22}ShipmentNotificationFormatSpecification
#   type - FedexWebServices::Soap::Pickup::NotificationFormatType
class ShipmentNotificationFormatSpecification
  attr_accessor :type

  def initialize(type = nil)
    @type = type
  end
end

# {http://fedex.com/ws/pickup/v22}ShipmentSpecialServicesRequested
#   specialServiceTypes - SOAP::SOAPString
#   codDetail - FedexWebServices::Soap::Pickup::CodDetail
#   deliveryOnInvoiceAcceptanceDetail - FedexWebServices::Soap::Pickup::DeliveryOnInvoiceAcceptanceDetail
#   holdAtLocationDetail - FedexWebServices::Soap::Pickup::HoldAtLocationDetail
#   eventNotificationDetail - FedexWebServices::Soap::Pickup::ShipmentEventNotificationDetail
#   returnShipmentDetail - FedexWebServices::Soap::Pickup::ReturnShipmentDetail
#   pendingShipmentDetail - FedexWebServices::Soap::Pickup::PendingShipmentDetail
#   internationalControlledExportDetail - FedexWebServices::Soap::Pickup::InternationalControlledExportDetail
#   internationalTrafficInArmsRegulationsDetail - FedexWebServices::Soap::Pickup::InternationalTrafficInArmsRegulationsDetail
#   shipmentDryIceDetail - FedexWebServices::Soap::Pickup::ShipmentDryIceDetail
#   homeDeliveryPremiumDetail - FedexWebServices::Soap::Pickup::HomeDeliveryPremiumDetail
#   flatbedTrailerDetail - FedexWebServices::Soap::Pickup::FlatbedTrailerDetail
#   freightGuaranteeDetail - FedexWebServices::Soap::Pickup::FreightGuaranteeDetail
#   etdDetail - FedexWebServices::Soap::Pickup::EtdDetail
#   extraLaborDetail - FedexWebServices::Soap::Pickup::ExtraLaborDetail
#   palletShrinkwrapDetail - FedexWebServices::Soap::Pickup::PalletShrinkwrapDetail
#   palletsProvidedDetail - FedexWebServices::Soap::Pickup::PalletsProvidedDetail
#   detentionDetail - FedexWebServices::Soap::Pickup::DetentionDetail
#   markingOrTaggingDetail - FedexWebServices::Soap::Pickup::MarkingOrTaggingDetail
#   nonBusinessTimeDetail - FedexWebServices::Soap::Pickup::NonBusinessTimeDetail
#   shipmentAssemblyDetail - FedexWebServices::Soap::Pickup::ShipmentAssemblyDetail
#   sortAndSegregateDetail - FedexWebServices::Soap::Pickup::SortAndSegregateDetail
#   specialEquipmentDetail - FedexWebServices::Soap::Pickup::SpecialEquipmentDetail
#   storageDetail - FedexWebServices::Soap::Pickup::StorageDetail
#   weighingDetail - FedexWebServices::Soap::Pickup::WeighingDetail
#   customDeliveryWindowDetail - FedexWebServices::Soap::Pickup::CustomDeliveryWindowDetail
class ShipmentSpecialServicesRequested
  attr_accessor :specialServiceTypes
  attr_accessor :codDetail
  attr_accessor :deliveryOnInvoiceAcceptanceDetail
  attr_accessor :holdAtLocationDetail
  attr_accessor :eventNotificationDetail
  attr_accessor :returnShipmentDetail
  attr_accessor :pendingShipmentDetail
  attr_accessor :internationalControlledExportDetail
  attr_accessor :internationalTrafficInArmsRegulationsDetail
  attr_accessor :shipmentDryIceDetail
  attr_accessor :homeDeliveryPremiumDetail
  attr_accessor :flatbedTrailerDetail
  attr_accessor :freightGuaranteeDetail
  attr_accessor :etdDetail
  attr_accessor :extraLaborDetail
  attr_accessor :palletShrinkwrapDetail
  attr_accessor :palletsProvidedDetail
  attr_accessor :detentionDetail
  attr_accessor :markingOrTaggingDetail
  attr_accessor :nonBusinessTimeDetail
  attr_accessor :shipmentAssemblyDetail
  attr_accessor :sortAndSegregateDetail
  attr_accessor :specialEquipmentDetail
  attr_accessor :storageDetail
  attr_accessor :weighingDetail
  attr_accessor :customDeliveryWindowDetail

  def initialize(specialServiceTypes = [], codDetail = nil, deliveryOnInvoiceAcceptanceDetail = nil, holdAtLocationDetail = nil, eventNotificationDetail = nil, returnShipmentDetail = nil, pendingShipmentDetail = nil, internationalControlledExportDetail = nil, internationalTrafficInArmsRegulationsDetail = nil, shipmentDryIceDetail = nil, homeDeliveryPremiumDetail = nil, flatbedTrailerDetail = nil, freightGuaranteeDetail = nil, etdDetail = nil, extraLaborDetail = nil, palletShrinkwrapDetail = nil, palletsProvidedDetail = nil, detentionDetail = nil, markingOrTaggingDetail = nil, nonBusinessTimeDetail = nil, shipmentAssemblyDetail = nil, sortAndSegregateDetail = nil, specialEquipmentDetail = nil, storageDetail = nil, weighingDetail = nil, customDeliveryWindowDetail = nil)
    @specialServiceTypes = specialServiceTypes
    @codDetail = codDetail
    @deliveryOnInvoiceAcceptanceDetail = deliveryOnInvoiceAcceptanceDetail
    @holdAtLocationDetail = holdAtLocationDetail
    @eventNotificationDetail = eventNotificationDetail
    @returnShipmentDetail = returnShipmentDetail
    @pendingShipmentDetail = pendingShipmentDetail
    @internationalControlledExportDetail = internationalControlledExportDetail
    @internationalTrafficInArmsRegulationsDetail = internationalTrafficInArmsRegulationsDetail
    @shipmentDryIceDetail = shipmentDryIceDetail
    @homeDeliveryPremiumDetail = homeDeliveryPremiumDetail
    @flatbedTrailerDetail = flatbedTrailerDetail
    @freightGuaranteeDetail = freightGuaranteeDetail
    @etdDetail = etdDetail
    @extraLaborDetail = extraLaborDetail
    @palletShrinkwrapDetail = palletShrinkwrapDetail
    @palletsProvidedDetail = palletsProvidedDetail
    @detentionDetail = detentionDetail
    @markingOrTaggingDetail = markingOrTaggingDetail
    @nonBusinessTimeDetail = nonBusinessTimeDetail
    @shipmentAssemblyDetail = shipmentAssemblyDetail
    @sortAndSegregateDetail = sortAndSegregateDetail
    @specialEquipmentDetail = specialEquipmentDetail
    @storageDetail = storageDetail
    @weighingDetail = weighingDetail
    @customDeliveryWindowDetail = customDeliveryWindowDetail
  end
end

# {http://fedex.com/ws/pickup/v22}SmsDetail
#   phoneNumber - SOAP::SOAPString
#   phoneNumberCountryCode - SOAP::SOAPString
class SmsDetail
  attr_accessor :phoneNumber
  attr_accessor :phoneNumberCountryCode

  def initialize(phoneNumber = nil, phoneNumberCountryCode = nil)
    @phoneNumber = phoneNumber
    @phoneNumberCountryCode = phoneNumberCountryCode
  end
end

# {http://fedex.com/ws/pickup/v22}SortAndSegregateDetail
#   pieceCount - SOAP::SOAPNonNegativeInteger
#   weight - FedexWebServices::Soap::Pickup::Weight
class SortAndSegregateDetail
  attr_accessor :pieceCount
  attr_accessor :weight

  def initialize(pieceCount = nil, weight = nil)
    @pieceCount = pieceCount
    @weight = weight
  end
end

# {http://fedex.com/ws/pickup/v22}SpecialEquipmentDetail
class SpecialEquipmentDetail < ::Array
end

# {http://fedex.com/ws/pickup/v22}SpecialEquipmentLineItem
#   type - FedexWebServices::Soap::Pickup::SpecialEquipmentType
#   duration - SOAP::SOAPDuration
class SpecialEquipmentLineItem
  attr_accessor :type
  attr_accessor :duration

  def initialize(type = nil, duration = nil)
    @type = type
    @duration = duration
  end
end

# {http://fedex.com/ws/pickup/v22}StorageDetail
#   duration - SOAP::SOAPDuration
class StorageDetail
  attr_accessor :duration

  def initialize(duration = nil)
    @duration = duration
  end
end

# {http://fedex.com/ws/pickup/v22}TaxpayerIdentification
#   tinType - FedexWebServices::Soap::Pickup::TinType
#   number - SOAP::SOAPString
#   usage - SOAP::SOAPString
#   effectiveDate - SOAP::SOAPDateTime
#   expirationDate - SOAP::SOAPDateTime
class TaxpayerIdentification
  attr_accessor :tinType
  attr_accessor :number
  attr_accessor :usage
  attr_accessor :effectiveDate
  attr_accessor :expirationDate

  def initialize(tinType = nil, number = nil, usage = nil, effectiveDate = nil, expirationDate = nil)
    @tinType = tinType
    @number = number
    @usage = usage
    @effectiveDate = effectiveDate
    @expirationDate = expirationDate
  end
end

# {http://fedex.com/ws/pickup/v22}TrackingId
#   trackingIdType - FedexWebServices::Soap::Pickup::TrackingIdType
#   formId - SOAP::SOAPString
#   uspsApplicationId - SOAP::SOAPString
#   trackingNumber - SOAP::SOAPString
class TrackingId
  attr_accessor :trackingIdType
  attr_accessor :formId
  attr_accessor :uspsApplicationId
  attr_accessor :trackingNumber

  def initialize(trackingIdType = nil, formId = nil, uspsApplicationId = nil, trackingNumber = nil)
    @trackingIdType = trackingIdType
    @formId = formId
    @uspsApplicationId = uspsApplicationId
    @trackingNumber = trackingNumber
  end
end

# {http://fedex.com/ws/pickup/v22}TransactionDetail
#   customerTransactionId - SOAP::SOAPString
#   localization - FedexWebServices::Soap::Pickup::Localization
class TransactionDetail
  attr_accessor :customerTransactionId
  attr_accessor :localization

  def initialize(customerTransactionId = nil, localization = nil)
    @customerTransactionId = customerTransactionId
    @localization = localization
  end
end

# {http://fedex.com/ws/pickup/v22}UploadDocumentDetail
#   lineNumber - SOAP::SOAPNonNegativeInteger
#   customerReference - SOAP::SOAPString
#   documentProducer - FedexWebServices::Soap::Pickup::UploadDocumentProducerType
#   documentType - FedexWebServices::Soap::Pickup::UploadDocumentType
#   fileName - SOAP::SOAPString
#   documentContent - SOAP::SOAPBase64
#   expirationDate - SOAP::SOAPDate
class UploadDocumentDetail
  attr_accessor :lineNumber
  attr_accessor :customerReference
  attr_accessor :documentProducer
  attr_accessor :documentType
  attr_accessor :fileName
  attr_accessor :documentContent
  attr_accessor :expirationDate

  def initialize(lineNumber = nil, customerReference = nil, documentProducer = nil, documentType = nil, fileName = nil, documentContent = nil, expirationDate = nil)
    @lineNumber = lineNumber
    @customerReference = customerReference
    @documentProducer = documentProducer
    @documentType = documentType
    @fileName = fileName
    @documentContent = documentContent
    @expirationDate = expirationDate
  end
end

# {http://fedex.com/ws/pickup/v22}UploadDocumentReferenceDetail
#   lineNumber - SOAP::SOAPNonNegativeInteger
#   customerReference - SOAP::SOAPString
#   description - SOAP::SOAPString
#   documentProducer - FedexWebServices::Soap::Pickup::UploadDocumentProducerType
#   documentType - FedexWebServices::Soap::Pickup::UploadDocumentType
#   documentId - SOAP::SOAPString
#   documentIdProducer - FedexWebServices::Soap::Pickup::UploadDocumentIdProducer
class UploadDocumentReferenceDetail
  attr_accessor :lineNumber
  attr_accessor :customerReference
  attr_accessor :description
  attr_accessor :documentProducer
  attr_accessor :documentType
  attr_accessor :documentId
  attr_accessor :documentIdProducer

  def initialize(lineNumber = nil, customerReference = nil, description = nil, documentProducer = nil, documentType = nil, documentId = nil, documentIdProducer = nil)
    @lineNumber = lineNumber
    @customerReference = customerReference
    @description = description
    @documentProducer = documentProducer
    @documentType = documentType
    @documentId = documentId
    @documentIdProducer = documentIdProducer
  end
end

# {http://fedex.com/ws/pickup/v22}WeighingDetail
#   type - FedexWebServices::Soap::Pickup::WeighingScaleType
class WeighingDetail
  attr_accessor :type

  def initialize(type = nil)
    @type = type
  end
end

# {http://fedex.com/ws/pickup/v22}Weight
#   units - FedexWebServices::Soap::Pickup::WeightUnits
#   value - SOAP::SOAPDecimal
class Weight
  attr_accessor :units
  attr_accessor :value

  def initialize(units = nil, value = nil)
    @units = units
    @value = value
  end
end

# {http://fedex.com/ws/pickup/v22}WebAuthenticationDetail
#   parentCredential - FedexWebServices::Soap::Pickup::WebAuthenticationCredential
#   userCredential - FedexWebServices::Soap::Pickup::WebAuthenticationCredential
class WebAuthenticationDetail
  attr_accessor :parentCredential
  attr_accessor :userCredential

  def initialize(parentCredential = nil, userCredential = nil)
    @parentCredential = parentCredential
    @userCredential = userCredential
  end
end

# {http://fedex.com/ws/pickup/v22}WebAuthenticationCredential
#   key - SOAP::SOAPString
#   password - SOAP::SOAPString
class WebAuthenticationCredential
  attr_accessor :key
  attr_accessor :password

  def initialize(key = nil, password = nil)
    @key = key
    @password = password
  end
end

# {http://fedex.com/ws/pickup/v22}VersionId
#   serviceId - SOAP::SOAPString
#   major - SOAP::SOAPInt
#   intermediate - SOAP::SOAPInt
#   minor - SOAP::SOAPInt
class VersionId
  attr_accessor :serviceId
  attr_accessor :major
  attr_accessor :intermediate
  attr_accessor :minor

  def initialize(serviceId = nil, major = nil, intermediate = nil, minor = nil)
    @serviceId = serviceId
    @major = major
    @intermediate = intermediate
    @minor = minor
  end
end

# {http://fedex.com/ws/pickup/v22}AccessorRoleType
class AccessorRoleType < ::String
  SHIPMENT_COMPLETOR = new("SHIPMENT_COMPLETOR")
  SHIPMENT_INITIATOR = new("SHIPMENT_INITIATOR")
end

# {http://fedex.com/ws/pickup/v22}AssociatedAccountNumberType
class AssociatedAccountNumberType < ::String
  FEDEX_EXPRESS = new("FEDEX_EXPRESS")
  FEDEX_FREIGHT = new("FEDEX_FREIGHT")
  FEDEX_GROUND = new("FEDEX_GROUND")
  FEDEX_OFFICE = new("FEDEX_OFFICE")
end

# {http://fedex.com/ws/pickup/v22}BuildingPartCode
class BuildingPartCode < ::String
  APARTMENT = new("APARTMENT")
  BUILDING = new("BUILDING")
  DEPARTMENT = new("DEPARTMENT")
  FLOOR = new("FLOOR")
  ROOM = new("ROOM")
  SUITE = new("SUITE")
end

# {http://fedex.com/ws/pickup/v22}CarrierCodeType
class CarrierCodeType < ::String
  FDXC = new("FDXC")
  FDXE = new("FDXE")
  FDXG = new("FDXG")
  FDXO = new("FDXO")
  FXCC = new("FXCC")
  FXFR = new("FXFR")
  FXSP = new("FXSP")
end

# {http://fedex.com/ws/pickup/v22}ChargeBasisLevelType
class ChargeBasisLevelType < ::String
  CURRENT_PACKAGE = new("CURRENT_PACKAGE")
  SUM_OF_PACKAGES = new("SUM_OF_PACKAGES")
end

# {http://fedex.com/ws/pickup/v22}CloseTimeType
class CloseTimeType < ::String
  CUSTOMER_SPECIFIED = new("CUSTOMER_SPECIFIED")
  DEFAULT = new("DEFAULT")
end

# {http://fedex.com/ws/pickup/v22}CodAddTransportationChargeBasisType
class CodAddTransportationChargeBasisType < ::String
  COD_SURCHARGE = new("COD_SURCHARGE")
  NET_CHARGE = new("NET_CHARGE")
  NET_FREIGHT = new("NET_FREIGHT")
  TOTAL_CUSTOMER_CHARGE = new("TOTAL_CUSTOMER_CHARGE")
end

# {http://fedex.com/ws/pickup/v22}CodCollectionType
class CodCollectionType < ::String
  ANY = new("ANY")
  CASH = new("CASH")
  COMPANY_CHECK = new("COMPANY_CHECK")
  GUARANTEED_FUNDS = new("GUARANTEED_FUNDS")
  PERSONAL_CHECK = new("PERSONAL_CHECK")
end

# {http://fedex.com/ws/pickup/v22}CodReturnReferenceIndicatorType
class CodReturnReferenceIndicatorType < ::String
  INVOICE = new("INVOICE")
  PO = new("PO")
  REFERENCE = new("REFERENCE")
  TRACKING = new("TRACKING")
end

# {http://fedex.com/ws/pickup/v22}CountryRelationshipType
class CountryRelationshipType < ::String
  DOMESTIC = new("DOMESTIC")
  INTERNATIONAL = new("INTERNATIONAL")
end

# {http://fedex.com/ws/pickup/v22}CustomDeliveryWindowType
class CustomDeliveryWindowType < ::String
  AFTER = new("AFTER")
  BEFORE = new("BEFORE")
  BETWEEN = new("BETWEEN")
  ON = new("ON")
end

# {http://fedex.com/ws/pickup/v22}DangerousGoodsAccessibilityType
class DangerousGoodsAccessibilityType < ::String
  ACCESSIBLE = new("ACCESSIBLE")
  INACCESSIBLE = new("INACCESSIBLE")
end

# {http://fedex.com/ws/pickup/v22}DayOfWeekType
class DayOfWeekType < ::String
  FRI = new("FRI")
  MON = new("MON")
  SAT = new("SAT")
  SUN = new("SUN")
  THU = new("THU")
  TUE = new("TUE")
  WED = new("WED")
end

# {http://fedex.com/ws/pickup/v22}DistanceUnits
class DistanceUnits < ::String
  KM = new("KM")
  MI = new("MI")
end

# {http://fedex.com/ws/pickup/v22}EmailOptionType
class EmailOptionType < ::String
  PRODUCE_PAPERLESS_SHIPPING_FORMAT = new("PRODUCE_PAPERLESS_SHIPPING_FORMAT")
  SUPPRESS_ACCESS_EMAILS = new("SUPPRESS_ACCESS_EMAILS")
  SUPPRESS_ADDITIONAL_LANGUAGES = new("SUPPRESS_ADDITIONAL_LANGUAGES")
end

# {http://fedex.com/ws/pickup/v22}EtdAttributeType
class EtdAttributeType < ::String
  POST_SHIPMENT_UPLOAD_REQUESTED = new("POST_SHIPMENT_UPLOAD_REQUESTED")
end

# {http://fedex.com/ws/pickup/v22}EtdConfirmationType
class EtdConfirmationType < ::String
  CONFIRMED = new("CONFIRMED")
  DEFERRED = new("DEFERRED")
end

# {http://fedex.com/ws/pickup/v22}ExpressRegionCode
class ExpressRegionCode < ::String
  APAC = new("APAC")
  CA = new("CA")
  EMEA = new("EMEA")
  LAC = new("LAC")
  US = new("US")
end

# {http://fedex.com/ws/pickup/v22}FedExLocationType
class FedExLocationType < ::String
  FEDEX_AUTHORIZED_SHIP_CENTER = new("FEDEX_AUTHORIZED_SHIP_CENTER")
  FEDEX_EXPRESS_STATION = new("FEDEX_EXPRESS_STATION")
  FEDEX_FACILITY = new("FEDEX_FACILITY")
  FEDEX_FREIGHT_SERVICE_CENTER = new("FEDEX_FREIGHT_SERVICE_CENTER")
  FEDEX_GROUND_TERMINAL = new("FEDEX_GROUND_TERMINAL")
  FEDEX_HOME_DELIVERY_STATION = new("FEDEX_HOME_DELIVERY_STATION")
  FEDEX_OFFICE = new("FEDEX_OFFICE")
  FEDEX_SELF_SERVICE_LOCATION = new("FEDEX_SELF_SERVICE_LOCATION")
  FEDEX_SHIPSITE = new("FEDEX_SHIPSITE")
  FEDEX_SMART_POST_HUB = new("FEDEX_SMART_POST_HUB")
end

# {http://fedex.com/ws/pickup/v22}FlatbedTrailerOption
class FlatbedTrailerOption < ::String
  OVER_DIMENSION = new("OVER_DIMENSION")
  TARP = new("TARP")
end

# {http://fedex.com/ws/pickup/v22}FreightGuaranteeType
class FreightGuaranteeType < ::String
  GUARANTEED_DATE = new("GUARANTEED_DATE")
  GUARANTEED_MORNING = new("GUARANTEED_MORNING")
  GUARANTEED_TIME = new("GUARANTEED_TIME")
end

# {http://fedex.com/ws/pickup/v22}FreightServiceSchedulingType
class FreightServiceSchedulingType < ::String
  LIMITED = new("LIMITED")
  STANDARD = new("STANDARD")
  WILL_CALL = new("WILL_CALL")
end

# {http://fedex.com/ws/pickup/v22}FreightShipmentRoleType
class FreightShipmentRoleType < ::String
  CONSIGNEE = new("CONSIGNEE")
  SHIPPER = new("SHIPPER")
end

# {http://fedex.com/ws/pickup/v22}HazardousCommodityOptionType
class HazardousCommodityOptionType < ::String
  BATTERY = new("BATTERY")
  HAZARDOUS_MATERIALS = new("HAZARDOUS_MATERIALS")
  LIMITED_QUANTITIES_COMMODITIES = new("LIMITED_QUANTITIES_COMMODITIES")
  ORM_D = new("ORM_D")
  REPORTABLE_QUANTITIES = new("REPORTABLE_QUANTITIES")
  SMALL_QUANTITY_EXCEPTION = new("SMALL_QUANTITY_EXCEPTION")
end

# {http://fedex.com/ws/pickup/v22}HazardousCommodityRegulationType
class HazardousCommodityRegulationType < ::String
  ADR = new("ADR")
  DOT = new("DOT")
  IATA = new("IATA")
  ORMD = new("ORMD")
end

# {http://fedex.com/ws/pickup/v22}HomeDeliveryPremiumType
class HomeDeliveryPremiumType < ::String
  APPOINTMENT = new("APPOINTMENT")
  DATE_CERTAIN = new("DATE_CERTAIN")
  EVENING = new("EVENING")
end

# {http://fedex.com/ws/pickup/v22}InternationalControlledExportType
class InternationalControlledExportType < ::String
  DEA_036 = new("DEA_036")
  DEA_236 = new("DEA_236")
  DEA_486 = new("DEA_486")
  DSP_05 = new("DSP_05")
  DSP_61 = new("DSP_61")
  DSP_73 = new("DSP_73")
  DSP_85 = new("DSP_85")
  DSP_94 = new("DSP_94")
  DSP_LICENSE_AGREEMENT = new("DSP_LICENSE_AGREEMENT")
  FROM_FOREIGN_TRADE_ZONE = new("FROM_FOREIGN_TRADE_ZONE")
  WAREHOUSE_WITHDRAWAL = new("WAREHOUSE_WITHDRAWAL")
end

# {http://fedex.com/ws/pickup/v22}LinearUnits
class LinearUnits < ::String
  CM = new("CM")
  IN = new("IN")
end

# {http://fedex.com/ws/pickup/v22}NotificationEventType
class NotificationEventType < ::String
  ON_DELIVERY = new("ON_DELIVERY")
  ON_ESTIMATED_DELIVERY = new("ON_ESTIMATED_DELIVERY")
  ON_EXCEPTION = new("ON_EXCEPTION")
  ON_PICKUP_DRIVER_ARRIVED = new("ON_PICKUP_DRIVER_ARRIVED")
  ON_PICKUP_DRIVER_ASSIGNED = new("ON_PICKUP_DRIVER_ASSIGNED")
  ON_PICKUP_DRIVER_DEPARTED = new("ON_PICKUP_DRIVER_DEPARTED")
  ON_PICKUP_DRIVER_EN_ROUTE = new("ON_PICKUP_DRIVER_EN_ROUTE")
  ON_SHIPMENT = new("ON_SHIPMENT")
  ON_TENDER = new("ON_TENDER")
end

# {http://fedex.com/ws/pickup/v22}NotificationFormatType
class NotificationFormatType < ::String
  HTML = new("HTML")
  TEXT = new("TEXT")
end

# {http://fedex.com/ws/pickup/v22}NotificationSeverityType
class NotificationSeverityType < ::String
  ERROR = new("ERROR")
  FAILURE = new("FAILURE")
  NOTE = new("NOTE")
  SUCCESS = new("SUCCESS")
  WARNING = new("WARNING")
end

# {http://fedex.com/ws/pickup/v22}NotificationType
class NotificationType < ::String
  EMAIL = new("EMAIL")
  FAX = new("FAX")
  SMS_TEXT_MESSAGE = new("SMS_TEXT_MESSAGE")
end

# {http://fedex.com/ws/pickup/v22}PaymentType
class PaymentType < ::String
  ACCOUNT = new("ACCOUNT")
  CASH = new("CASH")
  COLLECT = new("COLLECT")
  CREDIT_CARD = new("CREDIT_CARD")
  RECIPIENT = new("RECIPIENT")
  SENDER = new("SENDER")
  THIRD_PARTY = new("THIRD_PARTY")
end

# {http://fedex.com/ws/pickup/v22}PendingShipmentProcessingOptionType
class PendingShipmentProcessingOptionType < ::String
  ALLOW_MODIFICATIONS = new("ALLOW_MODIFICATIONS")
end

# {http://fedex.com/ws/pickup/v22}PendingShipmentType
class PendingShipmentType < ::String
  EMAIL = new("EMAIL")
end

# {http://fedex.com/ws/pickup/v22}PhysicalPackagingType
class PhysicalPackagingType < ::String
  BAG = new("BAG")
  BARREL = new("BARREL")
  BASKET = new("BASKET")
  BOX = new("BOX")
  BUCKET = new("BUCKET")
  BUNDLE = new("BUNDLE")
  CAGE = new("CAGE")
  CARTON = new("CARTON")
  CASE = new("CASE")
  CHEST = new("CHEST")
  CONTAINER = new("CONTAINER")
  CRATE = new("CRATE")
  CYLINDER = new("CYLINDER")
  DRUM = new("DRUM")
  ENVELOPE = new("ENVELOPE")
  HAMPER = new("HAMPER")
  OTHER = new("OTHER")
  PACKAGE = new("PACKAGE")
  PAIL = new("PAIL")
  PALLET = new("PALLET")
  PARCEL = new("PARCEL")
  PIECE = new("PIECE")
  REEL = new("REEL")
  ROLL = new("ROLL")
  SACK = new("SACK")
  SHRINK_WRAPPED = new("SHRINK_WRAPPED")
  SKID = new("SKID")
  TANK = new("TANK")
  TOTE_BIN = new("TOTE_BIN")
  TUBE = new("TUBE")
  UNIT = new("UNIT")
end

# {http://fedex.com/ws/pickup/v22}PickupBuildingLocationType
class PickupBuildingLocationType < ::String
  FRONT = new("FRONT")
  NONE = new("NONE")
  REAR = new("REAR")
  SIDE = new("SIDE")
end

# {http://fedex.com/ws/pickup/v22}PickupEventType
class PickupEventType < ::String
  ASSIGNED_TO_DRIVER = new("ASSIGNED_TO_DRIVER")
  CANCELED = new("CANCELED")
  DRIVER_ARRIVED = new("DRIVER_ARRIVED")
  DRIVER_DEPARTED = new("DRIVER_DEPARTED")
  DRIVER_EN_ROUTE = new("DRIVER_EN_ROUTE")
  EXCEPTION = new("EXCEPTION")
  PICKED_UP = new("PICKED_UP")
  SCHEDULED = new("SCHEDULED")
end

# {http://fedex.com/ws/pickup/v22}PickupRequestType
class PickupRequestType < ::String
  FUTURE_DAY = new("FUTURE_DAY")
  SAME_DAY = new("SAME_DAY")
end

# {http://fedex.com/ws/pickup/v22}PickupServiceCategoryType
class PickupServiceCategoryType < ::String
  FEDEX_DISTANCE_DEFERRED = new("FEDEX_DISTANCE_DEFERRED")
  FEDEX_NEXT_DAY_AFTERNOON = new("FEDEX_NEXT_DAY_AFTERNOON")
  FEDEX_NEXT_DAY_EARLY_MORNING = new("FEDEX_NEXT_DAY_EARLY_MORNING")
  FEDEX_NEXT_DAY_END_OF_DAY = new("FEDEX_NEXT_DAY_END_OF_DAY")
  FEDEX_NEXT_DAY_FREIGHT = new("FEDEX_NEXT_DAY_FREIGHT")
  FEDEX_NEXT_DAY_MID_MORNING = new("FEDEX_NEXT_DAY_MID_MORNING")
  SAME_DAY = new("SAME_DAY")
  SAME_DAY_CITY = new("SAME_DAY_CITY")
end

# {http://fedex.com/ws/pickup/v22}PickupType
class PickupType < ::String
  ON_CALL = new("ON_CALL")
  REGULAR_STOP_WITH_AUTO_CANCEL = new("REGULAR_STOP_WITH_AUTO_CANCEL")
  TAG = new("TAG")
end

# {http://fedex.com/ws/pickup/v22}PriorityAlertEnhancementType
class PriorityAlertEnhancementType < ::String
  PRIORITY_ALERT_PLUS = new("PRIORITY_ALERT_PLUS")
end

# {http://fedex.com/ws/pickup/v22}RateLevelBasisType
class RateLevelBasisType < ::String
  BUNDLED_RATE = new("BUNDLED_RATE")
  INDIVIDUAL_PACKAGE_RATE = new("INDIVIDUAL_PACKAGE_RATE")
end

# {http://fedex.com/ws/pickup/v22}RateTypeBasisType
class RateTypeBasisType < ::String
  ACCOUNT = new("ACCOUNT")
  ACTUAL = new("ACTUAL")
  CURRENT = new("CURRENT")
  CUSTOM = new("CUSTOM")
  LIST = new("LIST")
end

# {http://fedex.com/ws/pickup/v22}RecommendedDocumentType
class RecommendedDocumentType < ::String
  ANTIQUE_STATEMENT_EUROPEAN_UNION = new("ANTIQUE_STATEMENT_EUROPEAN_UNION")
  ANTIQUE_STATEMENT_UNITED_STATES = new("ANTIQUE_STATEMENT_UNITED_STATES")
  ASSEMBLER_DECLARATION = new("ASSEMBLER_DECLARATION")
  BEARING_WORKSHEET = new("BEARING_WORKSHEET")
  CERTIFICATE_OF_SHIPMENTS_TO_SYRIA = new("CERTIFICATE_OF_SHIPMENTS_TO_SYRIA")
  COMMERCIAL_INVOICE_FOR_THE_CARIBBEAN_COMMON_MARKET = new("COMMERCIAL_INVOICE_FOR_THE_CARIBBEAN_COMMON_MARKET")
  CONIFEROUS_SOLID_WOOD_PACKAGING_MATERIAL_TO_THE_PEOPLES_REPUBLIC_OF_CHINA = new("CONIFEROUS_SOLID_WOOD_PACKAGING_MATERIAL_TO_THE_PEOPLES_REPUBLIC_OF_CHINA")
  DECLARATION_FOR_FREE_ENTRY_OF_RETURNED_AMERICAN_PRODUCTS = new("DECLARATION_FOR_FREE_ENTRY_OF_RETURNED_AMERICAN_PRODUCTS")
  DECLARATION_OF_BIOLOGICAL_STANDARDS = new("DECLARATION_OF_BIOLOGICAL_STANDARDS")
  DECLARATION_OF_IMPORTED_ELECTRONIC_PRODUCTS_SUBJECT_TO_RADIATION_CONTROL_STANDARD = new("DECLARATION_OF_IMPORTED_ELECTRONIC_PRODUCTS_SUBJECT_TO_RADIATION_CONTROL_STANDARD")
  ELECTRONIC_INTEGRATED_CIRCUIT_WORKSHEET = new("ELECTRONIC_INTEGRATED_CIRCUIT_WORKSHEET")
  FILM_AND_VIDEO_CERTIFICATE = new("FILM_AND_VIDEO_CERTIFICATE")
  INTERIM_FOOTWEAR_INVOICE = new("INTERIM_FOOTWEAR_INVOICE")
  NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_ENGLISH = new("NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_ENGLISH")
  NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_FRENCH = new("NAFTA_CERTIFICATE_OF_ORIGIN_CANADA_FRENCH")
  NAFTA_CERTIFICATE_OF_ORIGIN_SPANISH = new("NAFTA_CERTIFICATE_OF_ORIGIN_SPANISH")
  NAFTA_CERTIFICATE_OF_ORIGIN_UNITED_STATES = new("NAFTA_CERTIFICATE_OF_ORIGIN_UNITED_STATES")
  PACKING_LIST = new("PACKING_LIST")
  PRINTED_CIRCUIT_BOARD_WORKSHEET = new("PRINTED_CIRCUIT_BOARD_WORKSHEET")
  REPAIRED_WATCH_BREAKOUT_WORKSHEET = new("REPAIRED_WATCH_BREAKOUT_WORKSHEET")
  STATEMENT_REGARDING_THE_IMPORT_OF_RADIO_FREQUENCY_DEVICES = new("STATEMENT_REGARDING_THE_IMPORT_OF_RADIO_FREQUENCY_DEVICES")
  TOXIC_SUBSTANCES_CONTROL_ACT = new("TOXIC_SUBSTANCES_CONTROL_ACT")
  UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_NON_TEXTILES = new("UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_NON_TEXTILES")
  UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_TEXTILES = new("UNITED_STATES_CARIBBEAN_BASIN_TRADE_PARTNERSHIP_ACT_CERTIFICATE_OF_ORIGIN_TEXTILES")
  UNITED_STATES_NEW_WATCH_WORKSHEET = new("UNITED_STATES_NEW_WATCH_WORKSHEET")
  UNITED_STATES_WATCH_REPAIR_DECLARATION = new("UNITED_STATES_WATCH_REPAIR_DECLARATION")
end

# {http://fedex.com/ws/pickup/v22}RequestedShippingDocumentType
class RequestedShippingDocumentType < ::String
  CERTIFICATE_OF_ORIGIN = new("CERTIFICATE_OF_ORIGIN")
  COMMERCIAL_INVOICE = new("COMMERCIAL_INVOICE")
  CUSTOMER_SPECIFIED_LABELS = new("CUSTOMER_SPECIFIED_LABELS")
  CUSTOM_PACKAGE_DOCUMENT = new("CUSTOM_PACKAGE_DOCUMENT")
  CUSTOM_SHIPMENT_DOCUMENT = new("CUSTOM_SHIPMENT_DOCUMENT")
  DANGEROUS_GOODS_SHIPPERS_DECLARATION = new("DANGEROUS_GOODS_SHIPPERS_DECLARATION")
  EXPORT_DECLARATION = new("EXPORT_DECLARATION")
  FREIGHT_ADDRESS_LABEL = new("FREIGHT_ADDRESS_LABEL")
  GENERAL_AGENCY_AGREEMENT = new("GENERAL_AGENCY_AGREEMENT")
  LABEL = new("LABEL")
  NAFTA_CERTIFICATE_OF_ORIGIN = new("NAFTA_CERTIFICATE_OF_ORIGIN")
  OP_900 = new("OP_900")
  PENDING_SHIPMENT_EMAIL_NOTIFICATION = new("PENDING_SHIPMENT_EMAIL_NOTIFICATION")
  PRO_FORMA_INVOICE = new("PRO_FORMA_INVOICE")
  RETURN_INSTRUCTIONS = new("RETURN_INSTRUCTIONS")
end

# {http://fedex.com/ws/pickup/v22}ReturnEMailAllowedSpecialServiceType
class ReturnEMailAllowedSpecialServiceType < ::String
  SATURDAY_DELIVERY = new("SATURDAY_DELIVERY")
  SATURDAY_PICKUP = new("SATURDAY_PICKUP")
end

# {http://fedex.com/ws/pickup/v22}ReturnType
class ReturnType < ::String
  FEDEX_TAG = new("FEDEX_TAG")
  NET_RETURN = new("NET_RETURN")
  PENDING = new("PENDING")
  PRINT_RETURN_LABEL = new("PRINT_RETURN_LABEL")
  VOICE_CALL_TAG = new("VOICE_CALL_TAG")
end

# {http://fedex.com/ws/pickup/v22}ShipmentDryIceProcessingOptionType
class ShipmentDryIceProcessingOptionType < ::String
  SHIPMENT_LEVEL_DRY_ICE_ONLY = new("SHIPMENT_LEVEL_DRY_ICE_ONLY")
end

# {http://fedex.com/ws/pickup/v22}ShipmentNotificationAggregationType
class ShipmentNotificationAggregationType < ::String
  PER_PACKAGE = new("PER_PACKAGE")
  PER_SHIPMENT = new("PER_SHIPMENT")
end

# {http://fedex.com/ws/pickup/v22}ShipmentNotificationRoleType
class ShipmentNotificationRoleType < ::String
  BROKER = new("BROKER")
  OTHER = new("OTHER")
  RECIPIENT = new("RECIPIENT")
  SHIPPER = new("SHIPPER")
end

# {http://fedex.com/ws/pickup/v22}SpecialEquipmentType
class SpecialEquipmentType < ::String
  FORK_LIFT = new("FORK_LIFT")
end

# {http://fedex.com/ws/pickup/v22}TinType
class TinType < ::String
  BUSINESS_NATIONAL = new("BUSINESS_NATIONAL")
  BUSINESS_STATE = new("BUSINESS_STATE")
  BUSINESS_UNION = new("BUSINESS_UNION")
  PERSONAL_NATIONAL = new("PERSONAL_NATIONAL")
  PERSONAL_STATE = new("PERSONAL_STATE")
end

# {http://fedex.com/ws/pickup/v22}TrackingIdType
class TrackingIdType < ::String
  EXPRESS = new("EXPRESS")
  FEDEX = new("FEDEX")
  FREIGHT = new("FREIGHT")
  GROUND = new("GROUND")
  USPS = new("USPS")
end

# {http://fedex.com/ws/pickup/v22}TrailerSizeType
class TrailerSizeType < ::String
  TRAILER_28_FT = new("TRAILER_28_FT")
  TRAILER_48_FT = new("TRAILER_48_FT")
  TRAILER_53_FT = new("TRAILER_53_FT")
end

# {http://fedex.com/ws/pickup/v22}TruckType
class TruckType < ::String
  DROP_TRAILER_AGREEMENT = new("DROP_TRAILER_AGREEMENT")
  LIFTGATE = new("LIFTGATE")
  TRACTOR_TRAILER_ACCESS = new("TRACTOR_TRAILER_ACCESS")
end

# {http://fedex.com/ws/pickup/v22}UploadDocumentIdProducer
class UploadDocumentIdProducer < ::String
  CUSTOMER = new("CUSTOMER")
  FEDEX_CAFE = new("FEDEX_CAFE")
  FEDEX_CSHP = new("FEDEX_CSHP")
  FEDEX_FXRS = new("FEDEX_FXRS")
  FEDEX_GSMW = new("FEDEX_GSMW")
  FEDEX_GTM = new("FEDEX_GTM")
  FEDEX_INET = new("FEDEX_INET")
end

# {http://fedex.com/ws/pickup/v22}UploadDocumentProducerType
class UploadDocumentProducerType < ::String
  CUSTOMER = new("CUSTOMER")
  FEDEX_CAFE = new("FEDEX_CAFE")
  FEDEX_CLS = new("FEDEX_CLS")
  FEDEX_FIDT = new("FEDEX_FIDT")
  FEDEX_FXRS = new("FEDEX_FXRS")
  FEDEX_GSMW = new("FEDEX_GSMW")
  FEDEX_GTM = new("FEDEX_GTM")
  OTHER = new("OTHER")
end

# {http://fedex.com/ws/pickup/v22}UploadDocumentType
class UploadDocumentType < ::String
  CERTIFICATE_OF_ORIGIN = new("CERTIFICATE_OF_ORIGIN")
  COMMERCIAL_INVOICE = new("COMMERCIAL_INVOICE")
  ETD_LABEL = new("ETD_LABEL")
  NAFTA_CERTIFICATE_OF_ORIGIN = new("NAFTA_CERTIFICATE_OF_ORIGIN")
  NET_RATE_SHEET = new("NET_RATE_SHEET")
  OTHER = new("OTHER")
  PRO_FORMA_INVOICE = new("PRO_FORMA_INVOICE")
end

# {http://fedex.com/ws/pickup/v22}WeighingScaleType
class WeighingScaleType < ::String
  FEDEX_SCALE = new("FEDEX_SCALE")
  PUBLIC_SCALE = new("PUBLIC_SCALE")
end

# {http://fedex.com/ws/pickup/v22}WeightUnits
class WeightUnits < ::String
  KG = new("KG")
  LB = new("LB")
end


end; end; end
