# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require_relative 'TrackServiceDefinitions.rb'
require_relative 'TrackServiceDefinitionsMappingRegistry.rb'
require 'soap/rpc/driver'

module FedexWebServices::Soap::Track

class TrackPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://wsbeta.fedex.com:443/web-services/track"

  Methods = [
    [ "http://fedex.com/ws/track/v19/track",
      "track",
      [ [:in, "TrackRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/track/v19", "TrackRequest"]],
        [:out, "TrackReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/track/v19", "TrackReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://fedex.com/ws/track/v19/getTrackingDocuments",
      "getTrackingDocuments",
      [ [:in, "GetTrackingDocumentsRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/track/v19", "GetTrackingDocumentsRequest"]],
        [:out, "GetTrackingDocumentsReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/track/v19", "GetTrackingDocumentsReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://fedex.com/ws/track/v19/sendNotifications",
      "sendNotifications",
      [ [:in, "SendNotificationsRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/track/v19", "SendNotificationsRequest"]],
        [:out, "SendNotificationsReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/track/v19", "SendNotificationsReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = TrackServiceDefinitionsMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = TrackServiceDefinitionsMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
