# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require 'xsd/qname'

module FedexWebServices; module Soap; module Track


# {http://fedex.com/ws/track/v19}Address
#   streetLines - SOAP::SOAPString
#   city - SOAP::SOAPString
#   stateOrProvinceCode - SOAP::SOAPString
#   postalCode - SOAP::SOAPString
#   urbanizationCode - SOAP::SOAPString
#   countryCode - SOAP::SOAPString
#   countryName - SOAP::SOAPString
#   residential - SOAP::SOAPBoolean
#   geographicCoordinates - SOAP::SOAPString
class Address
  attr_accessor :streetLines
  attr_accessor :city
  attr_accessor :stateOrProvinceCode
  attr_accessor :postalCode
  attr_accessor :urbanizationCode
  attr_accessor :countryCode
  attr_accessor :countryName
  attr_accessor :residential
  attr_accessor :geographicCoordinates

  def initialize(streetLines = [], city = nil, stateOrProvinceCode = nil, postalCode = nil, urbanizationCode = nil, countryCode = nil, countryName = nil, residential = nil, geographicCoordinates = nil)
    @streetLines = streetLines
    @city = city
    @stateOrProvinceCode = stateOrProvinceCode
    @postalCode = postalCode
    @urbanizationCode = urbanizationCode
    @countryCode = countryCode
    @countryName = countryName
    @residential = residential
    @geographicCoordinates = geographicCoordinates
  end
end

# {http://fedex.com/ws/track/v19}AppointmentDetail
#   date - SOAP::SOAPDate
#   windowDetails - FedexWebServices::Soap::Track::AppointmentTimeDetail
class AppointmentDetail
  attr_accessor :date
  attr_accessor :windowDetails

  def initialize(date = nil, windowDetails = [])
    @date = date
    @windowDetails = windowDetails
  end
end

# {http://fedex.com/ws/track/v19}AppointmentTimeDetail
#   type - FedexWebServices::Soap::Track::AppointmentWindowType
#   window - FedexWebServices::Soap::Track::LocalTimeRange
#   description - SOAP::SOAPString
class AppointmentTimeDetail
  attr_accessor :type
  attr_accessor :window
  attr_accessor :description

  def initialize(type = nil, window = nil, description = nil)
    @type = type
    @window = window
    @description = description
  end
end

# {http://fedex.com/ws/track/v19}AvailableImagesDetail
#   type - FedexWebServices::Soap::Track::AvailableImageType
#   size - FedexWebServices::Soap::Track::ImageSizeType
class AvailableImagesDetail
  attr_accessor :type
  attr_accessor :size

  def initialize(type = nil, size = nil)
    @type = type
    @size = size
  end
end

# {http://fedex.com/ws/track/v19}ClientDetail
#   accountNumber - SOAP::SOAPString
#   meterNumber - SOAP::SOAPString
#   integratorId - SOAP::SOAPString
#   localization - FedexWebServices::Soap::Track::Localization
class ClientDetail
  attr_accessor :accountNumber
  attr_accessor :meterNumber
  attr_accessor :integratorId
  attr_accessor :localization

  def initialize(accountNumber = nil, meterNumber = nil, integratorId = nil, localization = nil)
    @accountNumber = accountNumber
    @meterNumber = meterNumber
    @integratorId = integratorId
    @localization = localization
  end
end

# {http://fedex.com/ws/track/v19}Commodity
#   commodityId - SOAP::SOAPString
#   name - SOAP::SOAPString
#   numberOfPieces - SOAP::SOAPNonNegativeInteger
#   description - SOAP::SOAPString
#   purpose - FedexWebServices::Soap::Track::CommodityPurposeType
#   countryOfManufacture - SOAP::SOAPString
#   harmonizedCode - SOAP::SOAPString
#   weight - FedexWebServices::Soap::Track::Weight
#   quantity - SOAP::SOAPDecimal
#   quantityUnits - SOAP::SOAPString
#   additionalMeasures - FedexWebServices::Soap::Track::Measure
#   unitPrice - FedexWebServices::Soap::Track::Money
#   customsValue - FedexWebServices::Soap::Track::Money
#   exciseConditions - FedexWebServices::Soap::Track::EdtExciseCondition
#   exportLicenseNumber - SOAP::SOAPString
#   exportLicenseExpirationDate - SOAP::SOAPDate
#   cIMarksAndNumbers - SOAP::SOAPString
#   partNumber - SOAP::SOAPString
#   naftaDetail - FedexWebServices::Soap::Track::NaftaCommodityDetail
class Commodity
  attr_accessor :commodityId
  attr_accessor :name
  attr_accessor :numberOfPieces
  attr_accessor :description
  attr_accessor :purpose
  attr_accessor :countryOfManufacture
  attr_accessor :harmonizedCode
  attr_accessor :weight
  attr_accessor :quantity
  attr_accessor :quantityUnits
  attr_accessor :additionalMeasures
  attr_accessor :unitPrice
  attr_accessor :customsValue
  attr_accessor :exciseConditions
  attr_accessor :exportLicenseNumber
  attr_accessor :exportLicenseExpirationDate
  attr_accessor :cIMarksAndNumbers
  attr_accessor :partNumber
  attr_accessor :naftaDetail

  def initialize(commodityId = nil, name = nil, numberOfPieces = nil, description = nil, purpose = nil, countryOfManufacture = nil, harmonizedCode = nil, weight = nil, quantity = nil, quantityUnits = nil, additionalMeasures = [], unitPrice = nil, customsValue = nil, exciseConditions = [], exportLicenseNumber = nil, exportLicenseExpirationDate = nil, cIMarksAndNumbers = nil, partNumber = nil, naftaDetail = nil)
    @commodityId = commodityId
    @name = name
    @numberOfPieces = numberOfPieces
    @description = description
    @purpose = purpose
    @countryOfManufacture = countryOfManufacture
    @harmonizedCode = harmonizedCode
    @weight = weight
    @quantity = quantity
    @quantityUnits = quantityUnits
    @additionalMeasures = additionalMeasures
    @unitPrice = unitPrice
    @customsValue = customsValue
    @exciseConditions = exciseConditions
    @exportLicenseNumber = exportLicenseNumber
    @exportLicenseExpirationDate = exportLicenseExpirationDate
    @cIMarksAndNumbers = cIMarksAndNumbers
    @partNumber = partNumber
    @naftaDetail = naftaDetail
  end
end

# {http://fedex.com/ws/track/v19}CompletedTrackDetail
#   highestSeverity - FedexWebServices::Soap::Track::NotificationSeverityType
#   notifications - FedexWebServices::Soap::Track::Notification
#   duplicateWaybill - SOAP::SOAPBoolean
#   moreData - SOAP::SOAPBoolean
#   pagingToken - SOAP::SOAPString
#   trackDetailsCount - SOAP::SOAPNonNegativeInteger
#   trackDetails - FedexWebServices::Soap::Track::TrackDetail
class CompletedTrackDetail
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :duplicateWaybill
  attr_accessor :moreData
  attr_accessor :pagingToken
  attr_accessor :trackDetailsCount
  attr_accessor :trackDetails

  def initialize(highestSeverity = nil, notifications = [], duplicateWaybill = nil, moreData = nil, pagingToken = nil, trackDetailsCount = nil, trackDetails = [])
    @highestSeverity = highestSeverity
    @notifications = notifications
    @duplicateWaybill = duplicateWaybill
    @moreData = moreData
    @pagingToken = pagingToken
    @trackDetailsCount = trackDetailsCount
    @trackDetails = trackDetails
  end
end

# {http://fedex.com/ws/track/v19}Contact
#   personName - SOAP::SOAPString
#   title - SOAP::SOAPString
#   companyName - SOAP::SOAPString
#   phoneNumber - SOAP::SOAPString
#   phoneExtension - SOAP::SOAPString
#   tollFreePhoneNumber - SOAP::SOAPString
#   pagerNumber - SOAP::SOAPString
#   faxNumber - SOAP::SOAPString
#   eMailAddress - SOAP::SOAPString
class Contact
  attr_accessor :personName
  attr_accessor :title
  attr_accessor :companyName
  attr_accessor :phoneNumber
  attr_accessor :phoneExtension
  attr_accessor :tollFreePhoneNumber
  attr_accessor :pagerNumber
  attr_accessor :faxNumber
  attr_accessor :eMailAddress

  def initialize(personName = nil, title = nil, companyName = nil, phoneNumber = nil, phoneExtension = nil, tollFreePhoneNumber = nil, pagerNumber = nil, faxNumber = nil, eMailAddress = nil)
    @personName = personName
    @title = title
    @companyName = companyName
    @phoneNumber = phoneNumber
    @phoneExtension = phoneExtension
    @tollFreePhoneNumber = tollFreePhoneNumber
    @pagerNumber = pagerNumber
    @faxNumber = faxNumber
    @eMailAddress = eMailAddress
  end
end

# {http://fedex.com/ws/track/v19}ContactAndAddress
#   contact - FedexWebServices::Soap::Track::Contact
#   address - FedexWebServices::Soap::Track::Address
class ContactAndAddress
  attr_accessor :contact
  attr_accessor :address

  def initialize(contact = nil, address = nil)
    @contact = contact
    @address = address
  end
end

# {http://fedex.com/ws/track/v19}ContentRecord
#   partNumber - SOAP::SOAPString
#   itemNumber - SOAP::SOAPString
#   receivedQuantity - SOAP::SOAPNonNegativeInteger
#   description - SOAP::SOAPString
class ContentRecord
  attr_accessor :partNumber
  attr_accessor :itemNumber
  attr_accessor :receivedQuantity
  attr_accessor :description

  def initialize(partNumber = nil, itemNumber = nil, receivedQuantity = nil, description = nil)
    @partNumber = partNumber
    @itemNumber = itemNumber
    @receivedQuantity = receivedQuantity
    @description = description
  end
end

# {http://fedex.com/ws/track/v19}CustomerExceptionRequestDetail
#   id - SOAP::SOAPString
#   statusCode - SOAP::SOAPString
#   statusDescription - SOAP::SOAPString
#   createTime - SOAP::SOAPDateTime
class CustomerExceptionRequestDetail
  attr_accessor :id
  attr_accessor :statusCode
  attr_accessor :statusDescription
  attr_accessor :createTime

  def initialize(id = nil, statusCode = nil, statusDescription = nil, createTime = nil)
    @id = id
    @statusCode = statusCode
    @statusDescription = statusDescription
    @createTime = createTime
  end
end

# {http://fedex.com/ws/track/v19}CustomsOptionDetail
#   type - FedexWebServices::Soap::Track::CustomsOptionType
#   description - SOAP::SOAPString
class CustomsOptionDetail
  attr_accessor :type
  attr_accessor :description

  def initialize(type = nil, description = nil)
    @type = type
    @description = description
  end
end

# {http://fedex.com/ws/track/v19}DateRange
#   begins - SOAP::SOAPDate
#   ends - SOAP::SOAPDate
class DateRange
  attr_accessor :begins
  attr_accessor :ends

  def initialize(begins = nil, ends = nil)
    @begins = begins
    @ends = ends
  end
end

# {http://fedex.com/ws/track/v19}DeliveryOptionEligibilityDetail
#   option - FedexWebServices::Soap::Track::DeliveryOptionType
#   eligibility - FedexWebServices::Soap::Track::EligibilityType
class DeliveryOptionEligibilityDetail
  attr_accessor :option
  attr_accessor :eligibility

  def initialize(option = nil, eligibility = nil)
    @option = option
    @eligibility = eligibility
  end
end

# {http://fedex.com/ws/track/v19}Dimensions
#   length - SOAP::SOAPNonNegativeInteger
#   width - SOAP::SOAPNonNegativeInteger
#   height - SOAP::SOAPNonNegativeInteger
#   units - FedexWebServices::Soap::Track::LinearUnits
class Dimensions
  attr_accessor :length
  attr_accessor :width
  attr_accessor :height
  attr_accessor :units

  def initialize(length = nil, width = nil, height = nil, units = nil)
    @length = length
    @width = width
    @height = height
    @units = units
  end
end

# {http://fedex.com/ws/track/v19}Distance
#   value - SOAP::SOAPDecimal
#   units - FedexWebServices::Soap::Track::DistanceUnits
class Distance
  attr_accessor :value
  attr_accessor :units

  def initialize(value = nil, units = nil)
    @value = value
    @units = units
  end
end

# {http://fedex.com/ws/track/v19}DocumentPart
#   sequenceNumber - SOAP::SOAPNonNegativeInteger
#   content - SOAP::SOAPBase64
class DocumentPart
  attr_accessor :sequenceNumber
  attr_accessor :content

  def initialize(sequenceNumber = nil, content = nil)
    @sequenceNumber = sequenceNumber
    @content = content
  end
end

# {http://fedex.com/ws/track/v19}EMailDetail
#   emailAddress - SOAP::SOAPString
#   name - SOAP::SOAPString
class EMailDetail
  attr_accessor :emailAddress
  attr_accessor :name

  def initialize(emailAddress = nil, name = nil)
    @emailAddress = emailAddress
    @name = name
  end
end

# {http://fedex.com/ws/track/v19}EdtExciseCondition
#   category - SOAP::SOAPString
#   value - SOAP::SOAPString
class EdtExciseCondition
  attr_accessor :category
  attr_accessor :value

  def initialize(category = nil, value = nil)
    @category = category
    @value = value
  end
end

# {http://fedex.com/ws/track/v19}FaxDetail
#   phoneNumber - SOAP::SOAPString
class FaxDetail
  attr_accessor :phoneNumber

  def initialize(phoneNumber = nil)
    @phoneNumber = phoneNumber
  end
end

# {http://fedex.com/ws/track/v19}GetTrackingDocumentsReply
#   highestSeverity - FedexWebServices::Soap::Track::NotificationSeverityType
#   notifications - FedexWebServices::Soap::Track::Notification
#   transactionDetail - FedexWebServices::Soap::Track::TransactionDetail
#   version - FedexWebServices::Soap::Track::VersionId
#   documents - FedexWebServices::Soap::Track::TrackingDocument
class GetTrackingDocumentsReply
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :documents

  def initialize(highestSeverity = nil, notifications = [], transactionDetail = nil, version = nil, documents = [])
    @highestSeverity = highestSeverity
    @notifications = notifications
    @transactionDetail = transactionDetail
    @version = version
    @documents = documents
  end
end

# {http://fedex.com/ws/track/v19}GetTrackingDocumentsRequest
#   webAuthenticationDetail - FedexWebServices::Soap::Track::WebAuthenticationDetail
#   clientDetail - FedexWebServices::Soap::Track::ClientDetail
#   transactionDetail - FedexWebServices::Soap::Track::TransactionDetail
#   version - FedexWebServices::Soap::Track::VersionId
#   selectionDetails - FedexWebServices::Soap::Track::TrackSelectionDetail
#   trackingDocumentSpecification - FedexWebServices::Soap::Track::TrackingDocumentSpecification
class GetTrackingDocumentsRequest
  attr_accessor :webAuthenticationDetail
  attr_accessor :clientDetail
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :selectionDetails
  attr_accessor :trackingDocumentSpecification

  def initialize(webAuthenticationDetail = nil, clientDetail = nil, transactionDetail = nil, version = nil, selectionDetails = [], trackingDocumentSpecification = nil)
    @webAuthenticationDetail = webAuthenticationDetail
    @clientDetail = clientDetail
    @transactionDetail = transactionDetail
    @version = version
    @selectionDetails = selectionDetails
    @trackingDocumentSpecification = trackingDocumentSpecification
  end
end

# {http://fedex.com/ws/track/v19}LocalTimeRange
#   begins - SOAP::SOAPString
#   ends - SOAP::SOAPString
class LocalTimeRange
  attr_accessor :begins
  attr_accessor :ends

  def initialize(begins = nil, ends = nil)
    @begins = begins
    @ends = ends
  end
end

# {http://fedex.com/ws/track/v19}Localization
#   languageCode - SOAP::SOAPString
#   localeCode - SOAP::SOAPString
class Localization
  attr_accessor :languageCode
  attr_accessor :localeCode

  def initialize(languageCode = nil, localeCode = nil)
    @languageCode = languageCode
    @localeCode = localeCode
  end
end

# {http://fedex.com/ws/track/v19}Measure
#   quantity - SOAP::SOAPDecimal
#   units - SOAP::SOAPString
class Measure
  attr_accessor :quantity
  attr_accessor :units

  def initialize(quantity = nil, units = nil)
    @quantity = quantity
    @units = units
  end
end

# {http://fedex.com/ws/track/v19}Money
#   currency - SOAP::SOAPString
#   amount - SOAP::SOAPDecimal
class Money
  attr_accessor :currency
  attr_accessor :amount

  def initialize(currency = nil, amount = nil)
    @currency = currency
    @amount = amount
  end
end

# {http://fedex.com/ws/track/v19}NaftaCommodityDetail
#   preferenceCriterion - FedexWebServices::Soap::Track::NaftaPreferenceCriterionCode
#   producerDetermination - FedexWebServices::Soap::Track::NaftaProducerDeterminationCode
#   producerId - SOAP::SOAPString
#   netCostMethod - FedexWebServices::Soap::Track::NaftaNetCostMethodCode
#   netCostDateRange - FedexWebServices::Soap::Track::DateRange
class NaftaCommodityDetail
  attr_accessor :preferenceCriterion
  attr_accessor :producerDetermination
  attr_accessor :producerId
  attr_accessor :netCostMethod
  attr_accessor :netCostDateRange

  def initialize(preferenceCriterion = nil, producerDetermination = nil, producerId = nil, netCostMethod = nil, netCostDateRange = nil)
    @preferenceCriterion = preferenceCriterion
    @producerDetermination = producerDetermination
    @producerId = producerId
    @netCostMethod = netCostMethod
    @netCostDateRange = netCostDateRange
  end
end

# {http://fedex.com/ws/track/v19}Notification
#   severity - FedexWebServices::Soap::Track::NotificationSeverityType
#   source - SOAP::SOAPString
#   code - SOAP::SOAPString
#   message - SOAP::SOAPString
#   localizedMessage - SOAP::SOAPString
#   messageParameters - FedexWebServices::Soap::Track::NotificationParameter
class Notification
  attr_accessor :severity
  attr_accessor :source
  attr_accessor :code
  attr_accessor :message
  attr_accessor :localizedMessage
  attr_accessor :messageParameters

  def initialize(severity = nil, source = nil, code = nil, message = nil, localizedMessage = nil, messageParameters = [])
    @severity = severity
    @source = source
    @code = code
    @message = message
    @localizedMessage = localizedMessage
    @messageParameters = messageParameters
  end
end

# {http://fedex.com/ws/track/v19}NotificationDetail
#   notificationType - FedexWebServices::Soap::Track::NotificationType
#   emailDetail - FedexWebServices::Soap::Track::EMailDetail
#   localization - FedexWebServices::Soap::Track::Localization
class NotificationDetail
  attr_accessor :notificationType
  attr_accessor :emailDetail
  attr_accessor :localization

  def initialize(notificationType = nil, emailDetail = nil, localization = nil)
    @notificationType = notificationType
    @emailDetail = emailDetail
    @localization = localization
  end
end

# {http://fedex.com/ws/track/v19}NotificationParameter
#   id - SOAP::SOAPString
#   value - SOAP::SOAPString
class NotificationParameter
  attr_accessor :id
  attr_accessor :value

  def initialize(id = nil, value = nil)
    @id = id
    @value = value
  end
end

# {http://fedex.com/ws/track/v19}PagingDetail
#   pagingToken - SOAP::SOAPString
#   numberOfResultsPerPage - SOAP::SOAPNonNegativeInteger
class PagingDetail
  attr_accessor :pagingToken
  attr_accessor :numberOfResultsPerPage

  def initialize(pagingToken = nil, numberOfResultsPerPage = nil)
    @pagingToken = pagingToken
    @numberOfResultsPerPage = numberOfResultsPerPage
  end
end

# {http://fedex.com/ws/track/v19}PieceCountVerificationDetail
#   countLocationType - FedexWebServices::Soap::Track::PieceCountLocationType
#   count - SOAP::SOAPNonNegativeInteger
#   description - SOAP::SOAPString
class PieceCountVerificationDetail
  attr_accessor :countLocationType
  attr_accessor :count
  attr_accessor :description

  def initialize(countLocationType = nil, count = nil, description = nil)
    @countLocationType = countLocationType
    @count = count
    @description = description
  end
end

# {http://fedex.com/ws/track/v19}SendNotificationsReply
#   highestSeverity - FedexWebServices::Soap::Track::NotificationSeverityType
#   notifications - FedexWebServices::Soap::Track::Notification
#   transactionDetail - FedexWebServices::Soap::Track::TransactionDetail
#   version - FedexWebServices::Soap::Track::VersionId
#   duplicateWaybill - SOAP::SOAPBoolean
#   moreDataAvailable - SOAP::SOAPBoolean
#   pagingToken - SOAP::SOAPString
#   packages - FedexWebServices::Soap::Track::TrackNotificationPackage
class SendNotificationsReply
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :duplicateWaybill
  attr_accessor :moreDataAvailable
  attr_accessor :pagingToken
  attr_accessor :packages

  def initialize(highestSeverity = nil, notifications = [], transactionDetail = nil, version = nil, duplicateWaybill = nil, moreDataAvailable = nil, pagingToken = nil, packages = [])
    @highestSeverity = highestSeverity
    @notifications = notifications
    @transactionDetail = transactionDetail
    @version = version
    @duplicateWaybill = duplicateWaybill
    @moreDataAvailable = moreDataAvailable
    @pagingToken = pagingToken
    @packages = packages
  end
end

# {http://fedex.com/ws/track/v19}SendNotificationsRequest
#   webAuthenticationDetail - FedexWebServices::Soap::Track::WebAuthenticationDetail
#   clientDetail - FedexWebServices::Soap::Track::ClientDetail
#   transactionDetail - FedexWebServices::Soap::Track::TransactionDetail
#   version - FedexWebServices::Soap::Track::VersionId
#   trackingNumber - SOAP::SOAPString
#   multiPiece - SOAP::SOAPBoolean
#   pagingToken - SOAP::SOAPString
#   trackingNumberUniqueId - SOAP::SOAPString
#   shipDateRangeBegin - SOAP::SOAPDate
#   shipDateRangeEnd - SOAP::SOAPDate
#   senderEMailAddress - SOAP::SOAPString
#   senderContactName - SOAP::SOAPString
#   eventNotificationDetail - FedexWebServices::Soap::Track::ShipmentEventNotificationDetail
class SendNotificationsRequest
  attr_accessor :webAuthenticationDetail
  attr_accessor :clientDetail
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :trackingNumber
  attr_accessor :multiPiece
  attr_accessor :pagingToken
  attr_accessor :trackingNumberUniqueId
  attr_accessor :shipDateRangeBegin
  attr_accessor :shipDateRangeEnd
  attr_accessor :senderEMailAddress
  attr_accessor :senderContactName
  attr_accessor :eventNotificationDetail

  def initialize(webAuthenticationDetail = nil, clientDetail = nil, transactionDetail = nil, version = nil, trackingNumber = nil, multiPiece = nil, pagingToken = nil, trackingNumberUniqueId = nil, shipDateRangeBegin = nil, shipDateRangeEnd = nil, senderEMailAddress = nil, senderContactName = nil, eventNotificationDetail = nil)
    @webAuthenticationDetail = webAuthenticationDetail
    @clientDetail = clientDetail
    @transactionDetail = transactionDetail
    @version = version
    @trackingNumber = trackingNumber
    @multiPiece = multiPiece
    @pagingToken = pagingToken
    @trackingNumberUniqueId = trackingNumberUniqueId
    @shipDateRangeBegin = shipDateRangeBegin
    @shipDateRangeEnd = shipDateRangeEnd
    @senderEMailAddress = senderEMailAddress
    @senderContactName = senderContactName
    @eventNotificationDetail = eventNotificationDetail
  end
end

# {http://fedex.com/ws/track/v19}ShipmentEventNotificationDetail
#   aggregationType - FedexWebServices::Soap::Track::ShipmentNotificationAggregationType
#   personalMessage - SOAP::SOAPString
#   eventNotifications - FedexWebServices::Soap::Track::ShipmentEventNotificationSpecification
class ShipmentEventNotificationDetail
  attr_accessor :aggregationType
  attr_accessor :personalMessage
  attr_accessor :eventNotifications

  def initialize(aggregationType = nil, personalMessage = nil, eventNotifications = [])
    @aggregationType = aggregationType
    @personalMessage = personalMessage
    @eventNotifications = eventNotifications
  end
end

# {http://fedex.com/ws/track/v19}ShipmentEventNotificationSpecification
#   role - FedexWebServices::Soap::Track::ShipmentNotificationRoleType
#   events - FedexWebServices::Soap::Track::NotificationEventType
#   notificationDetail - FedexWebServices::Soap::Track::NotificationDetail
#   formatSpecification - FedexWebServices::Soap::Track::ShipmentNotificationFormatSpecification
class ShipmentEventNotificationSpecification
  attr_accessor :role
  attr_accessor :events
  attr_accessor :notificationDetail
  attr_accessor :formatSpecification

  def initialize(role = nil, events = [], notificationDetail = nil, formatSpecification = nil)
    @role = role
    @events = events
    @notificationDetail = notificationDetail
    @formatSpecification = formatSpecification
  end
end

# {http://fedex.com/ws/track/v19}ShipmentNotificationFormatSpecification
#   type - FedexWebServices::Soap::Track::NotificationFormatType
class ShipmentNotificationFormatSpecification
  attr_accessor :type

  def initialize(type = nil)
    @type = type
  end
end

# {http://fedex.com/ws/track/v19}SignatureImageDetail
#   image - SOAP::SOAPBase64
#   notifications - FedexWebServices::Soap::Track::Notification
class SignatureImageDetail
  attr_accessor :image
  attr_accessor :notifications

  def initialize(image = nil, notifications = [])
    @image = image
    @notifications = notifications
  end
end

# {http://fedex.com/ws/track/v19}SpecialInstructionStatusDetail
#   status - FedexWebServices::Soap::Track::SpecialInstructionsStatusCode
#   statusCreateTime - SOAP::SOAPDateTime
class SpecialInstructionStatusDetail
  attr_accessor :status
  attr_accessor :statusCreateTime

  def initialize(status = nil, statusCreateTime = nil)
    @status = status
    @statusCreateTime = statusCreateTime
  end
end

# {http://fedex.com/ws/track/v19}StringBarcode
#   type - FedexWebServices::Soap::Track::StringBarcodeType
#   value - SOAP::SOAPString
class StringBarcode
  attr_accessor :type
  attr_accessor :value

  def initialize(type = nil, value = nil)
    @type = type
    @value = value
  end
end

# {http://fedex.com/ws/track/v19}TrackAdvanceNotificationDetail
#   estimatedTimeOfArrival - SOAP::SOAPDateTime
#   reason - SOAP::SOAPString
#   status - FedexWebServices::Soap::Track::TrackAdvanceNotificationStatusType
#   statusDescription - SOAP::SOAPString
#   statusTime - SOAP::SOAPDateTime
class TrackAdvanceNotificationDetail
  attr_accessor :estimatedTimeOfArrival
  attr_accessor :reason
  attr_accessor :status
  attr_accessor :statusDescription
  attr_accessor :statusTime

  def initialize(estimatedTimeOfArrival = nil, reason = nil, status = nil, statusDescription = nil, statusTime = nil)
    @estimatedTimeOfArrival = estimatedTimeOfArrival
    @reason = reason
    @status = status
    @statusDescription = statusDescription
    @statusTime = statusTime
  end
end

# {http://fedex.com/ws/track/v19}TrackChargeDetail
#   type - FedexWebServices::Soap::Track::TrackChargeDetailType
#   chargeAmount - FedexWebServices::Soap::Track::Money
class TrackChargeDetail
  attr_accessor :type
  attr_accessor :chargeAmount

  def initialize(type = nil, chargeAmount = nil)
    @type = type
    @chargeAmount = chargeAmount
  end
end

# {http://fedex.com/ws/track/v19}TrackDetail
#   notification - FedexWebServices::Soap::Track::Notification
#   trackingNumber - SOAP::SOAPString
#   barcode - FedexWebServices::Soap::Track::StringBarcode
#   trackingNumberUniqueIdentifier - SOAP::SOAPString
#   statusDetail - FedexWebServices::Soap::Track::TrackStatusDetail
#   informationNotes - FedexWebServices::Soap::Track::TrackInformationNoteDetail
#   customerExceptionRequests - FedexWebServices::Soap::Track::CustomerExceptionRequestDetail
#   reconciliation - FedexWebServices::Soap::Track::TrackReconciliation
#   serviceCommitMessage - SOAP::SOAPString
#   destinationServiceArea - SOAP::SOAPString
#   destinationServiceAreaDescription - SOAP::SOAPString
#   carrierCode - FedexWebServices::Soap::Track::CarrierCodeType
#   operatingCompany - FedexWebServices::Soap::Track::OperatingCompanyType
#   operatingCompanyOrCarrierDescription - SOAP::SOAPString
#   cartageAgentCompanyName - SOAP::SOAPString
#   productionLocationContactAndAddress - FedexWebServices::Soap::Track::ContactAndAddress
#   otherIdentifiers - FedexWebServices::Soap::Track::TrackOtherIdentifierDetail
#   formId - SOAP::SOAPString
#   service - FedexWebServices::Soap::Track::TrackServiceDescriptionDetail
#   packageWeight - FedexWebServices::Soap::Track::Weight
#   packageDimensions - FedexWebServices::Soap::Track::Dimensions
#   packageDimensionalWeight - FedexWebServices::Soap::Track::Weight
#   shipmentWeight - FedexWebServices::Soap::Track::Weight
#   packaging - FedexWebServices::Soap::Track::TrackPackagingDescriptionDetail
#   physicalPackagingType - FedexWebServices::Soap::Track::PhysicalPackagingType
#   packageSequenceNumber - SOAP::SOAPNonNegativeInteger
#   packageCount - SOAP::SOAPNonNegativeInteger
#   shipmentContentPieceCount - SOAP::SOAPNonNegativeInteger
#   packageContentPieceCount - SOAP::SOAPNonNegativeInteger
#   creatorSoftwareId - SOAP::SOAPString
#   charges - FedexWebServices::Soap::Track::TrackChargeDetail
#   nickName - SOAP::SOAPString
#   notes - SOAP::SOAPString
#   attributes - FedexWebServices::Soap::Track::TrackDetailAttributeType
#   shipmentContents - FedexWebServices::Soap::Track::ContentRecord
#   packageContents - SOAP::SOAPString
#   clearanceLocationCode - SOAP::SOAPString
#   clearanceBrokerage - FedexWebServices::Soap::Track::ClearanceBrokerageType
#   commodities - FedexWebServices::Soap::Track::Commodity
#   returnDetail - FedexWebServices::Soap::Track::TrackReturnDetail
#   customsOptionDetails - FedexWebServices::Soap::Track::CustomsOptionDetail
#   advanceNotificationDetail - FedexWebServices::Soap::Track::TrackAdvanceNotificationDetail
#   specialHandlings - FedexWebServices::Soap::Track::TrackSpecialHandling
#   payments - FedexWebServices::Soap::Track::TrackPayment
#   shipper - FedexWebServices::Soap::Track::Contact
#   possessionStatus - FedexWebServices::Soap::Track::TrackPossessionStatusType
#   shipperAddress - FedexWebServices::Soap::Track::Address
#   originLocationAddress - FedexWebServices::Soap::Track::Address
#   originStationId - SOAP::SOAPString
#   datesOrTimes - FedexWebServices::Soap::Track::TrackingDateOrTimestamp
#   totalTransitDistance - FedexWebServices::Soap::Track::Distance
#   distanceToDestination - FedexWebServices::Soap::Track::Distance
#   specialInstructions - FedexWebServices::Soap::Track::TrackSpecialInstruction
#   recipient - FedexWebServices::Soap::Track::Contact
#   lastUpdatedDestinationAddress - FedexWebServices::Soap::Track::Address
#   destinationAddress - FedexWebServices::Soap::Track::Address
#   holdAtLocationContact - FedexWebServices::Soap::Track::Contact
#   holdAtLocationAddress - FedexWebServices::Soap::Track::Address
#   destinationStationId - SOAP::SOAPString
#   destinationLocationAddress - FedexWebServices::Soap::Track::Address
#   destinationLocationType - FedexWebServices::Soap::Track::FedExLocationType
#   destinationLocationTimeZoneOffset - SOAP::SOAPString
#   actualDeliveryAddress - FedexWebServices::Soap::Track::Address
#   officeOrderDeliveryMethod - FedexWebServices::Soap::Track::OfficeOrderDeliveryMethodType
#   deliveryLocationType - FedexWebServices::Soap::Track::TrackDeliveryLocationType
#   deliveryLocationDescription - SOAP::SOAPString
#   deliveryAttempts - SOAP::SOAPNonNegativeInteger
#   deliverySignatureName - SOAP::SOAPString
#   pieceCountVerificationDetails - FedexWebServices::Soap::Track::PieceCountVerificationDetail
#   totalUniqueAddressCountInConsolidation - SOAP::SOAPNonNegativeInteger
#   availableImages - FedexWebServices::Soap::Track::AvailableImagesDetail
#   signature - FedexWebServices::Soap::Track::SignatureImageDetail
#   notificationEventsAvailable - FedexWebServices::Soap::Track::NotificationEventType
#   splitShipmentParts - FedexWebServices::Soap::Track::TrackSplitShipmentPart
#   deliveryOptionEligibilityDetails - FedexWebServices::Soap::Track::DeliveryOptionEligibilityDetail
#   events - FedexWebServices::Soap::Track::TrackEvent
class TrackDetail
  attr_accessor :notification
  attr_accessor :trackingNumber
  attr_accessor :barcode
  attr_accessor :trackingNumberUniqueIdentifier
  attr_accessor :statusDetail
  attr_accessor :informationNotes
  attr_accessor :customerExceptionRequests
  attr_accessor :reconciliation
  attr_accessor :serviceCommitMessage
  attr_accessor :destinationServiceArea
  attr_accessor :destinationServiceAreaDescription
  attr_accessor :carrierCode
  attr_accessor :operatingCompany
  attr_accessor :operatingCompanyOrCarrierDescription
  attr_accessor :cartageAgentCompanyName
  attr_accessor :productionLocationContactAndAddress
  attr_accessor :otherIdentifiers
  attr_accessor :formId
  attr_accessor :service
  attr_accessor :packageWeight
  attr_accessor :packageDimensions
  attr_accessor :packageDimensionalWeight
  attr_accessor :shipmentWeight
  attr_accessor :packaging
  attr_accessor :physicalPackagingType
  attr_accessor :packageSequenceNumber
  attr_accessor :packageCount
  attr_accessor :shipmentContentPieceCount
  attr_accessor :packageContentPieceCount
  attr_accessor :creatorSoftwareId
  attr_accessor :charges
  attr_accessor :nickName
  attr_accessor :notes
  attr_accessor :attributes
  attr_accessor :shipmentContents
  attr_accessor :packageContents
  attr_accessor :clearanceLocationCode
  attr_accessor :clearanceBrokerage
  attr_accessor :commodities
  attr_accessor :returnDetail
  attr_accessor :customsOptionDetails
  attr_accessor :advanceNotificationDetail
  attr_accessor :specialHandlings
  attr_accessor :payments
  attr_accessor :shipper
  attr_accessor :possessionStatus
  attr_accessor :shipperAddress
  attr_accessor :originLocationAddress
  attr_accessor :originStationId
  attr_accessor :datesOrTimes
  attr_accessor :totalTransitDistance
  attr_accessor :distanceToDestination
  attr_accessor :specialInstructions
  attr_accessor :recipient
  attr_accessor :lastUpdatedDestinationAddress
  attr_accessor :destinationAddress
  attr_accessor :holdAtLocationContact
  attr_accessor :holdAtLocationAddress
  attr_accessor :destinationStationId
  attr_accessor :destinationLocationAddress
  attr_accessor :destinationLocationType
  attr_accessor :destinationLocationTimeZoneOffset
  attr_accessor :actualDeliveryAddress
  attr_accessor :officeOrderDeliveryMethod
  attr_accessor :deliveryLocationType
  attr_accessor :deliveryLocationDescription
  attr_accessor :deliveryAttempts
  attr_accessor :deliverySignatureName
  attr_accessor :pieceCountVerificationDetails
  attr_accessor :totalUniqueAddressCountInConsolidation
  attr_accessor :availableImages
  attr_accessor :signature
  attr_accessor :notificationEventsAvailable
  attr_accessor :splitShipmentParts
  attr_accessor :deliveryOptionEligibilityDetails
  attr_accessor :events

  def initialize(notification = nil, trackingNumber = nil, barcode = nil, trackingNumberUniqueIdentifier = nil, statusDetail = nil, informationNotes = [], customerExceptionRequests = [], reconciliation = nil, serviceCommitMessage = nil, destinationServiceArea = nil, destinationServiceAreaDescription = nil, carrierCode = nil, operatingCompany = nil, operatingCompanyOrCarrierDescription = nil, cartageAgentCompanyName = nil, productionLocationContactAndAddress = nil, otherIdentifiers = [], formId = nil, service = nil, packageWeight = nil, packageDimensions = nil, packageDimensionalWeight = nil, shipmentWeight = nil, packaging = nil, physicalPackagingType = nil, packageSequenceNumber = nil, packageCount = nil, shipmentContentPieceCount = nil, packageContentPieceCount = nil, creatorSoftwareId = nil, charges = [], nickName = nil, notes = nil, attributes = [], shipmentContents = [], packageContents = [], clearanceLocationCode = nil, clearanceBrokerage = nil, commodities = [], returnDetail = nil, customsOptionDetails = [], advanceNotificationDetail = nil, specialHandlings = [], payments = [], shipper = nil, possessionStatus = nil, shipperAddress = nil, originLocationAddress = nil, originStationId = nil, datesOrTimes = [], totalTransitDistance = nil, distanceToDestination = nil, specialInstructions = [], recipient = nil, lastUpdatedDestinationAddress = nil, destinationAddress = nil, holdAtLocationContact = nil, holdAtLocationAddress = nil, destinationStationId = nil, destinationLocationAddress = nil, destinationLocationType = nil, destinationLocationTimeZoneOffset = nil, actualDeliveryAddress = nil, officeOrderDeliveryMethod = nil, deliveryLocationType = nil, deliveryLocationDescription = nil, deliveryAttempts = nil, deliverySignatureName = nil, pieceCountVerificationDetails = [], totalUniqueAddressCountInConsolidation = nil, availableImages = [], signature = nil, notificationEventsAvailable = [], splitShipmentParts = [], deliveryOptionEligibilityDetails = [], events = [])
    @notification = notification
    @trackingNumber = trackingNumber
    @barcode = barcode
    @trackingNumberUniqueIdentifier = trackingNumberUniqueIdentifier
    @statusDetail = statusDetail
    @informationNotes = informationNotes
    @customerExceptionRequests = customerExceptionRequests
    @reconciliation = reconciliation
    @serviceCommitMessage = serviceCommitMessage
    @destinationServiceArea = destinationServiceArea
    @destinationServiceAreaDescription = destinationServiceAreaDescription
    @carrierCode = carrierCode
    @operatingCompany = operatingCompany
    @operatingCompanyOrCarrierDescription = operatingCompanyOrCarrierDescription
    @cartageAgentCompanyName = cartageAgentCompanyName
    @productionLocationContactAndAddress = productionLocationContactAndAddress
    @otherIdentifiers = otherIdentifiers
    @formId = formId
    @service = service
    @packageWeight = packageWeight
    @packageDimensions = packageDimensions
    @packageDimensionalWeight = packageDimensionalWeight
    @shipmentWeight = shipmentWeight
    @packaging = packaging
    @physicalPackagingType = physicalPackagingType
    @packageSequenceNumber = packageSequenceNumber
    @packageCount = packageCount
    @shipmentContentPieceCount = shipmentContentPieceCount
    @packageContentPieceCount = packageContentPieceCount
    @creatorSoftwareId = creatorSoftwareId
    @charges = charges
    @nickName = nickName
    @notes = notes
    @attributes = attributes
    @shipmentContents = shipmentContents
    @packageContents = packageContents
    @clearanceLocationCode = clearanceLocationCode
    @clearanceBrokerage = clearanceBrokerage
    @commodities = commodities
    @returnDetail = returnDetail
    @customsOptionDetails = customsOptionDetails
    @advanceNotificationDetail = advanceNotificationDetail
    @specialHandlings = specialHandlings
    @payments = payments
    @shipper = shipper
    @possessionStatus = possessionStatus
    @shipperAddress = shipperAddress
    @originLocationAddress = originLocationAddress
    @originStationId = originStationId
    @datesOrTimes = datesOrTimes
    @totalTransitDistance = totalTransitDistance
    @distanceToDestination = distanceToDestination
    @specialInstructions = specialInstructions
    @recipient = recipient
    @lastUpdatedDestinationAddress = lastUpdatedDestinationAddress
    @destinationAddress = destinationAddress
    @holdAtLocationContact = holdAtLocationContact
    @holdAtLocationAddress = holdAtLocationAddress
    @destinationStationId = destinationStationId
    @destinationLocationAddress = destinationLocationAddress
    @destinationLocationType = destinationLocationType
    @destinationLocationTimeZoneOffset = destinationLocationTimeZoneOffset
    @actualDeliveryAddress = actualDeliveryAddress
    @officeOrderDeliveryMethod = officeOrderDeliveryMethod
    @deliveryLocationType = deliveryLocationType
    @deliveryLocationDescription = deliveryLocationDescription
    @deliveryAttempts = deliveryAttempts
    @deliverySignatureName = deliverySignatureName
    @pieceCountVerificationDetails = pieceCountVerificationDetails
    @totalUniqueAddressCountInConsolidation = totalUniqueAddressCountInConsolidation
    @availableImages = availableImages
    @signature = signature
    @notificationEventsAvailable = notificationEventsAvailable
    @splitShipmentParts = splitShipmentParts
    @deliveryOptionEligibilityDetails = deliveryOptionEligibilityDetails
    @events = events
  end
end

# {http://fedex.com/ws/track/v19}TrackEvent
#   timestamp - SOAP::SOAPDateTime
#   eventType - SOAP::SOAPString
#   eventDescription - SOAP::SOAPString
#   statusExceptionCode - SOAP::SOAPString
#   statusExceptionDescription - SOAP::SOAPString
#   barcodeEntryType - FedexWebServices::Soap::Track::BarcodeEntryType
#   address - FedexWebServices::Soap::Track::Address
#   stationId - SOAP::SOAPString
#   arrivalLocation - FedexWebServices::Soap::Track::ArrivalLocationType
class TrackEvent
  attr_accessor :timestamp
  attr_accessor :eventType
  attr_accessor :eventDescription
  attr_accessor :statusExceptionCode
  attr_accessor :statusExceptionDescription
  attr_accessor :barcodeEntryType
  attr_accessor :address
  attr_accessor :stationId
  attr_accessor :arrivalLocation

  def initialize(timestamp = nil, eventType = nil, eventDescription = nil, statusExceptionCode = nil, statusExceptionDescription = nil, barcodeEntryType = nil, address = nil, stationId = nil, arrivalLocation = nil)
    @timestamp = timestamp
    @eventType = eventType
    @eventDescription = eventDescription
    @statusExceptionCode = statusExceptionCode
    @statusExceptionDescription = statusExceptionDescription
    @barcodeEntryType = barcodeEntryType
    @address = address
    @stationId = stationId
    @arrivalLocation = arrivalLocation
  end
end

# {http://fedex.com/ws/track/v19}TrackInformationNoteDetail
#   code - SOAP::SOAPString
#   description - SOAP::SOAPString
class TrackInformationNoteDetail
  attr_accessor :code
  attr_accessor :description

  def initialize(code = nil, description = nil)
    @code = code
    @description = description
  end
end

# {http://fedex.com/ws/track/v19}TrackNotificationPackage
#   trackingNumber - SOAP::SOAPString
#   trackingNumberUniqueIdentifiers - SOAP::SOAPString
#   carrierCode - FedexWebServices::Soap::Track::CarrierCodeType
#   shipDate - SOAP::SOAPDate
#   destination - FedexWebServices::Soap::Track::Address
#   recipientDetails - FedexWebServices::Soap::Track::TrackNotificationRecipientDetail
class TrackNotificationPackage
  attr_accessor :trackingNumber
  attr_accessor :trackingNumberUniqueIdentifiers
  attr_accessor :carrierCode
  attr_accessor :shipDate
  attr_accessor :destination
  attr_accessor :recipientDetails

  def initialize(trackingNumber = nil, trackingNumberUniqueIdentifiers = nil, carrierCode = nil, shipDate = nil, destination = nil, recipientDetails = [])
    @trackingNumber = trackingNumber
    @trackingNumberUniqueIdentifiers = trackingNumberUniqueIdentifiers
    @carrierCode = carrierCode
    @shipDate = shipDate
    @destination = destination
    @recipientDetails = recipientDetails
  end
end

# {http://fedex.com/ws/track/v19}TrackNotificationRecipientDetail
class TrackNotificationRecipientDetail < ::Array
end

# {http://fedex.com/ws/track/v19}TrackOtherIdentifierDetail
#   packageIdentifier - FedexWebServices::Soap::Track::TrackPackageIdentifier
#   trackingNumberUniqueIdentifier - SOAP::SOAPString
#   carrierCode - FedexWebServices::Soap::Track::CarrierCodeType
class TrackOtherIdentifierDetail
  attr_accessor :packageIdentifier
  attr_accessor :trackingNumberUniqueIdentifier
  attr_accessor :carrierCode

  def initialize(packageIdentifier = nil, trackingNumberUniqueIdentifier = nil, carrierCode = nil)
    @packageIdentifier = packageIdentifier
    @trackingNumberUniqueIdentifier = trackingNumberUniqueIdentifier
    @carrierCode = carrierCode
  end
end

# {http://fedex.com/ws/track/v19}TrackPackageIdentifier
#   type - FedexWebServices::Soap::Track::TrackIdentifierType
#   value - SOAP::SOAPString
class TrackPackageIdentifier
  attr_accessor :type
  attr_accessor :value

  def initialize(type = nil, value = nil)
    @type = type
    @value = value
  end
end

# {http://fedex.com/ws/track/v19}TrackPackagingDescriptionDetail
#   type - SOAP::SOAPString
#   description - SOAP::SOAPString
class TrackPackagingDescriptionDetail
  attr_accessor :type
  attr_accessor :description

  def initialize(type = nil, description = nil)
    @type = type
    @description = description
  end
end

# {http://fedex.com/ws/track/v19}TrackPayment
#   classification - FedexWebServices::Soap::Track::TrackChargesPaymentClassificationType
#   type - FedexWebServices::Soap::Track::TrackPaymentType
#   description - SOAP::SOAPString
class TrackPayment
  attr_accessor :classification
  attr_accessor :type
  attr_accessor :description

  def initialize(classification = nil, type = nil, description = nil)
    @classification = classification
    @type = type
    @description = description
  end
end

# {http://fedex.com/ws/track/v19}TrackReconciliation
#   status - SOAP::SOAPString
#   description - SOAP::SOAPString
class TrackReconciliation
  attr_accessor :status
  attr_accessor :description

  def initialize(status = nil, description = nil)
    @status = status
    @description = description
  end
end

# {http://fedex.com/ws/track/v19}TrackReply
#   highestSeverity - FedexWebServices::Soap::Track::NotificationSeverityType
#   notifications - FedexWebServices::Soap::Track::Notification
#   transactionDetail - FedexWebServices::Soap::Track::TransactionDetail
#   version - FedexWebServices::Soap::Track::VersionId
#   completedTrackDetails - FedexWebServices::Soap::Track::CompletedTrackDetail
class TrackReply
  attr_accessor :highestSeverity
  attr_accessor :notifications
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :completedTrackDetails

  def initialize(highestSeverity = nil, notifications = [], transactionDetail = nil, version = nil, completedTrackDetails = [])
    @highestSeverity = highestSeverity
    @notifications = notifications
    @transactionDetail = transactionDetail
    @version = version
    @completedTrackDetails = completedTrackDetails
  end
end

# {http://fedex.com/ws/track/v19}TrackRequest
#   webAuthenticationDetail - FedexWebServices::Soap::Track::WebAuthenticationDetail
#   clientDetail - FedexWebServices::Soap::Track::ClientDetail
#   transactionDetail - FedexWebServices::Soap::Track::TransactionDetail
#   version - FedexWebServices::Soap::Track::VersionId
#   selectionDetails - FedexWebServices::Soap::Track::TrackSelectionDetail
#   transactionTimeOutValueInMilliseconds - SOAP::SOAPNonNegativeInteger
#   processingOptions - FedexWebServices::Soap::Track::TrackRequestProcessingOptionType
class TrackRequest
  attr_accessor :webAuthenticationDetail
  attr_accessor :clientDetail
  attr_accessor :transactionDetail
  attr_accessor :version
  attr_accessor :selectionDetails
  attr_accessor :transactionTimeOutValueInMilliseconds
  attr_accessor :processingOptions

  def initialize(webAuthenticationDetail = nil, clientDetail = nil, transactionDetail = nil, version = nil, selectionDetails = [], transactionTimeOutValueInMilliseconds = nil, processingOptions = [])
    @webAuthenticationDetail = webAuthenticationDetail
    @clientDetail = clientDetail
    @transactionDetail = transactionDetail
    @version = version
    @selectionDetails = selectionDetails
    @transactionTimeOutValueInMilliseconds = transactionTimeOutValueInMilliseconds
    @processingOptions = processingOptions
  end
end

# {http://fedex.com/ws/track/v19}TrackReturnDetail
#   movementStatus - FedexWebServices::Soap::Track::TrackReturnMovementStatusType
#   labelType - FedexWebServices::Soap::Track::TrackReturnLabelType
#   description - SOAP::SOAPString
#   authorizationName - SOAP::SOAPString
class TrackReturnDetail
  attr_accessor :movementStatus
  attr_accessor :labelType
  attr_accessor :description
  attr_accessor :authorizationName

  def initialize(movementStatus = nil, labelType = nil, description = nil, authorizationName = nil)
    @movementStatus = movementStatus
    @labelType = labelType
    @description = description
    @authorizationName = authorizationName
  end
end

# {http://fedex.com/ws/track/v19}TrackSelectionDetail
#   carrierCode - FedexWebServices::Soap::Track::CarrierCodeType
#   operatingCompany - FedexWebServices::Soap::Track::OperatingCompanyType
#   packageIdentifier - FedexWebServices::Soap::Track::TrackPackageIdentifier
#   trackingNumberUniqueIdentifier - SOAP::SOAPString
#   shipDateRangeBegin - SOAP::SOAPDate
#   shipDateRangeEnd - SOAP::SOAPDate
#   shipmentAccountNumber - SOAP::SOAPString
#   secureSpodAccount - SOAP::SOAPString
#   destination - FedexWebServices::Soap::Track::Address
#   pagingDetail - FedexWebServices::Soap::Track::PagingDetail
#   customerSpecifiedTimeOutValueInMilliseconds - SOAP::SOAPNonNegativeInteger
class TrackSelectionDetail
  attr_accessor :carrierCode
  attr_accessor :operatingCompany
  attr_accessor :packageIdentifier
  attr_accessor :trackingNumberUniqueIdentifier
  attr_accessor :shipDateRangeBegin
  attr_accessor :shipDateRangeEnd
  attr_accessor :shipmentAccountNumber
  attr_accessor :secureSpodAccount
  attr_accessor :destination
  attr_accessor :pagingDetail
  attr_accessor :customerSpecifiedTimeOutValueInMilliseconds

  def initialize(carrierCode = nil, operatingCompany = nil, packageIdentifier = nil, trackingNumberUniqueIdentifier = nil, shipDateRangeBegin = nil, shipDateRangeEnd = nil, shipmentAccountNumber = nil, secureSpodAccount = nil, destination = nil, pagingDetail = nil, customerSpecifiedTimeOutValueInMilliseconds = nil)
    @carrierCode = carrierCode
    @operatingCompany = operatingCompany
    @packageIdentifier = packageIdentifier
    @trackingNumberUniqueIdentifier = trackingNumberUniqueIdentifier
    @shipDateRangeBegin = shipDateRangeBegin
    @shipDateRangeEnd = shipDateRangeEnd
    @shipmentAccountNumber = shipmentAccountNumber
    @secureSpodAccount = secureSpodAccount
    @destination = destination
    @pagingDetail = pagingDetail
    @customerSpecifiedTimeOutValueInMilliseconds = customerSpecifiedTimeOutValueInMilliseconds
  end
end

# {http://fedex.com/ws/track/v19}TrackServiceDescriptionDetail
#   type - SOAP::SOAPString
#   description - SOAP::SOAPString
#   shortDescription - SOAP::SOAPString
class TrackServiceDescriptionDetail
  attr_accessor :type
  attr_accessor :description
  attr_accessor :shortDescription

  def initialize(type = nil, description = nil, shortDescription = nil)
    @type = type
    @description = description
    @shortDescription = shortDescription
  end
end

# {http://fedex.com/ws/track/v19}TrackSpecialHandling
#   type - SOAP::SOAPString
#   description - SOAP::SOAPString
#   paymentType - FedexWebServices::Soap::Track::TrackPaymentType
class TrackSpecialHandling
  attr_accessor :type
  attr_accessor :description
  attr_accessor :paymentType

  def initialize(type = nil, description = nil, paymentType = nil)
    @type = type
    @description = description
    @paymentType = paymentType
  end
end

# {http://fedex.com/ws/track/v19}TrackSpecialInstruction
#   description - SOAP::SOAPString
#   deliveryOption - FedexWebServices::Soap::Track::TrackDeliveryOptionType
#   statusDetail - FedexWebServices::Soap::Track::SpecialInstructionStatusDetail
#   originalEstimatedDeliveryTimestamp - SOAP::SOAPDateTime
#   originalRequestTime - SOAP::SOAPDateTime
#   requestedAppointmentTime - FedexWebServices::Soap::Track::AppointmentDetail
class TrackSpecialInstruction
  attr_accessor :description
  attr_accessor :deliveryOption
  attr_accessor :statusDetail
  attr_accessor :originalEstimatedDeliveryTimestamp
  attr_accessor :originalRequestTime
  attr_accessor :requestedAppointmentTime

  def initialize(description = nil, deliveryOption = nil, statusDetail = nil, originalEstimatedDeliveryTimestamp = nil, originalRequestTime = nil, requestedAppointmentTime = nil)
    @description = description
    @deliveryOption = deliveryOption
    @statusDetail = statusDetail
    @originalEstimatedDeliveryTimestamp = originalEstimatedDeliveryTimestamp
    @originalRequestTime = originalRequestTime
    @requestedAppointmentTime = requestedAppointmentTime
  end
end

# {http://fedex.com/ws/track/v19}TrackSplitShipmentPart
#   pieceCount - SOAP::SOAPPositiveInteger
#   timestamp - SOAP::SOAPDateTime
#   statusCode - SOAP::SOAPString
#   statusDescription - SOAP::SOAPString
class TrackSplitShipmentPart
  attr_accessor :pieceCount
  attr_accessor :timestamp
  attr_accessor :statusCode
  attr_accessor :statusDescription

  def initialize(pieceCount = nil, timestamp = nil, statusCode = nil, statusDescription = nil)
    @pieceCount = pieceCount
    @timestamp = timestamp
    @statusCode = statusCode
    @statusDescription = statusDescription
  end
end

# {http://fedex.com/ws/track/v19}TrackStatusAncillaryDetail
#   reason - SOAP::SOAPString
#   reasonDescription - SOAP::SOAPString
#   action - SOAP::SOAPString
#   actionDescription - SOAP::SOAPString
class TrackStatusAncillaryDetail
  attr_accessor :reason
  attr_accessor :reasonDescription
  attr_accessor :action
  attr_accessor :actionDescription

  def initialize(reason = nil, reasonDescription = nil, action = nil, actionDescription = nil)
    @reason = reason
    @reasonDescription = reasonDescription
    @action = action
    @actionDescription = actionDescription
  end
end

# {http://fedex.com/ws/track/v19}TrackStatusDetail
#   creationTime - SOAP::SOAPDateTime
#   code - SOAP::SOAPString
#   description - SOAP::SOAPString
#   location - FedexWebServices::Soap::Track::Address
#   ancillaryDetails - FedexWebServices::Soap::Track::TrackStatusAncillaryDetail
class TrackStatusDetail
  attr_accessor :creationTime
  attr_accessor :code
  attr_accessor :description
  attr_accessor :location
  attr_accessor :ancillaryDetails

  def initialize(creationTime = nil, code = nil, description = nil, location = nil, ancillaryDetails = [])
    @creationTime = creationTime
    @code = code
    @description = description
    @location = location
    @ancillaryDetails = ancillaryDetails
  end
end

# {http://fedex.com/ws/track/v19}TrackingBillOfLadingDocumentDetail
#   documentFormat - FedexWebServices::Soap::Track::TrackingDocumentFormat
class TrackingBillOfLadingDocumentDetail
  attr_accessor :documentFormat

  def initialize(documentFormat = nil)
    @documentFormat = documentFormat
  end
end

# {http://fedex.com/ws/track/v19}TrackingDateOrTimestamp
#   type - FedexWebServices::Soap::Track::TrackingDateOrTimestampType
#   dateOrTimestamp - SOAP::SOAPString
class TrackingDateOrTimestamp
  attr_accessor :type
  attr_accessor :dateOrTimestamp

  def initialize(type = nil, dateOrTimestamp = nil)
    @type = type
    @dateOrTimestamp = dateOrTimestamp
  end
end

# {http://fedex.com/ws/track/v19}TrackingDocument
#   type - FedexWebServices::Soap::Track::TrackingDocumentType
#   localizations - FedexWebServices::Soap::Track::Localization
#   imageType - FedexWebServices::Soap::Track::TrackingDocumentImageType
#   resolution - SOAP::SOAPNonNegativeInteger
#   parts - FedexWebServices::Soap::Track::DocumentPart
class TrackingDocument
  attr_accessor :type
  attr_accessor :localizations
  attr_accessor :imageType
  attr_accessor :resolution
  attr_accessor :parts

  def initialize(type = nil, localizations = [], imageType = nil, resolution = nil, parts = [])
    @type = type
    @localizations = localizations
    @imageType = imageType
    @resolution = resolution
    @parts = parts
  end
end

# {http://fedex.com/ws/track/v19}TrackingDocumentDispositionDetail
#   dispositionType - FedexWebServices::Soap::Track::TrackingDocumentDispositionType
#   eMailDetail - FedexWebServices::Soap::Track::TrackingDocumentEmailDetail
#   faxDetails - FedexWebServices::Soap::Track::FaxDetail
class TrackingDocumentDispositionDetail
  attr_accessor :dispositionType
  attr_accessor :eMailDetail
  attr_accessor :faxDetails

  def initialize(dispositionType = nil, eMailDetail = nil, faxDetails = [])
    @dispositionType = dispositionType
    @eMailDetail = eMailDetail
    @faxDetails = faxDetails
  end
end

# {http://fedex.com/ws/track/v19}TrackingDocumentEmailDetail
#   recipients - FedexWebServices::Soap::Track::EMailDetail
#   sender - FedexWebServices::Soap::Track::EMailDetail
#   localization - FedexWebServices::Soap::Track::Localization
#   personalMessage - SOAP::SOAPString
class TrackingDocumentEmailDetail
  attr_accessor :recipients
  attr_accessor :sender
  attr_accessor :localization
  attr_accessor :personalMessage

  def initialize(recipients = [], sender = nil, localization = nil, personalMessage = nil)
    @recipients = recipients
    @sender = sender
    @localization = localization
    @personalMessage = personalMessage
  end
end

# {http://fedex.com/ws/track/v19}TrackingDocumentFormat
#   dispositions - FedexWebServices::Soap::Track::TrackingDocumentDispositionDetail
#   grouping - FedexWebServices::Soap::Track::TrackingDocumentGroupingType
#   imageType - FedexWebServices::Soap::Track::TrackingDocumentImageType
#   localization - FedexWebServices::Soap::Track::Localization
class TrackingDocumentFormat
  attr_accessor :dispositions
  attr_accessor :grouping
  attr_accessor :imageType
  attr_accessor :localization

  def initialize(dispositions = [], grouping = nil, imageType = nil, localization = nil)
    @dispositions = dispositions
    @grouping = grouping
    @imageType = imageType
    @localization = localization
  end
end

# {http://fedex.com/ws/track/v19}TrackingDocumentSpecification
#   documentTypes - FedexWebServices::Soap::Track::TrackingDocumentType
#   billOfLadingDocumentDetail - FedexWebServices::Soap::Track::TrackingBillOfLadingDocumentDetail
#   freightBillingDocumentDetail - FedexWebServices::Soap::Track::TrackingFreightBillingDocumentDetail
#   signatureProofOfDeliveryDetail - FedexWebServices::Soap::Track::TrackingSignatureProofOfDeliveryDetail
class TrackingDocumentSpecification
  attr_accessor :documentTypes
  attr_accessor :billOfLadingDocumentDetail
  attr_accessor :freightBillingDocumentDetail
  attr_accessor :signatureProofOfDeliveryDetail

  def initialize(documentTypes = [], billOfLadingDocumentDetail = nil, freightBillingDocumentDetail = nil, signatureProofOfDeliveryDetail = nil)
    @documentTypes = documentTypes
    @billOfLadingDocumentDetail = billOfLadingDocumentDetail
    @freightBillingDocumentDetail = freightBillingDocumentDetail
    @signatureProofOfDeliveryDetail = signatureProofOfDeliveryDetail
  end
end

# {http://fedex.com/ws/track/v19}TrackingFreightBillingDocumentDetail
#   documentFormat - FedexWebServices::Soap::Track::TrackingDocumentFormat
class TrackingFreightBillingDocumentDetail
  attr_accessor :documentFormat

  def initialize(documentFormat = nil)
    @documentFormat = documentFormat
  end
end

# {http://fedex.com/ws/track/v19}TrackingSignatureProofOfDeliveryDetail
#   documentFormat - FedexWebServices::Soap::Track::TrackingDocumentFormat
class TrackingSignatureProofOfDeliveryDetail
  attr_accessor :documentFormat

  def initialize(documentFormat = nil)
    @documentFormat = documentFormat
  end
end

# {http://fedex.com/ws/track/v19}TransactionDetail
#   customerTransactionId - SOAP::SOAPString
#   localization - FedexWebServices::Soap::Track::Localization
class TransactionDetail
  attr_accessor :customerTransactionId
  attr_accessor :localization

  def initialize(customerTransactionId = nil, localization = nil)
    @customerTransactionId = customerTransactionId
    @localization = localization
  end
end

# {http://fedex.com/ws/track/v19}Weight
#   units - FedexWebServices::Soap::Track::WeightUnits
#   value - SOAP::SOAPDecimal
class Weight
  attr_accessor :units
  attr_accessor :value

  def initialize(units = nil, value = nil)
    @units = units
    @value = value
  end
end

# {http://fedex.com/ws/track/v19}WebAuthenticationDetail
#   parentCredential - FedexWebServices::Soap::Track::WebAuthenticationCredential
#   userCredential - FedexWebServices::Soap::Track::WebAuthenticationCredential
class WebAuthenticationDetail
  attr_accessor :parentCredential
  attr_accessor :userCredential

  def initialize(parentCredential = nil, userCredential = nil)
    @parentCredential = parentCredential
    @userCredential = userCredential
  end
end

# {http://fedex.com/ws/track/v19}WebAuthenticationCredential
#   key - SOAP::SOAPString
#   password - SOAP::SOAPString
class WebAuthenticationCredential
  attr_accessor :key
  attr_accessor :password

  def initialize(key = nil, password = nil)
    @key = key
    @password = password
  end
end

# {http://fedex.com/ws/track/v19}VersionId
#   serviceId - SOAP::SOAPString
#   major - SOAP::SOAPInt
#   intermediate - SOAP::SOAPInt
#   minor - SOAP::SOAPInt
class VersionId
  attr_accessor :serviceId
  attr_accessor :major
  attr_accessor :intermediate
  attr_accessor :minor

  def initialize(serviceId = nil, major = nil, intermediate = nil, minor = nil)
    @serviceId = serviceId
    @major = major
    @intermediate = intermediate
    @minor = minor
  end
end

# {http://fedex.com/ws/track/v19}AppointmentWindowType
class AppointmentWindowType < ::String
  AFTERNOON = new("AFTERNOON")
  LATE_AFTERNOON = new("LATE_AFTERNOON")
  MID_DAY = new("MID_DAY")
  MORNING = new("MORNING")
end

# {http://fedex.com/ws/track/v19}ArrivalLocationType
class ArrivalLocationType < ::String
  AIRPORT = new("AIRPORT")
  CUSTOMER = new("CUSTOMER")
  CUSTOMS_BROKER = new("CUSTOMS_BROKER")
  DELIVERY_LOCATION = new("DELIVERY_LOCATION")
  DESTINATION_AIRPORT = new("DESTINATION_AIRPORT")
  DESTINATION_FEDEX_FACILITY = new("DESTINATION_FEDEX_FACILITY")
  DROP_BOX = new("DROP_BOX")
  ENROUTE = new("ENROUTE")
  FEDEX_FACILITY = new("FEDEX_FACILITY")
  FEDEX_OFFICE_LOCATION = new("FEDEX_OFFICE_LOCATION")
  INTERLINE_CARRIER = new("INTERLINE_CARRIER")
  NON_FEDEX_FACILITY = new("NON_FEDEX_FACILITY")
  ORIGIN_AIRPORT = new("ORIGIN_AIRPORT")
  ORIGIN_FEDEX_FACILITY = new("ORIGIN_FEDEX_FACILITY")
  PICKUP_LOCATION = new("PICKUP_LOCATION")
  PLANE = new("PLANE")
  PORT_OF_ENTRY = new("PORT_OF_ENTRY")
  SHIP_AND_GET_LOCATION = new("SHIP_AND_GET_LOCATION")
  SORT_FACILITY = new("SORT_FACILITY")
  TURNPOINT = new("TURNPOINT")
  VEHICLE = new("VEHICLE")
end

# {http://fedex.com/ws/track/v19}AvailableImageType
class AvailableImageType < ::String
  BILL_OF_LADING = new("BILL_OF_LADING")
  SIGNATURE_PROOF_OF_DELIVERY = new("SIGNATURE_PROOF_OF_DELIVERY")
end

# {http://fedex.com/ws/track/v19}BarcodeEntryType
class BarcodeEntryType < ::String
  MANUAL_ENTRY = new("MANUAL_ENTRY")
  SCAN = new("SCAN")
end

# {http://fedex.com/ws/track/v19}CarrierCodeType
class CarrierCodeType < ::String
  FDXC = new("FDXC")
  FDXE = new("FDXE")
  FDXG = new("FDXG")
  FDXO = new("FDXO")
  FXCC = new("FXCC")
  FXFR = new("FXFR")
  FXSP = new("FXSP")
end

# {http://fedex.com/ws/track/v19}ClearanceBrokerageType
class ClearanceBrokerageType < ::String
  BROKER_INCLUSIVE = new("BROKER_INCLUSIVE")
  BROKER_INCLUSIVE_NON_RESIDENT_IMPORTER = new("BROKER_INCLUSIVE_NON_RESIDENT_IMPORTER")
  BROKER_SELECT = new("BROKER_SELECT")
  BROKER_SELECT_NON_RESIDENT_IMPORTER = new("BROKER_SELECT_NON_RESIDENT_IMPORTER")
  BROKER_UNASSIGNED = new("BROKER_UNASSIGNED")
end

# {http://fedex.com/ws/track/v19}CommodityPurposeType
class CommodityPurposeType < ::String
  BUSINESS = new("BUSINESS")
  CONSUMER = new("CONSUMER")
end

# {http://fedex.com/ws/track/v19}CustomsOptionType
class CustomsOptionType < ::String
  COURTESY_RETURN_LABEL = new("COURTESY_RETURN_LABEL")
  EXHIBITION_TRADE_SHOW = new("EXHIBITION_TRADE_SHOW")
  FAULTY_ITEM = new("FAULTY_ITEM")
  FOLLOWING_REPAIR = new("FOLLOWING_REPAIR")
  FOR_REPAIR = new("FOR_REPAIR")
  ITEM_FOR_LOAN = new("ITEM_FOR_LOAN")
  OTHER = new("OTHER")
  REJECTED = new("REJECTED")
  REPLACEMENT = new("REPLACEMENT")
  TRIAL = new("TRIAL")
end

# {http://fedex.com/ws/track/v19}DeliveryOptionType
class DeliveryOptionType < ::String
  INDIRECT_SIGNATURE_RELEASE = new("INDIRECT_SIGNATURE_RELEASE")
  REDIRECT_TO_HOLD_AT_LOCATION = new("REDIRECT_TO_HOLD_AT_LOCATION")
  REROUTE = new("REROUTE")
  RESCHEDULE = new("RESCHEDULE")
end

# {http://fedex.com/ws/track/v19}DistanceUnits
class DistanceUnits < ::String
  KM = new("KM")
  MI = new("MI")
end

# {http://fedex.com/ws/track/v19}EligibilityType
class EligibilityType < ::String
  ELIGIBLE = new("ELIGIBLE")
  INELIGIBLE = new("INELIGIBLE")
  POSSIBLY_ELIGIBLE = new("POSSIBLY_ELIGIBLE")
end

# {http://fedex.com/ws/track/v19}FedExLocationType
class FedExLocationType < ::String
  FEDEX_AUTHORIZED_SHIP_CENTER = new("FEDEX_AUTHORIZED_SHIP_CENTER")
  FEDEX_EXPRESS_STATION = new("FEDEX_EXPRESS_STATION")
  FEDEX_FACILITY = new("FEDEX_FACILITY")
  FEDEX_FREIGHT_SERVICE_CENTER = new("FEDEX_FREIGHT_SERVICE_CENTER")
  FEDEX_GROUND_TERMINAL = new("FEDEX_GROUND_TERMINAL")
  FEDEX_HOME_DELIVERY_STATION = new("FEDEX_HOME_DELIVERY_STATION")
  FEDEX_OFFICE = new("FEDEX_OFFICE")
  FEDEX_ONSITE = new("FEDEX_ONSITE")
  FEDEX_SELF_SERVICE_LOCATION = new("FEDEX_SELF_SERVICE_LOCATION")
  FEDEX_SHIPSITE = new("FEDEX_SHIPSITE")
  FEDEX_SHIP_AND_GET = new("FEDEX_SHIP_AND_GET")
  FEDEX_SMART_POST_HUB = new("FEDEX_SMART_POST_HUB")
end

# {http://fedex.com/ws/track/v19}ImageSizeType
class ImageSizeType < ::String
  LARGE = new("LARGE")
  SMALL = new("SMALL")
end

# {http://fedex.com/ws/track/v19}LinearUnits
class LinearUnits < ::String
  CM = new("CM")
  IN = new("IN")
end

# {http://fedex.com/ws/track/v19}NaftaNetCostMethodCode
class NaftaNetCostMethodCode < ::String
  NC = new("NC")
  NO = new("NO")
end

# {http://fedex.com/ws/track/v19}NaftaPreferenceCriterionCode
class NaftaPreferenceCriterionCode < ::String
  A = new("A")
  B = new("B")
  C = new("C")
  D = new("D")
  E = new("E")
  F = new("F")
end

# {http://fedex.com/ws/track/v19}NaftaProducerDeterminationCode
class NaftaProducerDeterminationCode < ::String
  NO_1 = new("NO_1")
  NO_2 = new("NO_2")
  NO_3 = new("NO_3")
  YES = new("YES")
end

# {http://fedex.com/ws/track/v19}NotificationEventType
class NotificationEventType < ::String
  ON_DELIVERY = new("ON_DELIVERY")
  ON_ESTIMATED_DELIVERY = new("ON_ESTIMATED_DELIVERY")
  ON_EXCEPTION = new("ON_EXCEPTION")
  ON_PICKUP_DRIVER_ARRIVED = new("ON_PICKUP_DRIVER_ARRIVED")
  ON_PICKUP_DRIVER_ASSIGNED = new("ON_PICKUP_DRIVER_ASSIGNED")
  ON_PICKUP_DRIVER_DEPARTED = new("ON_PICKUP_DRIVER_DEPARTED")
  ON_PICKUP_DRIVER_EN_ROUTE = new("ON_PICKUP_DRIVER_EN_ROUTE")
  ON_SHIPMENT = new("ON_SHIPMENT")
  ON_TENDER = new("ON_TENDER")
end

# {http://fedex.com/ws/track/v19}NotificationFormatType
class NotificationFormatType < ::String
  HTML = new("HTML")
  TEXT = new("TEXT")
end

# {http://fedex.com/ws/track/v19}NotificationSeverityType
class NotificationSeverityType < ::String
  ERROR = new("ERROR")
  FAILURE = new("FAILURE")
  NOTE = new("NOTE")
  SUCCESS = new("SUCCESS")
  WARNING = new("WARNING")
end

# {http://fedex.com/ws/track/v19}NotificationType
class NotificationType < ::String
  EMAIL = new("EMAIL")
end

# {http://fedex.com/ws/track/v19}OfficeOrderDeliveryMethodType
class OfficeOrderDeliveryMethodType < ::String
  COURIER = new("COURIER")
  OTHER = new("OTHER")
  PICKUP = new("PICKUP")
  SHIPMENT = new("SHIPMENT")
end

# {http://fedex.com/ws/track/v19}OperatingCompanyType
class OperatingCompanyType < ::String
  FEDEX_CARGO = new("FEDEX_CARGO")
  FEDEX_CORPORATE_SERVICES = new("FEDEX_CORPORATE_SERVICES")
  FEDEX_CORPORATION = new("FEDEX_CORPORATION")
  FEDEX_CUSTOMER_INFORMATION_SYSTEMS = new("FEDEX_CUSTOMER_INFORMATION_SYSTEMS")
  FEDEX_CUSTOM_CRITICAL = new("FEDEX_CUSTOM_CRITICAL")
  FEDEX_EXPRESS = new("FEDEX_EXPRESS")
  FEDEX_FREIGHT = new("FEDEX_FREIGHT")
  FEDEX_GROUND = new("FEDEX_GROUND")
  FEDEX_KINKOS = new("FEDEX_KINKOS")
  FEDEX_OFFICE = new("FEDEX_OFFICE")
  FEDEX_SERVICES = new("FEDEX_SERVICES")
  FEDEX_TRADE_NETWORKS = new("FEDEX_TRADE_NETWORKS")
end

# {http://fedex.com/ws/track/v19}PhysicalPackagingType
class PhysicalPackagingType < ::String
  BAG = new("BAG")
  BARREL = new("BARREL")
  BASKET = new("BASKET")
  BOX = new("BOX")
  BUCKET = new("BUCKET")
  BUNDLE = new("BUNDLE")
  CAGE = new("CAGE")
  CARTON = new("CARTON")
  CASE = new("CASE")
  CHEST = new("CHEST")
  CONTAINER = new("CONTAINER")
  CRATE = new("CRATE")
  CYLINDER = new("CYLINDER")
  DRUM = new("DRUM")
  ENVELOPE = new("ENVELOPE")
  HAMPER = new("HAMPER")
  OTHER = new("OTHER")
  PACKAGE = new("PACKAGE")
  PAIL = new("PAIL")
  PALLET = new("PALLET")
  PARCEL = new("PARCEL")
  PIECE = new("PIECE")
  REEL = new("REEL")
  ROLL = new("ROLL")
  SACK = new("SACK")
  SHRINK_WRAPPED = new("SHRINK_WRAPPED")
  SKID = new("SKID")
  TANK = new("TANK")
  TOTE_BIN = new("TOTE_BIN")
  TUBE = new("TUBE")
  UNIT = new("UNIT")
end

# {http://fedex.com/ws/track/v19}PieceCountLocationType
class PieceCountLocationType < ::String
  DESTINATION = new("DESTINATION")
  ORIGIN = new("ORIGIN")
end

# {http://fedex.com/ws/track/v19}ShipmentNotificationAggregationType
class ShipmentNotificationAggregationType < ::String
  PER_PACKAGE = new("PER_PACKAGE")
  PER_SHIPMENT = new("PER_SHIPMENT")
end

# {http://fedex.com/ws/track/v19}ShipmentNotificationRoleType
class ShipmentNotificationRoleType < ::String
  BROKER = new("BROKER")
  OTHER = new("OTHER")
  RECIPIENT = new("RECIPIENT")
  SHIPPER = new("SHIPPER")
end

# {http://fedex.com/ws/track/v19}SpecialInstructionsStatusCode
class SpecialInstructionsStatusCode < ::String
  ACCEPTED = new("ACCEPTED")
  CANCELLED = new("CANCELLED")
  DENIED = new("DENIED")
  HELD = new("HELD")
  MODIFIED = new("MODIFIED")
  RELINQUISHED = new("RELINQUISHED")
  REQUESTED = new("REQUESTED")
  SET = new("SET")
end

# {http://fedex.com/ws/track/v19}StringBarcodeType
class StringBarcodeType < ::String
  ADDRESS = new("ADDRESS")
  ASTRA = new("ASTRA")
  FEDEX_1D = new("FEDEX_1D")
  GROUND = new("GROUND")
  POSTAL = new("POSTAL")
  USPS = new("USPS")
end

# {http://fedex.com/ws/track/v19}TrackAdvanceNotificationStatusType
class TrackAdvanceNotificationStatusType < ::String
  BACK_ON_TRACK = new("BACK_ON_TRACK")
  FAIL = new("FAIL")
end

# {http://fedex.com/ws/track/v19}TrackChargeDetailType
class TrackChargeDetailType < ::String
  ORIGINAL_CHARGES = new("ORIGINAL_CHARGES")
end

# {http://fedex.com/ws/track/v19}TrackChargesPaymentClassificationType
class TrackChargesPaymentClassificationType < ::String
  DUTIES_AND_TAXES = new("DUTIES_AND_TAXES")
  TRANSPORTATION = new("TRANSPORTATION")
end

# {http://fedex.com/ws/track/v19}TrackDeliveryLocationType
class TrackDeliveryLocationType < ::String
  APARTMENT_OFFICE = new("APARTMENT_OFFICE")
  FEDEX_LOCATION = new("FEDEX_LOCATION")
  GATE_HOUSE = new("GATE_HOUSE")
  GUARD_OR_SECURITY_STATION = new("GUARD_OR_SECURITY_STATION")
  IN_BOND_OR_CAGE = new("IN_BOND_OR_CAGE")
  LEASING_OFFICE = new("LEASING_OFFICE")
  MAILROOM = new("MAILROOM")
  MAIN_OFFICE = new("MAIN_OFFICE")
  MANAGER_OFFICE = new("MANAGER_OFFICE")
  OTHER = new("OTHER")
  PHARMACY = new("PHARMACY")
  RECEPTIONIST_OR_FRONT_DESK = new("RECEPTIONIST_OR_FRONT_DESK")
  RENTAL_OFFICE = new("RENTAL_OFFICE")
  RESIDENCE = new("RESIDENCE")
  SHIPPING_RECEIVING = new("SHIPPING_RECEIVING")
end

# {http://fedex.com/ws/track/v19}TrackDeliveryOptionType
class TrackDeliveryOptionType < ::String
  APPOINTMENT = new("APPOINTMENT")
  DATE_CERTAIN = new("DATE_CERTAIN")
  ELECTRONIC_SIGNATURE_RELEASE = new("ELECTRONIC_SIGNATURE_RELEASE")
  EVENING = new("EVENING")
  REDIRECT_TO_HOLD_AT_LOCATION = new("REDIRECT_TO_HOLD_AT_LOCATION")
  REROUTE = new("REROUTE")
end

# {http://fedex.com/ws/track/v19}TrackDetailAttributeType
class TrackDetailAttributeType < ::String
  INCLUDED_IN_WATCHLIST = new("INCLUDED_IN_WATCHLIST")
end

# {http://fedex.com/ws/track/v19}TrackIdentifierType
class TrackIdentifierType < ::String
  BILL_OF_LADING = new("BILL_OF_LADING")
  COD_RETURN_TRACKING_NUMBER = new("COD_RETURN_TRACKING_NUMBER")
  CUSTOMER_AUTHORIZATION_NUMBER = new("CUSTOMER_AUTHORIZATION_NUMBER")
  CUSTOMER_REFERENCE = new("CUSTOMER_REFERENCE")
  DEPARTMENT = new("DEPARTMENT")
  DOCUMENT_AIRWAY_BILL = new("DOCUMENT_AIRWAY_BILL")
  FREE_FORM_REFERENCE = new("FREE_FORM_REFERENCE")
  GROUND_INTERNATIONAL = new("GROUND_INTERNATIONAL")
  GROUND_SHIPMENT_ID = new("GROUND_SHIPMENT_ID")
  GROUP_MPS = new("GROUP_MPS")
  INVOICE = new("INVOICE")
  JOB_GLOBAL_TRACKING_NUMBER = new("JOB_GLOBAL_TRACKING_NUMBER")
  ORDER_GLOBAL_TRACKING_NUMBER = new("ORDER_GLOBAL_TRACKING_NUMBER")
  ORDER_TO_PAY_NUMBER = new("ORDER_TO_PAY_NUMBER")
  OUTBOUND_LINK_TO_RETURN = new("OUTBOUND_LINK_TO_RETURN")
  PARTNER_CARRIER_NUMBER = new("PARTNER_CARRIER_NUMBER")
  PART_NUMBER = new("PART_NUMBER")
  PURCHASE_ORDER = new("PURCHASE_ORDER")
  REROUTE_TRACKING_NUMBER = new("REROUTE_TRACKING_NUMBER")
  RETURNED_TO_SHIPPER_TRACKING_NUMBER = new("RETURNED_TO_SHIPPER_TRACKING_NUMBER")
  RETURN_MATERIALS_AUTHORIZATION = new("RETURN_MATERIALS_AUTHORIZATION")
  SHIPPER_REFERENCE = new("SHIPPER_REFERENCE")
  STANDARD_MPS = new("STANDARD_MPS")
  TRACKING_NUMBER_OR_DOORTAG = new("TRACKING_NUMBER_OR_DOORTAG")
  TRANSPORTATION_CONTROL_NUMBER = new("TRANSPORTATION_CONTROL_NUMBER")
end

# {http://fedex.com/ws/track/v19}TrackPaymentType
class TrackPaymentType < ::String
  CASH_OR_CHECK_AT_DESTINATION = new("CASH_OR_CHECK_AT_DESTINATION")
  CASH_OR_CHECK_AT_ORIGIN = new("CASH_OR_CHECK_AT_ORIGIN")
  CREDIT_CARD_AT_DESTINATION = new("CREDIT_CARD_AT_DESTINATION")
  CREDIT_CARD_AT_ORIGIN = new("CREDIT_CARD_AT_ORIGIN")
  OTHER = new("OTHER")
  RECIPIENT_ACCOUNT = new("RECIPIENT_ACCOUNT")
  SHIPPER_ACCOUNT = new("SHIPPER_ACCOUNT")
  THIRD_PARTY_ACCOUNT = new("THIRD_PARTY_ACCOUNT")
end

# {http://fedex.com/ws/track/v19}TrackPossessionStatusType
class TrackPossessionStatusType < ::String
  BROKER = new("BROKER")
  CARRIER = new("CARRIER")
  CUSTOMS = new("CUSTOMS")
  RECIPIENT = new("RECIPIENT")
  SHIPPER = new("SHIPPER")
  SPLIT_STATUS = new("SPLIT_STATUS")
  TRANSFER_PARTNER = new("TRANSFER_PARTNER")
end

# {http://fedex.com/ws/track/v19}TrackRequestProcessingOptionType
class TrackRequestProcessingOptionType < ::String
  INCLUDE_DETAILED_SCANS = new("INCLUDE_DETAILED_SCANS")
end

# {http://fedex.com/ws/track/v19}TrackReturnLabelType
class TrackReturnLabelType < ::String
  EMAIL = new("EMAIL")
  PRINT = new("PRINT")
end

# {http://fedex.com/ws/track/v19}TrackReturnMovementStatusType
class TrackReturnMovementStatusType < ::String
  MOVEMENT_OCCURRED = new("MOVEMENT_OCCURRED")
  NO_MOVEMENT = new("NO_MOVEMENT")
end

# {http://fedex.com/ws/track/v19}TrackingDateOrTimestampType
class TrackingDateOrTimestampType < ::String
  ACTUAL_DELIVERY = new("ACTUAL_DELIVERY")
  ACTUAL_PICKUP = new("ACTUAL_PICKUP")
  ACTUAL_TENDER = new("ACTUAL_TENDER")
  ANTICIPATED_TENDER = new("ANTICIPATED_TENDER")
  APPOINTMENT_DELIVERY = new("APPOINTMENT_DELIVERY")
  ESTIMATED_DELIVERY = new("ESTIMATED_DELIVERY")
  ESTIMATED_PICKUP = new("ESTIMATED_PICKUP")
  ESTIMATED_RETURN_TO_STATION = new("ESTIMATED_RETURN_TO_STATION")
  SHIP = new("SHIP")
end

# {http://fedex.com/ws/track/v19}TrackingDocumentDispositionType
class TrackingDocumentDispositionType < ::String
  EMAIL = new("EMAIL")
  FAX = new("FAX")
  RETURN = new("RETURN")
end

# {http://fedex.com/ws/track/v19}TrackingDocumentGroupingType
class TrackingDocumentGroupingType < ::String
  CONSOLIDATED_BY_DOCUMENT_TYPE = new("CONSOLIDATED_BY_DOCUMENT_TYPE")
  INDIVIDUAL = new("INDIVIDUAL")
end

# {http://fedex.com/ws/track/v19}TrackingDocumentImageType
class TrackingDocumentImageType < ::String
  PDF = new("PDF")
  PNG = new("PNG")
end

# {http://fedex.com/ws/track/v19}TrackingDocumentType
class TrackingDocumentType < ::String
  BILL_OF_LADING = new("BILL_OF_LADING")
  FREIGHT_BILLING_DOCUMENT = new("FREIGHT_BILLING_DOCUMENT")
  SIGNATURE_PROOF_OF_DELIVERY = new("SIGNATURE_PROOF_OF_DELIVERY")
end

# {http://fedex.com/ws/track/v19}WeightUnits
class WeightUnits < ::String
  KG = new("KG")
  LB = new("LB")
end


end; end; end
