# encoding: UTF-8
# Generated by wsdl2ruby (SOAP4R-NG/2.0.4)
require_relative 'ValidationAvailabilityAndCommitmentServiceDefinitions.rb'
require_relative 'ValidationAvailabilityAndCommitmentServiceDefinitionsMappingRegistry.rb'
require 'soap/rpc/driver'

module FedexWebServices::Soap::ValidationAvailabilityAndCommitment

class ValidationAvailabilityAndCommitmentPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://wsbeta.fedex.com:443/web-services/ValidationAvailabilityAndCommitment"

  Methods = [
    [ "http://fedex.com/ws/vacs/v14/getAllServicesAndPackaging",
      "getAllServicesAndPackaging",
      [ [:in, "GetAllServicesAndPackagingRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/vacs/v14", "GetAllServicesAndPackagingRequest"]],
        [:out, "GetAllServicesAndPackagingReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/vacs/v14", "GetAllServicesAndPackagingReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://fedex.com/ws/vacs/v14/getAllSpecialServices",
      "getAllSpecialServices",
      [ [:in, "GetAllSpecialServicesRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/vacs/v14", "GetAllSpecialServicesRequest"]],
        [:out, "GetAllSpecialServicesReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/vacs/v14", "GetAllSpecialServicesReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ],
    [ "http://fedex.com/ws/vacs/v14/serviceAvailability",
      "serviceAvailability",
      [ [:in, "ServiceAvailabilityRequest", ["::SOAP::SOAPElement", "http://fedex.com/ws/vacs/v14", "ServiceAvailabilityRequest"]],
        [:out, "ServiceAvailabilityReply", ["::SOAP::SOAPElement", "http://fedex.com/ws/vacs/v14", "ServiceAvailabilityReply"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = ValidationAvailabilityAndCommitmentServiceDefinitionsMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = ValidationAvailabilityAndCommitmentServiceDefinitionsMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
